- font-codegen/src/fields.rs
- font-codegen/src/record.rs
- font-codegen/src/table.rs
- read-fonts/generated/font.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/generated/generated_gdef.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_hmtx.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_name.rs
- read-fonts/src/font_data.rs
- read-fonts/src/layout.rs
- read-fonts/src/layout/gpos.rs
- read-fonts/src/offset.rs
- read-fonts/src/table_ref.rs
- write-fonts/generated/generated_gdef.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/generated/generated_head.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/src/from_obj.rs
- write-fonts/src/layout.rs
- write-fonts/src/layout/gpos.rs
- write-fonts/src/layout/value_record.rs
In my initial design I had imagined that FontData would track its
position relative to the data root, so that when a parse error occured
we could store the absolute position of that error, which we could use
in debugging.
I never ended up really purusing this, and so the field was superfluous.
In addition to removing it, this moves to always passing FontData by
value; in effect FontData is a transparent wrapper over &'a [u8]. This
means that we can copy it around, and this in turn simplifies some of
our generated code.
> Remove FontData::pos and always pass by value

- write-fonts/src/layout.rs
- write-fonts/src/offsets.rs
This includes various methods for manipulating class/coverage tables, as well as methods for modifying the contents of offset markers.
This was part of the preliminary subsetting work, but should be useful for any sort of compilation.
> Add subsetting-motivated helpers to compile types

- font-codegen/src/fields.rs
- font-codegen/src/record.rs
- font-codegen/src/table.rs
- write-fonts/generated/generated_gdef.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/generated/generated_gsub.rs
- write-fonts/src/layout/gdef.rs
- write-fonts/src/tests/gpos.rs
A few tweaks to how we handle versioned fields during compilation:
- we now check the version before writing out versioned fields (was a bug)
- during our validation pass, if a table has a version we fetch it, and then check that any fields that are expected to be present for that version are actually present.
- we can now write out versioned scalars (was a bug)
> Fix compiling of versioned fields

- font-types/src/lib.rs
> [font-types] Reexport InvalidTag at crate root

- font-types/Cargo.toml
- font-types/README.md
- read-fonts/Cargo.toml
- write-fonts/Cargo.toml
- write-fonts/README.md
I'd like to get this up on crates.io so that I can start importing it more sanely elsewhere.
This gets us ready for an initial release there, setting version numbers and adding readmes and missing cargo manifest fields.
> Prepare to publish initial versions

- font-codegen/src/fields.rs
- read-fonts/generated/generated_gdef.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gsub.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_test.rs
- read-fonts/src/tests/gpos.rs
- read-fonts/src/tests/test_gdef.rs
- read-fonts/src/tests/test_gsub.rs
- write-fonts/generated/generated_gdef.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/generated/generated_gsub.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/generated/generated_test.rs
This is based on the name of the getter in the spec: if the raw getter is pluralized, we will pluralize the resolved getter.
For instance, for the raw 'attach_point_offsets' field, we will generate 'attach_points', but for 'attach_point_offset' we will generate 'attach_point'.
> [codegen] Pluralize getter names for arrays of offsets

- font-codegen/src/table.rs
- read-fonts/generated/font.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/generated/generated_gdef.rs
- read-fonts/generated/generated_glyf.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gsub.rs
- read-fonts/generated/generated_head.rs
- read-fonts/generated/generated_hhea.rs
- read-fonts/generated/generated_hmtx.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_maxp.rs
- read-fonts/generated/generated_name.rs
- read-fonts/generated/generated_post.rs
- read-fonts/generated/generated_test.rs
- read-fonts/src/lib.rs
- read-fonts/src/table_ref.rs
I realized we can just implement FontRead/FontReadWithArgs directly, which is easier to understand and lets us remove these traits completly from the API.
> Remove FontInfo/FontInfoWithArgs traits

- font-codegen/src/table.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_hmtx.rs
- read-fonts/generated/generated_layout.rs
At some point we changed the code we were generating such that this was no longer necessary.
> [codegen] Remove generated #[ignore(unused_parens)]

- font-codegen/src/record.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/src/font_data.rs
The only rationale for adding these is to make the struct usable via transmute & co, and that is not something these types are doing. Having these annotations is potentially confusing, and also likely produces a sub-optimal memory layout.
This also updates the signature for FontData::read_array_unchecked to include a T: FixedSized bound; this omission was a bug.
> [codegen] No repr(packed) for non-zerocopy records

- font-codegen/src/record.rs
- read-fonts/generated/generated_gpos.rs
> [codegen] Remove #[allow(unused_parens)] from record code

- read-fonts/generated/generated_cmap.rs
- resources/codegen_inputs/cmap.rs
We were generating this enum, but we were not actually using it in the cmap table.
> Actually use PlatformId in cmap

- font-types/src/version.rs
This gives us a way to specify custom implementations as needed (e.g. for OS/2).
> Make the 'rhs' of the Compatible trait be generic

- otexplorer/src/main.rs
Currently, we will just silently ignore any provided table argument that is not present in the font, which can be confusing. This is particularly so if a table name is misspelled or miscapitalized.
> [otexplorer] Print msg if requested tables are missing

- .github/workflows/rust.yml
This adds a github actions task that runs the codegen tool and ensures it does not produce any changes; this ensures that generated files which have been commited match the commited inputs.
This might cause issues when the files have been generated in windows? If this is the case we should figure out why, and get windows producing the same outputs as the unixes.
> [ci] Ensure codegen is up-to-date

- font-codegen/src/fields.rs
- font-codegen/src/parsing.rs
- otexplorer/src/print.rs
- otexplorer/src/query.rs
- read-fonts/generated/generated_colr.rs
- read-fonts/generated/generated_test.rs
- read-fonts/src/array.rs
- read-fonts/src/codegen_test.rs
- read-fonts/src/traversal.rs
- resources/codegen_inputs/colr.rs
- resources/codegen_inputs/test.rs
- write-fonts/generated/generated_test.rs
- write-fonts/src/offsets.rs
- write-fonts/src/write.rs
With this change, you can now have an offset where the inner type is either a) a scalar (`BigEndian<T>`) type, or a record. I believe this covers all the existing cases?
I've updated COLR to use the new syntax.
I've also added support in traversal and `otexplorer`, although I haven't played around much to see what the formatting looks like; we may want to tweak it.
This required some fairly deep changes in our parsing code since we need to distinguish between whether an offset's inner type is an array or not, and then if it *is* we also need to know if it's a scalar. Anyway, it wasn't so bad.
- closes #74 
- relevant to #68
> Support offsets to arrays

- font-types/src/lib.rs
- font-types/src/version.rs
- otexplorer/src/main.rs
- read-fonts/generated/font.rs
- read-fonts/src/lib.rs
- read-fonts/src/read.rs
- read-fonts/src/table_ref.rs
- resources/codegen_inputs/font.rs
- write-fonts/generated/generated_font.rs
Initial support for reading ttc files. Also adds an index command line flag to otexplorer.
The API probably needs some adjustments. `FontRef::new` should likely take an `index` parameter to make this consistent.
> Add font collection (ttc) support

- font-codegen/src/fields.rs
- read-fonts/generated/generated_colr.rs
- read-fonts/generated/generated_gdef.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gsub.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_test.rs
- read-fonts/src/traversal.rs
This becomes confusing once we also support offsets _to_ arrays.
> [traversal] Rename offset_array -> array_of_offsets

- font-codegen/Cargo.toml
- font-codegen/src/fields.rs
- font-codegen/src/lib.rs
- font-codegen/src/main.rs
- font-codegen/src/parsing.rs
- font-codegen/src/record.rs
- font-codegen/src/table.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/generated/generated_cpal.rs
- read-fonts/generated/generated_glyf.rs
- resources/codegen_inputs/cmap.rs
- resources/codegen_inputs/colr.rs
- resources/codegen_inputs/cpal.rs
- resources/codegen_inputs/font.rs
- resources/codegen_inputs/gdef.rs
- resources/codegen_inputs/glyf.rs
- resources/codegen_inputs/gpos.rs
- resources/codegen_inputs/gsub.rs
- resources/codegen_inputs/head.rs
- resources/codegen_inputs/hhea.rs
- resources/codegen_inputs/hmtx.rs
- resources/codegen_inputs/layout.rs
- resources/codegen_inputs/maxp.rs
- resources/codegen_inputs/name.rs
- resources/codegen_inputs/post.rs
- resources/codegen_inputs/stat.rs
- resources/codegen_inputs/test.rs
Remove BigEndian from codegen inputs. Output is unchanged, except a few places where a (pointless?) `BigEndian<u8>` is changed to naked `u8`. Fixes #71.
* FieldType can now be PendingResolution at the end of the parse phase
* There is now an analysis phase that attempts to resolve anything pending
* it is an error condition to have things pending at the end of analysis
I have a lot of noisy logging that I would ideally like to keep but have toggled off by default, akin to a debug level log in normal Google source. Not sure how best to get that in Rust. EDIT: per @dfrg I added log & env_logger which seem to work well.
> Drop BigEndian from codegen input

- font-codegen/src/lib.rs
- read-fonts/generated/generated_glyf.rs
- read-fonts/src/font_data.rs
- read-fonts/src/tables/glyf.rs
- resources/codegen_inputs/glyf.rs
This is basically just some cleanup of the hand-written glyf outline parsing code with a few additions (transforms and instructions for composite components).
I've added some docs, a basic test, and made some small stylistic changes as well.
Also (hopefully) fixes the newline issue on Windows.
> Update parser for glyf table

- write-fonts/src/layout/gpos.rs
Constructing these otherwise is a bit annoying. We might consider generating this sort of code at some point, but we wouldn't want it for all multi-format types; this is perhaps another interesting example where we would want to augment a future schema?
Actually this maybe clarifies part of how I've been thinking about schema/codegen, and which I've struggled to express coherently, thus far. Basically, there are two related and heavily overlapping tasks performed by the current codegen inputs: the first is that they serve as a description of the tables in the spec, and the second is that *they serve as a description of the code we wish to generate*, and these things do not perfectly line up.
> Add convenience init methods to AnchorTable

- font-codegen/src/formatting.rs
- font-codegen/src/lib.rs
- read-fonts/generated/generated_glyf.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_stat.rs
Because the contents of this macro is not value Rust code, rustfmt doesn't know what to do with it, which means we currently end up with monolithic single line blobs in our generated files for any declared bitflags.
This patch adds an additional post-processing step that finds any such declarations and manually reparses and rewrites them.
Maybe this is not a good idea? This was definitely me scratching an itch at the end of the day.
> [codegen] Manually reformat generated bitflags! decls

- font-codegen/src/fields.rs
- font-codegen/src/parsing.rs
- read-fonts/generated/generated_test.rs
- resources/codegen_inputs/test.rs
- write-fonts/generated/generated_cpal.rs
- write-fonts/generated/generated_gdef.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/generated/generated_gsub.rs
- write-fonts/generated/generated_hmtx.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/generated/generated_name.rs
- write-fonts/generated/generated_post.rs
- write-fonts/generated/generated_test.rs
- write-fonts/src/from_obj.rs
- write-fonts/src/offsets.rs
This cleans up our code for converting the parse types to the compile types.
Previously we were writing a lot of different bespoke impls for these conversions, using a variety of different patterns; this patch replaces a lot of those custom implementations with recursive calls to the `FromObjRef`/`FromTableRef` methods.
This simplifies our codegen code somewhat, but the main advantage is that it is more sustainable as we add new types; one particular wart of the previous implementation was that relied on a blanket impl of `From` to convert offset types, and this was going to break once we had offsets to arrays of records and not just offsets to arrays of scalars, which I ran into in STAT.
The one place where we still need bespoke impls is in handling arrays of offsets; this is because the …
> Rationalize from obj conversions

- write-fonts/src/offsets.rs
(based off of #96)
This seems generally useful, and is now possible since we've gotten rid of all the other weird From impls in #96
> Add blanket From<T> and From<Option<T>> for offset markers

- README.md
- resources/githooks/pre-commit
- resources/githooks/pre-push
This is opt-in, but it adds resources/githooks which includes pre-commit and pre-push (based on the presubmit.sh stand-alone script) that can be used with git hooks; it also documents how to configure git hooks in the readme.
(Just Merge Me™️)
> Setup shared git hooks

- read-fonts/src/tables/glyf.rs
- read-fonts/src/tables/loca.rs
Fixes some bugs in outline parsing and also adds a new `read_points` method (in addition to the iterator) in `SimpleGlyph` that is much faster when the user can provide preallocated buffers.
Ok to merge.
> Bug fixes and improvements to glyf outline parsing

- font-codegen/src/flags_enums.rs
- read-fonts/generated/generated_glyf.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_stat.rs
The default will always be empty flags. If this is not acceptable, we can add an attribute for specifying the desired default value, or an attribute indicating we won't generate a Default impl.
Default for enums is more annoying: not all enums have a meaningful default value, and we don't want to guess, so maybe for now the best bet is to just require the user to implement the trait, or otherwise just specify an explicit default value for each field in a table that contains a raw enum.
Another approach altogether (which had mentioned in relation to NameIds) would be to not use an actual rust enum to represent these enums, and make them instead by newtype structs with associated constants. This feels un-rusty, but also an awful lot simpler and closer to representing the underlying truth.
> Impl default for generated bitflags

- font-codegen/src/fields.rs
- font-codegen/src/lib.rs
- font-codegen/src/parsing.rs
- font-codegen/src/record.rs
Feel free to merge if acceptable. Helps with #82, though spots where we propagate an error with ? still get missed. Baby steps.
> Capture backtraces when codegen goes awry

- read-fonts/src/lib.rs
Simple change that re-exports font-types from read-fonts so that those types can be accessed from `read_fonts::types` without having to sync dependency versions in your own Cargo.toml.
> Re-export font-types in read-fonts

- font-codegen/src/table.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/generated/generated_gsub.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/src/from_obj.rs
- write-fonts/src/layout.rs
- write-fonts/src/layout/gpos.rs
- write-fonts/src/layout/gsub.rs
- write-fonts/src/offsets.rs
- write-fonts/src/tables/name.rs
- write-fonts/src/tests/gpos.rs
- write-fonts/src/validate.rs
This PR makes `OffsetMarker` not be an `Option` internally. It makes `OffsetMarker` implement `Deref<Target=T>`, (and `NullableOffsetMarker` impls `Deref<Target=Option<T>>`) so they now act basically as transparent wrappers.
Basically, I think this was a design mistake. From the commit message:
>For the record, the original idea was that if we were parsing an
existing font into compile types, and we encountered an offset that was
malformed, we would represent that with the `None` case, and then during
validation we would warn if an offset was unexpectedly null.
>As we now expect all tables and records to implement Default, we can
drop the Option, and just insert a new empty table in this particular
case.
This is a big API simplification, and should remove the need for the user to interact …
> No null offsetmarker

- font-codegen/src/fields.rs
- font-codegen/src/parsing.rs
- write-fonts/generated/generated_cpal.rs
- write-fonts/generated/generated_gdef.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/generated/generated_gsub.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/generated/generated_name.rs
- write-fonts/generated/generated_stat.rs
- write-fonts/generated/generated_test_offsets_arrays.rs
- write-fonts/generated/generated_test_records.rs
- write-fonts/src/layout.rs
- write-fonts/src/layout/gdef.rs
- write-fonts/src/layout/gpos.rs
- write-fonts/src/layout/gsub.rs
- write-fonts/src/tables/name.rs
- write-fonts/src/tests/gpos.rs
Speculative, but I think this is a good change.
Before this patch, types in `write-fonts` used the field names in the spec (snake-cased) which means that all offset fields were suffixed with `_offset`, and arrays of offsets were suffixed with `_offsets`. With this patch, we now use the same name for these fields as we do for the getters in read fonts which resolve the offsets; basically we convert `thing_offset` to `thing`, and `thing_offsets` to `things`, with a few special-cases to cover nouns with irregular pluralization.
This makes using `write-fonts` both a bit less verbose but also generally *less confusing*; in `write-fonts` these fields are concrete, and the new names reflect this.
> [codegen] Trim '_offset' from field names in write-fonts

- font-types/src/fixed.rs
I've run into some friction when using the fixed point types for computing things like deltas and variation region scalars. This adds `Mul`, `Div` and `Neg` impls for `Fixed` along with exposed associated constants for 0 and 1. Also adds a `to_fixed` conversion for `F2dot14`.
Ok to merge if there are no issues.
> Enhancements to the Fixed type

- read-fonts/generated/generated_layout.rs
- read-fonts/src/tables/layout.rs
- read-fonts/src/tables/lookupflag.rs
- resources/codegen_inputs/layout.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/src/tables/layout.rs
This can be shared between the two crates. Was blocked on 'extern scalar', which now exists.
Requires custom traversal logic, because traversal has know way of knowing about this type, and I'd like to avoid special-casing it in that code.
This will conflict with #142, and I don't have strong opinions about which should go in first.
> Add LookupFlag type

- read-fonts/src/tables/post.rs
There's an argument that maybe this should live somewhere else? But for now I just want to use it from fea-rs.
> Make DEFAULT_GLYPH_NAMES array public

- write-fonts/src/offsets.rs
- write-fonts/src/tables/layout.rs
We use a newtype pattern so we can differentiate between the GPOS and GSUB uses of certain common tables, but that is challange during compilation, where we don't really care about this distinction until the very end. This patch lets us work with the common tables while we build them up, and then cast them into the appropriate concrete type when we're done.
> Helpers for compiling shared layout tables

- font-codegen/src/fields.rs
- otexplorer/src/print.rs
- otexplorer/src/query.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/src/tables/layout.rs
- read-fonts/src/tables/value_record.rs
- read-fonts/src/traversal.rs
- resources/codegen_inputs/layout.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/src/tables/layout.rs
- write-fonts/src/tables/value_record.rs
This is a bit annoying because ValueRecord is hand-rolled, and so I had to rework a bunch of it to make it actually contain device tables.
My understanding is that this isn't really used much, but it's in the `feaLib` tests so that's enough for me 😅
> Compile Device tables, including in ValueRecord

- font-types/Cargo.toml
- read-fonts/Cargo.toml
- write-fonts/Cargo.toml
This will let me reference a stable version in fea-rs.
Also I apparently haven't been tagging releases, so will  start doing that.
> Bump versions to 0.0.3

- font-types/src/tag.rs
This improves the validation logic around tags to fix a few issues:
- tags cannot begin with spaces, but can contain trailing spaces
- validation logic was different between new and new_checked
In addition it adds an AsRef<[u8]> impl and a to_bytes method, for accessing the raw bytes.
> Tag tweaks

- otexplorer/src/main.rs
- read-fonts/src/lib.rs
- read-fonts/src/tests/test_data.rs
This changes `FontRef`, `FileRef`, and `CollectionRef` constructors to take `&'a [u8]` rather than `FontData<'a>`.
These types are useful as public interfaces in other crates, but the `FontData` parameter makes them cumbersome to construct and is mostly an implementation detail of read-fonts.
The changes here are all fairly simple. Ok to merge if it looks good.
> Change top level read-fonts type constructors to take a byte slice

- read-fonts/Cargo.toml
- read-fonts/build.rs
- read-fonts/src/tests/test_data.rs
- write-fonts/Cargo.toml
Instead of directly including these files, we now have a build script
that will copy the files into a build directory *if they exist*, and
will write an empty file in that location if they do not.
This ensures that include_bytes! always points to a file that exists,
which means that we will compile as a package.
> Fix include_bytes! breakage

- read-fonts/generated/generated_variations.rs
- read-fonts/src/tables/variations.rs
- resources/codegen_inputs/variations.rs
This can let our logic be more easily shared between read- and write-fonts.
@dfrg you were casting these to u32, but I don't think there's any overflow risk... was there some other rationale I might have missed?
> Variations: make more use of EntryFormat type

- resources/codegen_inputs/stat.rs
- write-fonts/generated/generated_stat.rs
- write-fonts/src/tables/stat.rs
- fixed a bug where we were calculating design_axis_count incorrectly
- add a custom constructor, to ensure elided_fallback_name_id is always present
- add a basic test case
> STAT compilation improvements

- font-codegen/README.md
- font-codegen/src/fields.rs
- font-codegen/src/parsing.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/generated/generated_glyf.rs
- read-fonts/generated/generated_gsub.rs
- read-fonts/generated/generated_hmtx.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_os2.rs
- read-fonts/generated/generated_variations.rs
- read-fonts/generated/generated_vmtx.rs
- read-fonts/src/lib.rs
- read-fonts/src/tables/layout.rs
- read-fonts/src/tables/variations.rs
- resources/codegen_inputs/cmap.rs
- resources/codegen_inputs/glyf.rs
- resources/codegen_inputs/gsub.rs
- resources/codegen_inputs/hmtx.rs
- resources/codegen_inputs/layout.rs
- resources/codegen_inputs/variations.rs
- resources/codegen_inputs/vmtx.rs
This introduces a new, more constrained grammar for this attribute, supporting two forms.
In the simple form, it accepts a single argument, which may be either a `$field`, a literal integer (`52`) or the special token `..`, which means "all remaining data", and is only valid for the last field in a table.
In the non-simple form, it accepts a function like syntax, where the 'function' is one of a small set of predefined options. These functions expect some set number of pre-defined arguments, which may be either `$field`s or literals.
supported 'functions' are currently `subtract`, `half`, `delta_value_count` and `map_data_size`.
----
This actually wasn't too bad? It's a lot more code to do what we want, but it does have a nice conceptual clarity, and it makes it much more possible to …
> [codegen] Make #[count] not accept expressions

- font-codegen/src/fields.rs
- font-codegen/src/parsing.rs
I realized there was a cleaner way of handling this, by moving the All variant out of CountArg and into the top-level Count struct; this reduces the number of special cases we need to think about.
> [codegen] Minor refactor of Count attr

- font-codegen/src/fields.rs
- font-codegen/src/parsing.rs
- read-fonts/generated/font.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/src/lib.rs
- resources/codegen_inputs/cmap.rs
- resources/codegen_inputs/font.rs
- write-fonts/generated/generated_font.rs
This might have made sense at some point, but it is no longer used and adds unnecessary complexity.
Getting this to work involves fixing the two remaining places where we
use untyped offsets:
- in the root TableRecord, where there may be arbitrary tags and
arbitrary tables, we just encode the offset as a u32.
- in cmap, we hadn't declared format 14 subtables correctly.
Just Merge Me™️
> [codegen] Remove support for unspecified offset targets

- font-types/src/raw.rs
As of rustc 1.66, rustdoc warns if you have anything that looks like an HTML tag (e.g., a generic) that is not enclosed in backticks.
Just Merge Me™️
> Fixup new rustdoc warning

- font-types/src/version.rs
- read-fonts/generated/generated_vhea.rs
- resources/codegen_inputs/vhea.rs
- write-fonts/generated/generated_vhea.rs
- write-fonts/src/tables/vhea.rs
We had specified this as MajorMinor (essentially a packed pair of u16s) but the type in the spec is Version16Dot16, which has its own special representation.
> Fix version type in vhea table

- resources/codegen_inputs/layout.rs
- write-fonts/generated/generated_layout.rs
It would be nice to make this be Option<u16>, but that is blocked on us having some slightly better way of specifying custom compilation behaviour; this is an improvement in the meantime.
> Set default value for LangSys::required_feature_index

- read-fonts/generated/generated_layout.rs
- resources/codegen_inputs/layout.rs
- write-fonts/generated/generated_layout.rs
These are currently defined as sequences of `GlyphId` but should actually be arbitrary `u16` class values as stored in a `ClassDef`.
> Change class sequence rules to use u16

- write-fonts/src/offsets.rs
- write-fonts/src/tables/layout.rs
- write-fonts/src/tables/value_record.rs
This makes ValueRecord hashable, and also adds a method to ValueFormat for computing the byte size of the record.
This has again highlighted one annoyance of this tool, which is there's no way to change or augment the set of traits that we derive for a given object; it would be nice if we could add support in codegen for this. (I am mentioning it here so that I can reference this in a new issue.)
> [write-fonts] Small ValueRecord additions

- write-fonts/src/tables/layout.rs
- There was a bug where we didn't dedupe entries in the coverage table before building
- There was an inefficiency where we would allow explicit class 0 entries when building classdefs
- I wanted a method on the write-fonts ClassDef to get the class for an item
> Coverage table & class def fixups

- font-types/src/fixed.rs
- read-fonts/src/tables/name.rs
This adds `to_bits` and `from_bits` conversions to the fixed point types. We can work toward better typing in punchcut, but these feel reasonable and will alleviate some of the pain of roundtripping through bytes in meantime. This also adds `Fixed::to_f2dot14`.
Additionally, derives `Clone` for `name::CharIter` in the spirit of making iterators clone where possible. I ran into this when working on localized string support in the new font metadata library.
Really small PR, so feel free to merge.
> Small changes to fixed point types and CharIter

- write-fonts/src/tables/glyf.rs
This can be handled somewhere higher up the stack, as needed.
> Don't rotate/reverse paths

- font-codegen/src/flags_enums.rs
- read-fonts/generated/generated_glyf.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gvar.rs
- read-fonts/generated/generated_stat.rs
- read-fonts/generated/generated_test_flags.rs
- read-fonts/generated/generated_variations.rs
- read-fonts/src/codegen_test.rs
This was overlooked when we stopped using bitflags.
fixes #233
(just merge me)
> Fix missing Ord impl for flag types

- write-fonts/src/tables/glyf.rs
Implements `FromObjRef` and `FromTableRef` for `write_fonts::tables::glyf::SimpleGlyph` to allow conversion from the read type to the write type using the `from_table_ref` method.
> Convert read SimpleGlyph to write SimpleGlyph

- font-types/src/lib.rs
- font-types/src/pen.rs
- write-fonts/src/lib.rs
- write-fonts/src/pens.rs
Having this makes porting algorithms implemented against pens in FontTools and nanoemoji easier.
My immediate need is to match https://github.com/googlefonts/ufo2ft/blob/dd738cdcddf61cce2a744d1cafab5c9b33e92dd4/Lib/ufo2ft/util.py#L205 for https://github.com/googlefonts/fontmake-rs/pull/123 so I need transform and reverse. I will presumably need a glyf pen too but I haven't done that yet.
> Implement a subset of FontTools Pens for write-fonts, leaning on kurbo for things like transform

- .github/workflows/rust.yml
- write-fonts/Cargo.toml
- write-fonts/src/pens.rs
This also sets 0.9.1 as the minimum kurbo version, to ensure we are always using testing against the new syntax.
> Adopt new svg format to match kurbo

- .github/workflows/rust.yml
There were a bunch of deprecation warnings in the CI logs, which raised two issues:
- we need to update any actions that we call from CI to [versions using node 16](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
- the actions-rs actions we've been using to install the toolchain and run cargo [are unmaintained](https://github.com/actions-rs/toolchain/issues/216), so we move over to another action from dtolonay
> [ci] Migrate from actions-rs, update checkout

- write-fonts/src/tables/glyf.rs
Things I learned trying to compile glyphs: I want to see more of the fields of Component.
This is a blocker for completing the merge of https://github.com/googlefonts/fontmake-rs/pull/120.
> Make Component friendlier to compiler

- resources/test_fonts/extract_glyphs.py
- resources/test_fonts/rebuild.sh
Changes `rebuild.sh` to activate the virtual environment before attempting to actually use it.
Fixes #268 
Just merge if it looks good.
> Fix broken call to extract_glyphs

- font-codegen/src/fields.rs
It's quite confusing if you name an offset to blah as blah as the codegen will emit two definitions of `blah()`. Enforce the naming convention - which we are already following - of a suffix on an offset field.
Hoisted out of https://github.com/googlefonts/fontations/pull/271
Fixes #270. Just merge me.
> Enforce the offset naming scheme.

- font-codegen/src/table.rs
Copied from record implementation; cmap hits this problem for tables
Hoisted out of #271.
Just merge me.
> Allow lots of args in a table ctor

- font-codegen/src/fields.rs
- font-codegen/src/parsing.rs
- otexplorer/src/main.rs
- read-fonts/generated/font.rs
- read-fonts/generated/generated_test_offsets_arrays.rs
- read-fonts/src/lib.rs
- resources/codegen_inputs/avar.rs
- resources/codegen_inputs/cmap.rs
- resources/codegen_inputs/font.rs
- resources/codegen_inputs/mvar.rs
- resources/codegen_inputs/test_offsets_arrays.rs
- write-fonts/generated/generated_test_offsets_arrays.rs
When they don't, such as when a reserved field is marked `#[skip_getter]` the write types get confused.
Most of the time the source of definition for a getter-less field should be a const, typically a  `#[compile(0]`:
```rust
/// Set to 0.
#[skip_getter]
#[compile(0)]
reserved_pad: u16,
```
Sometimes not, such as font.rs:
```rust
#[skip_getter]
offset: u32,
```
Hoisted out of #271. In #271 attribute `user_computed` was added to allow codegen to report errors when this is done by accident while still letting special butterfly fields exist. Here I have chosen to remove the skip getter from offset instead. That required tweaks to lib.rs.
> Require fields have some means of acquiring a value

- write-fonts/src/lib.rs
- write-fonts/src/round.rs
- write-fonts/src/tables/glyf.rs
Put it in write-fonts because `floor()` is not available in font-types. Modelled on std::ops, e.g. https://doc.rust-lang.org/std/ops/trait.Sub.html.
> Make ot_round more widely accessible and comment it

- font-codegen/src/record.rs
- font-codegen/src/table.rs
- read-fonts/generated/generated_fvar.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gvar.rs
- read-fonts/generated/generated_hmtx.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_stat.rs
- read-fonts/generated/generated_test_records.rs
- read-fonts/generated/generated_variations.rs
- read-fonts/generated/generated_vmtx.rs
- read-fonts/src/read.rs
- read-fonts/src/table_provider.rs
- read-fonts/src/tables/gvar.rs
- read-fonts/src/tables/instance_record.rs
- read-fonts/src/tables/loca.rs
- read-fonts/src/tables/variations.rs
- write-fonts/src/tables/hmtx.rs
I wanted to write this separately from #284, since maybe it is actually just a better solution overall? With this, the user should never need to interact with `FontReadWithArgs` at all, and can use the generated methods, where the arguments get names.
I used `read` instead of `new` for the method name because that's the name we generally use for constructors in `read-fonts`, otherwise I would prefer `new`.
> Better read arg constructors

- font-codegen/README.md
- font-codegen/src/fields.rs
- font-codegen/src/parsing.rs
- resources/codegen_inputs/name.rs
- resources/codegen_inputs/test_records.rs
- write-fonts/generated/generated_name.rs
- write-fonts/generated/generated_test_records.rs
- write-fonts/src/codegen_test.rs
- write-fonts/src/tables/name.rs
This closes #190, by providing a way to fully customize the compilation behaviour for a given field.
This differs from the `#[compile]` attribute in two important ways:
- `#[compile]` implies that this field is fully computed, which means we do not even include the field on the struct (since it would be ignored). `#[compile_with]` implies that the field exists, but that it requires special logic when compiled.
- with `#[compile]`, you must provide a value with the same type as the declared type of the field. With `#[compile_with]`, you name a method that will be called, and which can return *any* type that implements `FontWrite`.
This PR includes a commit that uses this new attribute to improve how we compile the strings in the `name` table.
Once this is merged, I will be able to also fix …
> Add #[compile_with] attribute

- skrifa/src/scale/glyf/hint/mod.rs
- skrifa/src/scale/glyf/mod.rs
- skrifa/src/scale/glyf/scaler.rs
This patch doesn't have any functional changes. Just a bit of code shuffling:
* Removes the unnecessary intermediate `GlyphScaler` type (and the double lifetime!)
* Moves font "instance" parameters (size, scale and coords) to the `ScalerFont` type
* Encapsulates hinting state in a new module
This is mostly so I can maintain the bytecode interpreter in a fork (for now!) without requiring changes to the main scaler code. It's also just better organized all around.
> [skrifa] cleanup and better encapsulate hinting

- write-fonts/src/tables/cmap.rs
Naively you'd think Unicode would be but you would be wrong; per @anthrotype fontmake emits Windows cmaps because they are the most widely supported.
Also, it helps a lot with binary search if things are in order.
> Fix Cmap::from_mappings

- font-codegen/Cargo.toml
- font-types/Cargo.toml
- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
Currently I cannot release write-fonts 0.1.5.
Just merge. And feel free to release font-types, read-fonts, and write-fonts too.
> Bump font-types and read-fonts because NameId touched them

- font-codegen/Cargo.toml
- font-types/Cargo.toml
- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- write-fonts/Cargo.toml
So I can release write support for avar, fvar, and hvar
> patch bump font-types and write-fonts

- .github/workflows/rust.yml
- resources/githooks/pre-push
- resources/scripts/check_no_println.sh
- resources/scripts/println_ignore.txt
- write-fonts/Cargo.toml
- write-fonts/src/tables/name.rs
similar to https://github.com/googlefonts/fontmake-rs/pull/204, with the only difference that in the case of fontations there are a couple of files where the use of `println!` is intentional and legitimate (font-codegen::preprocessor or otexplorer) so I added an allow-list to be able to exclude those from the check.
> add pre-push git hook to check for accidental println! statements

- write-fonts/Cargo.toml
So I can release #315 for https://github.com/googlefonts/fontmake-rs/issues/223
> Bump write-fonts to 0.1.7

- write-fonts/Cargo.toml
To release #322 so fontmake-rs can build a trivial font that is OTS-clean.
JMM.
> Update write-fonts to 0.1.8

- .github/workflows/rust.yml
- resources/githooks/pre-push
- skrifa/src/meta/strings.rs
- write-fonts/src/round.rs
As far as I can tell these tend to generally be useful, and with this off it's easy to commit bare hyperlinks that rustdoc yells at me for, locally.
~(currently checking that this actually fails, then I will fix the existing problems)~
JMM
> [ci] Treat rustdoc warnings as errors

- read-fonts/src/tables/variations.rs
- write-fonts/src/tables/variations.rs
This implements the logic for writing out packed deltas and packed point numbers, used in gvar & cvar.
Split out from #319, since this stands alone reasonably well.
> Write packed things

- write-fonts/src/graph.rs
- write-fonts/src/write.rs
This would previously just hit an unwrap and provide very little information. We still provide very little information, but we now do it earlier and in a controlled way.
This should at least explain what happens in cases like #303.
> Improve diagnostics when table packing fails

- skrifa/src/coords.rs
- skrifa/src/lib.rs
- skrifa/src/meta/metrics.rs
- skrifa/src/scale/mod.rs
- skrifa/src/scale/scaler.rs
- skrifa/src/setting.rs
- skrifa/src/size.rs
No functional changes here. This is the first in a series of cleanup PRs designed to prepare skrifa for initial release.
Removes the `scale::Variation` type and replaces it with a generic `Setting<T>` type along with a type alias `VariationSetting = Setting<f32>`. Setting is generic because the same structure will also be useful for OpenType feature settings at some point in the future.
Addresses one item on the list in #209.
Also moves a few types from lib.rs to modules.
> [skrifa] cleanup: replace Variation with generic Setting<T>

- write-fonts/src/tables/glyf.rs
As discussed in chat, we want to match fonttools behavior whereby the removal of the last point of a contour when it sits on top of the first point is only done for explicitly _closed_ contours (that end with a close_path), and not open contours, even if the points' coordinates do overlap.
https://github.com/fonttools/fonttools/blob/3b9a73ff8379ab49d3ce35aaaaf04b3a7d9d1655/Lib/fontTools/pens/pointPen.py#L321-L323
This makes sure we produce the same number of simple glyf points as fonttools, whether the path is open or closed. 
And also keep single point contours since fonttools does not prune them, and they are harmless.
> SimpleGlyph::from_kurbo: only pop the last_pt==move_pt for closed paths

- skrifa/src/lib.rs
- skrifa/src/scale/glyf/scaler.rs
- skrifa/src/scale/mod.rs
- skrifa/src/scale/scaler.rs
- skrifa/src/unique_id.rs
Again, following up on #209, replaces the raw u64 used as a font identifier/cache key with a new `UniqueId` type.
> [skrifa] replace raw u64 with UniqueId

- skrifa/Cargo.toml
- skrifa/README.md
- skrifa/src/lib.rs
- skrifa/src/meta/mod.rs
- skrifa/src/scale/error.rs
- skrifa/src/scale/mod.rs
- skrifa/src/scale/scaler.rs
- skrifa/src/setting.rs
This provides some more detailed documentation with a focus on the scale module. Also updates the readme to describe supported metadata.
[Readme rendered](https://github.com/dfrg/fontations/blob/skrifa-docs/skrifa/README.md)
No functional changes, but additional `From` impls for `Setting` were added because writing docs exposed that the shape of the `ScalerBuilder::variation_settings` API wasn't quite what I intended.
Closes #209
> Additional docs for skrifa

- write-fonts/Cargo.toml
So I can release #351, #353, #354 as these make it impossible for fontmake-rs to encode an interesting gvar.
JMM.
> write-fonts => 0.1.10

- .github/workflows/rust.yml
Runs `cargo test -p` for each package rather than a single `cargo test` for the whole workspace.
Closes #363
> [ci] test packages individually

- read-fonts/generated/generated_head.rs
- read-fonts/generated/generated_os2.rs
- resources/codegen_inputs/head.rs
- resources/codegen_inputs/os2.rs
- skrifa/src/attribute.rs
- skrifa/src/metrics.rs
- write-fonts/generated/generated_head.rs
- write-fonts/generated/generated_os2.rs
Adds flags types for `OS/2.fsSelection` and `head.macStyle`. Update uses to match. I didn't do `OS/2.fsType` because it has a weird mask component where bits don't precisely match intended usage.
Looks like this won't break fontmake-rs because it doesn't touch these fields yet.
Addresses half of #360.
JMM
> Add some more flags types

- font-codegen/README.md
- font-codegen/src/flags_enums.rs
- font-codegen/src/parsing.rs
- font-codegen/src/record.rs
- font-types/src/raw.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/generated/generated_colr.rs
- read-fonts/generated/generated_gdef.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_name.rs
- read-fonts/generated/generated_test_enum.rs
- read-fonts/src/tables/layout.rs
- resources/codegen_inputs/layout.rs
- resources/codegen_inputs/name.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/generated/generated_name.rs
- write-fonts/src/offsets.rs
- write-fonts/src/tables/layout.rs
- write-fonts/src/tables/name.rs
This was an old todo that I hit again when working on gvar; sometimes we want some particular table/record to implement a specific trait, on a case-by-case basis. This adds support for a new table-level attribute where you can provide a list of traits that will be derived for the type.
While getting this to work I ran into a few existing cases where we were not deriving traits that we could be, so I added those as well (for instance, we will now derive Ord/PartialOrd for generated flags as well as BigEndian<T>).
closes #186
> [codegen] Add #[derive_traits(..)] attribute

- font-types/src/raw.rs
- read-fonts/generated/generated_variations.rs
- resources/codegen_inputs/variations.rs
- write-fonts/generated/generated_variations.rs
- write-fonts/src/tables/variations.rs
This also adds a missing impl of Hash for BigEndian<T>
~based on #215 which should be merged first.~
> Use #[capabilites] on Tuple type

- read-fonts/src/tables/avar.rs
This is a curious case; avar is unique in that it has a hand written impl of the `VarSize` trait, and that impl was not accounting for the length of the count field itself when determining the size. This meant that the size could be zero, which would prevent us from advancing while iterating, leading to a hang.
This works fine when there was only a single segment map, since we do not truncate the data when reading the type; but it would cause us to read incorrect values when tables contained multiple axes.
This fixes the issue, and adds a test case with multiple axes.
The big question I have, though, is: why haven't we hit this before? Or maybe we have hit this before, and I haven't noticed?
cc @dfrg, want to double check that this makes sense?
fixes #367
> Fix miscalculation of segment map size in avar

- write-fonts/Cargo.toml
- write-fonts/src/lib.rs
- write-fonts/src/round.rs
- write-fonts/src/tables/glyf.rs
- write-fonts/src/util.rs
~~this is still quite messy and has no unit tests, but seems to work when I use this to build Oswald~~
EDIT: I've updated the PR adding tests, so this is now ready to review.
The PR adds a new public function to write_fonts::tables::glyf module called `simple_glyphs_from_kurbo`, which takes a slice of BezPaths and returns a vector of SimpleGlyphs (or an error if the input paths are not interpolation compatible).
Oncurve points that are impliable (i.e. at equal distance from preceding and following off-curve points) in _all_ the interpolatable paths are dropped from the SimpleGlyph contours.
The same function is also used in the existing SimpleGlyph::from_kurbo constructor to create one SimpleGlyph only instead of a Vec of them.
Linked draft PR in fontmake-rs to make use of this: …
> Filter implied on curves for interpolatable glyphs

- skrifa/src/string.rs
In response to #379. Adds an implementation of `Default` for `LocalizedStrings`, creating an iterator that yields nothing.
Just merge me.
> [skrifa] impl Default for LocalizedStrings

- font-types/src/fword.rs
- read-fonts/src/tables/colr.rs
This adds an intermediate "resolved" state for the paint graph where all values are promoted to `Fixed`, variation deltas are applied and transforms are collapsed into a single variant for each type (transform, translate, scale, rotate, skew).
The result is roughly equivalent to FreeType's [FT_COLR_Paint](https://freetype.org/freetype2/docs/reference/ft2-layer_management.html#ft_colr_paint) type. While the structure is slightly different, but the value of numeric fields _should_ be identical.
Also adds helper methods to the `Colr` table to retrieve base glyphs, layers, clip boxes, etc.
Lots of code, but the bulk of it is just mechanical type conversions.
There are no tests here yet. Opened #375 to track.
> [read-fonts] Add useful helpers for reading COLR glyphs

- font-codegen/Cargo.toml
- font-types/Cargo.toml
- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
I run
```
$ ./resources/scripts/bump-version font-types patch
```
and then
```
$ ./resources/scripts/bump-version read-fonts write-fonts skrifa minor
```
> bump minor version for read-fonts, write-fonts & skrifa; bump patch for font-types

- write-fonts/Cargo.toml
- write-fonts/src/graph.rs
- write-fonts/src/write.rs
Splits this in two, and adds a separate 'has_overflows' method that is slightly faster.
This includes the commit from #384, makes sense to just PR these together.
> Refactor topo sort method

- write-fonts/src/error.rs
- write-fonts/src/graph.rs
- write-fonts/src/lib.rs
- write-fonts/src/write.rs
Currently not very useful, but we will expose the graphviz support through this error type.
> Return an error if packing fails

- write-fonts/src/graph.rs
A port of the harfbuzz implementation; when overflows occur in subgraphs with multiple 32-bit roots (e.g. extension subtables sharing coverage tables or similar) we will iteratively select some subset of those roots and move them to another subgraph, duplicating and dependencies.
~based on #386, which should go in first.~
> Implement subgraph splitting for overflow resolution

- write-fonts/src/graph.rs
- write-fonts/src/write.rs
This is a pair of commits split out from the work on promotion and table splitting.
The first of these is a few small tweaks to the `TableWriter` type, renaming `write` to `write_bytes` and adding a `write` method for writing a scalar, which we will use when we do the manual table writing, as well as adding a convenience method for generating a graph from a root table.
The second of these commits moves the logic for actually writing out the final buffer into a `serialize` method on the `Graph` type, instead of being a free function in the `write` module. This was mainly motivated by making it easier during testing for us to dump out the bytes for a given graph, so that we can reparse them and verify things are as we expect.
> TableWriter and serialization tweaks

- read-fonts/src/tables/cmap.rs
- skrifa/src/charmap.rs
Adds iterators to retrieve mapping data for cmap formats 4, 12 and 14 in read-fonts.
Also exposes this functionality in skrifa's `Charmap`.
Closes #390
> Add iterators for cmap

- write-fonts/src/tables/glyf.rs
- write-fonts/src/tables/variations.rs
- write-fonts/src/util.rs
Directly port IUP py > Rust, including the test suite. I attempted fine-grained refs to the source material, lmk if I missed any.
Not yet hooked up to anything. Not meant to be idiomatic where doing so would cost clarity in comparison to Python. In Python optimize is triggered by https://github.com/fonttools/fonttools/blob/54e70b3ceff4d7ed34491a6512fb875408308405/Lib/fontTools/varLib/__init__.py#L239.
Please review primarily for equivalence to Python. Suggestions for how to make it more idiomatic are most welcome but I would prefer to address them in a subsequent PR.
> First tilt at porting IUP

- write-fonts/src/tables/glyf.rs
matches a similar change for `p0` in https://github.com/googlefonts/fontations/pull/395/commits/466e1b53
> small follow-up from #395

- write-fonts/Cargo.toml
https://github.com/googlefonts/fontations/pull/389  broke compatibility. I now can't build fontmake-rs against fontations latest for iup because fea-rs kerplodes. Step 1 toward fixing that. JMM.
> minor bump write-fonts => 0.3.0

- write-fonts/Cargo.toml
- write-fonts/src/lib.rs
Nameless errors are more intimidating than intended. Follow-on from #403.
> Make error types visible and bump-version minor on write-fonts

- write-fonts/Cargo.toml
- write-fonts/src/error.rs
fea-rs and fontmake-rs both expect this.
While we're at it, rig to release write-fonts.
Will need to update https://github.com/cmyr/fea-rs/pull/135 once published.
> Make write-fonts Error Send

- write-fonts/src/tables/variations.rs
Encountered an error trying to use IUP in fontmake-rs. Seems to be result of a collection of transcription errors; I'm mildly surprised the original test suite could pass. Added a new test to expose.
Use mutable delta and coord structures so we can get the result back out again.
I am currently not clear how the Python implementation makes sure that every call to optimize a set of deltas and coordinates performs the same rotation. Seems like it would be bad if that was not true.
Also, it's very annoying when write-fonts panics so use a result instead of an assert.
> Expose and fix bug w/IUP

- write-fonts/Cargo.toml
Intended to be used to release #411 for fontmake-rs
> write-fonts 0.3.2 => 0.3.3

- write-fonts/Cargo.toml
Intended to be used to release #417
> Bump write-fonts patch, now 0.3.5

- write-fonts/src/tables/os2.rs
https://learn.microsoft.com/en-us/typography/opentype/spec/os2 states "use of version 4 or later is strongly recommended." Python tooling appears to agree (OS/2 v4 vs v2 shows up diffing fontmake (python) vs fontc). v2, v3, and v4 have the same fields with modified wording for what some mean.
JMM
> Default OS/2 version to 4 not 2

- write-fonts/src/graph.rs
> Use u64 to store ObjectId

- font-codegen/Cargo.toml
- font-types/Cargo.toml
- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
Changes for font-types from font-types-v0.1.6 to 0.1.7
45277f2 bump patch for font-types and read-fonts
ec575c8 Forbid unsafe in font-types
Changes for read-fonts from read-fonts-v0.2.0 to 0.2.1
45277f2 bump patch for font-types and read-fonts
80a7a70 font-types => 0.1.6
1066567 Support writing sparse tuple stores
abc5939 Add iterators for cmap
> bump patch for font-types and read-fonts

- write-fonts/src/graph.rs
This moves most logs down to 'trace' level, and moves a few from 'info' down to 'debug'.
- closes #409 
JMM™️
> Use lower log levels in graph.rs

- font-types/src/raw.rs
- write-fonts/src/tables/cmap.rs
I'm sorry Rod, but this patch is going to make you mad.
Noticed this when reviewing old PRs; I thought it shouldn't be necessary to make everything a vec, since there should be PartialEq impls for comparing BigEndian types to their native values, and that should mean you can then compare slices directly, since that's provided by std.
And this works! With one small, infuriating caveat:
*We can impl PartialEq<T> for BigEndian<T>, but not the other way around*.
What this means is that you can write, `be_val == ne_val` but not `ne_val == be_val`. This is related to the orphan rules (https://doc.rust-lang.org/error_codes/E0210.html) and the tl;dr there is that we can't impl a foreign trait (PartialEq) on a foreign type (T). So we are stuck with this weird asymetry.
That said, I thought it …
> Cleanup cmap test assertions

- resources/codegen_inputs/avar.rs
- write-fonts/generated/generated_avar.rs
closes #373.
This was a minor oversight when this table was first added; making this change means we don't need to manually set the version for this table, since it is always 1.0.
Unfortunately this is a breaking change, since it removes the 'version' field from the public API.
> Use #[compile] to set avar version

- read-fonts/src/tables/glyf.rs
Fixes https://github.com/googlefonts/fontations/issues/439
> [read-fonts/glyf] Avoid overflow in Transform::compute_flags()

- write-fonts/src/graph.rs
- write-fonts/src/table_type.rs
- write-fonts/src/tables/layout.rs
- write-fonts/src/write.rs
The implementation here does not involve `write` types; instead we manually modify the graph in place. The implementation closely follows HarfBuzz.
This adds a `TableType` enum so that we can retain some type information after initial compilation; this somewhat overlaps with the `FontWrite::name` method added in #387, and maybe these could be combined?
This should get additional tests, and I'm working on porting some of the tests from the hb-repacker test suite.
closes #303.
> Implement GPOS/GSUB extension promotion

- font-codegen/src/fields.rs
- read-fonts/generated/generated_base.rs
- read-fonts/generated/generated_colr.rs
- read-fonts/generated/generated_gdef.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gsub.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_stat.rs
- read-fonts/generated/generated_test_offsets_arrays.rs
- read-fonts/generated/generated_variations.rs
- read-fonts/src/lib.rs
- read-fonts/src/offset_array.rs
- read-fonts/src/read.rs
- read-fonts/src/tables/stat.rs
- read-fonts/src/tables/variations.rs
- read-fonts/src/tests/gpos.rs
- read-fonts/src/tests/test_gdef.rs
- read-fonts/src/tests/test_gsub.rs
- write-fonts/generated/generated_base.rs
- write-fonts/generated/generated_gdef.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/generated/generated_gsub.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/generated/generated_stat.rs
- write-fonts/generated/generated_test_offsets_arrays.rs
- write-fonts/generated/generated_variations.rs
- write-fonts/src/from_obj.rs
- write-fonts/src/tables/gpos.rs
- write-fonts/src/tables/stat.rs
This was a long-standing papercut: in codegen we generate typed getters for offsets, but for arrays of offsets this was limited to generating an iterator.
This was a slightly annoying API, since an iterator cannot be retained, and does not provide random access.
This patch addresses this by adding a pair of concrete types that can wrap arrays of offsets and nullable offsets, and can dynamically resolve those offsets as they are accessed.
I've had this branch written for months and sitting around, so we might as well get it in now.
This is a breaking change.
> Add types to represent typed arrays of offsets

- skrifa/src/lib.rs
- skrifa/src/small_array.rs
Pulls out the `SmallArray` type from https://github.com/googlefonts/fontations/pull/443 with suggested improvements applied.
If this looks good, JMM!
> [skrifa] add SmallArray type

- skrifa/src/attribute.rs
- skrifa/src/charmap.rs
- skrifa/src/lib.rs
- skrifa/src/provider.rs
- skrifa/src/scale/glyf/deltas.rs
- skrifa/src/scale/glyf/hint/mod.rs
- skrifa/src/scale/glyf/scaler.rs
- skrifa/src/scale/mod.rs
- skrifa/src/scale/scaler.rs
- skrifa/src/scale/test.rs
- skrifa/src/small_array.rs
- skrifa/src/variation.rs
We had allows at crate level for unused and dead code to support feature gated hinting stuff but that has _allowed_ these things to proliferate in the codebase. This PR removes those, cleans up the mess and adds more targeted allows where necessary.
No functional changes, so JMM if it looks good.
> [skrifa] clean up warnings

- font-codegen/src/fields.rs
- read-fonts/generated/generated_base.rs
- read-fonts/generated/generated_colr.rs
- read-fonts/generated/generated_gdef.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gsub.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_stat.rs
- read-fonts/generated/generated_test_offsets_arrays.rs
- read-fonts/generated/generated_variations.rs
We currently generate return types like:
```rust
ArrayOfNullableOffsets<'a, ItemVariationData, Offset32>
```
where `ItemVariationData`  may need an explicit `'a` lifetime to be useful. This changes codegen to add those lifetimes when the target is not generic. @cmyr  please double check me on this.
> Add lifetime to T for generated ArrayOfOffsets

- read-fonts/src/tables/postscript/blend.rs
The `needs_update` machinery was removed in #458 but the unused field remained and the comments didn't reflect the change.
JMM
> [read-fonts/cff] fix comments and remove unused field

- font-codegen/src/fields.rs
- font-types/src/lib.rs
- font-types/src/raw.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/src/font_data.rs
- read-fonts/src/read.rs
- read-fonts/src/tables/avar.rs
- read-fonts/src/tables/value_record.rs
As part of the safety work, I wanted to simplify our font-types traits where possible.
In particular, this removes the `ReadScalar` trait, which was intended to provide a unified way to read both `Scalar` types as well as their `BigEndian` wrappers; but the former case is not common, and the extra trait was confusing, so I have separated this functionality.
This means that we will need separate methods for when we want to actually read a BigEndian value, but this doesn't seem too bad.
In addition this adds a new trait to more narrowly encode the condition that the Raw associated type on the Scalar trait should only ever be a fixed-size byte array.
> [font-types] Rework raw traits

- read-fonts/src/tables/postscript.rs
- read-fonts/src/tables/postscript/fd_select.rs
Implements the `glyph_id -> font_index` mapping for the FDSelect subtables.
> [read-fonts] CFF FDSelect lookups

- read-fonts/src/tables/postscript.rs
- read-fonts/src/tables/postscript/stack.rs
Adds a new `Stack` type that implements the operand stack for storing and processing intermediate values while parsing CFF DICTs and charstrings.
> [read-fonts] add CFF operand stack

- font-codegen/src/record.rs
- read-fonts/generated/font.rs
- read-fonts/generated/generated_avar.rs
- read-fonts/generated/generated_base.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/generated/generated_colr.rs
- read-fonts/generated/generated_cpal.rs
- read-fonts/generated/generated_fvar.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_hmtx.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_mvar.rs
- read-fonts/generated/generated_name.rs
- read-fonts/generated/generated_postscript.rs
- read-fonts/generated/generated_stat.rs
- read-fonts/generated/generated_test_enum.rs
- read-fonts/generated/generated_test_offsets_arrays.rs
- read-fonts/generated/generated_test_records.rs
- read-fonts/generated/generated_variations.rs
- read-fonts/src/array.rs
- read-fonts/src/font_data.rs
- read-fonts/src/lib.rs
- read-fonts/src/read.rs
This is based on top of #462, but can be reviewed separately.
This addresses the remaining concerns around our use of unsafe.
- It introduces a new trait, `JustBytes`, which is our equivalent of `FromBytes` in zerocopy. This trait is marked unsafe, and is intended to only be implemented during codegen, as well as for `BigEndian<T>` and `u8`.
- It adds `# Safety` and `// SAFETY` documentation blocks and comments where required.
In practice, the most important part of this PR is that we no longer use the general-purpose `FixedSize` trait as the trait bound on methods that involve reinterpreting bytes; this fixes the unsoundness where someone could call one of those methods with a type that implemented that trait, but violated the safety invariants.
- closes #228 
- closes #435 
- references …
> Tighten up safety guarantees

- read-fonts/src/tables/postscript.rs
- read-fonts/src/tables/postscript/charstring.rs
- read-fonts/src/tables/postscript/dict.rs
This is in similar fashion to the dictionary implementation, but just has the token parsing for now. Full evaluation is large so I decided to split that out into a separate PR.
The bit of churn in `dict` is just to simplify blend state processing.
> [read-fonts] CFF charstring basics

- write-fonts/src/write.rs
It's annoying to flip on info logging and get streams of writing table. Aside: many of them report unknown, e.g.:
```shell
...
2023-06-06T22:03:59.294694Z: ThreadId(2): INFO: writing table 'Unknown'
2023-06-06T22:03:59.294714Z: ThreadId(2): INFO: writing table 'Unknown'
2023-06-06T22:03:59.294738Z: ThreadId(2): INFO: writing table 'Unknown'
2023-06-06T22:03:59.294763Z: ThreadId(2): INFO: writing table 'Unknown'
2023-06-06T22:03:59.294792Z: ThreadId(2): INFO: writing table 'Unknown'
2023-06-06T22:03:59.294812Z: ThreadId(2): INFO: writing table 'Unknown'
2023-06-06T22:03:59.294832Z: ThreadId(2): INFO: writing table 'Unknown'
2023-06-06T22:03:59.294862Z: ThreadId(2): INFO: writing table 'Unknown'
2023-06-06T22:03:59.294888Z: ThreadId(2): INFO: writing table 'Unknown' …
```
> Stop spamming writing table to log

- write-fonts/src/tables/glyf.rs
Before we were simply testing that the euclidean distance between p1 and p0 was the same as the distance between p2 and p1, without actually enforcing that the three points were on the same line.
Here we check that the two vectors p1p0 and p2p1's x/y components are almost the same.
FontTools also does the same, see:
https://github.com/fonttools/fonttools/blob/66ce7c0e0c0ffdd11b2b5011323305f166ee3b85/Lib/fontTools/ttLib/tables/_g_l_y_f.py#L1599-L1601
> check that p0,p1,p2 are both collinear AND equidistant before making p1 implied

- write-fonts/Cargo.toml
```
$ cargo release changes
Changes for write-fonts from write-fonts-v0.6.0 to 0.6.1
6e1dfa7 get rid of the const/static because rustc is smarter than I thought
25dc979 make a simple isclose function that uses a static default FloatComparator
7a943a5 add a few tests for is_mid_point
8c75944 check if oncurves can be implied both before and after rounding
1bb5a33 implement OtRound for kurbo::Vec2
b7994cc port python's math.isclose so we can match 100% fonttools
59075aa write midpoint computation more tersely
89803d0 check that p0,p1,p2 are collinear as well as equidistant before dropping p1
60cb4f7 add (failing) repro for equidistant-not-collinear on-curve
38ddfbb Stop spamming writing table
```
> bump write-fonts to 0.6.1

- otexplorer/src/print.rs
- read-fonts/src/tables/post.rs
This adds a SAFETY comment on one use of unsafe, and in the other case a comment could not be written to explain how it is guaranteed to be safe, so remove the use of the unsafe method and use the safe from_utf8() instead.
Some followup work to address https://github.com/googlefonts/fontations/issues/435
> Add SAFETY comment and remove an unsafe

- font-codegen/src/record.rs
- read-fonts/generated/font.rs
- read-fonts/generated/generated_avar.rs
- read-fonts/generated/generated_base.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/generated/generated_colr.rs
- read-fonts/generated/generated_cpal.rs
- read-fonts/generated/generated_fvar.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_hmtx.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_mvar.rs
- read-fonts/generated/generated_name.rs
- read-fonts/generated/generated_postscript.rs
- read-fonts/generated/generated_stat.rs
- read-fonts/generated/generated_test_enum.rs
- read-fonts/generated/generated_test_offsets_arrays.rs
- read-fonts/generated/generated_test_records.rs
- read-fonts/generated/generated_variations.rs
- read-fonts/src/lib.rs
- read-fonts/src/read.rs
This prevents it from ever being implemented outside of `read-fonts`.
See discussion at https://github.com/googlefonts/fontations/issues/436#issuecomment-1583069720
> Make FromBytes sealed trait

- read-fonts/src/font_data.rs
- Adds a better comment explaining how we assert the absense of padding
- Removes the `pub` marker from `read_array_unchecked`
per discussion in https://github.com/googlefonts/fontations/issues/436
> Minor cleanup related to unsafe code

- read-fonts/generated/generated_cff.rs
- read-fonts/generated/generated_cff2.rs
- read-fonts/src/tables/cff.rs
- read-fonts/src/tables/cff2.rs
- read-fonts/src/tables/postscript/dict.rs
- read-fonts/src/tables/postscript/index.rs
- resources/codegen_inputs/cff.rs
- resources/codegen_inputs/cff2.rs
- write-fonts/generated/generated_cff.rs
- write-fonts/generated/generated_cff2.rs
This changes codegen inputs to generate fake "headers" for the CFF/CFF2 tables and then hand defines new top level tables for each that parse all data that doesn't require DICT evaluation.
This makes these tables follow a similar style to the rest of read-fonts.
> [read-fonts] Better CFF/CFF2 tables

- skrifa/src/lib.rs
- skrifa/src/metrics.rs
- skrifa/src/scale/mod.rs
@drott found that skrifa is computing incorrect advance widths for some variable fonts. Turns out that we didn't handle the case where the `HVAR` table is missing. This updates `GlyphMetrics` to fall back to `gvar` in that case.
> [skrifa] use gvar for metric deltas if hvar is missing

- font-types/src/tag.rs
- read-fonts/src/tests/layout.rs
- skrifa/src/scale/glyf/scaler.rs
Copy-pasting the first commit message:
his was ill-considered, and is not a good match for the ways this type
is used in practice.
More broadly, this change represents a loosening of constraints on the
contents of a Tag, to better match what we are actually doing anyway.
Concretely, this means that we are taking the spec as a *suggestion*,
but fully support invalid tags.
This also adds a `validate` method to Tag, which can be used to check
the validity of a tag that was created through one of the unchecked
paths.
The second commit changes our printing behaviour, so that if a tag is non-ascii we will print the numerical value of the non-ascii bytes.
> Remove panicking paths from Tag

- read-fonts/generated/generated_layout.rs
- resources/codegen_inputs/layout.rs
- write-fonts/generated/generated_layout.rs
This is mentioned in the spec but was overlooked during my first pass here.
> Make FeatureVariationRecord nullable

- resources/codegen_inputs/fvar.rs
- write-fonts/generated/generated_fvar.rs
- write-fonts/src/tables/fvar.rs
We can lean on codegen a bit more heavily here, which saves requiring the user to manually set certain fields.
> [write-fonts] Compute more fields on Fvar

- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
the codegen change I made also broke read-fonts, and skrifa uses read-fonts, so we need to bump those two as well.
> Bump read-fonts & skrifa

- font-types/src/fixed.rs
- font-types/src/point.rs
- read-fonts/src/tables/glyf.rs
Based on #490, add more inline attributes to functions in `font-types`. This was measurably affecting performance in the TrueType scaler.
Also adds lossy f32 conversions to the fixed point types and updates `glyf::to_path` to use them.
JMM
> [font-types] inline more things

- write-fonts/src/tables/layout.rs
Normally these constructors are generated automatically (if the constructor for the particular variant is autogenerated) but because Device has a hand-written constructor, we also need to manually add this.
JMM
> [write-fonts] Add DeviceOrVariationIndex::device

- font-types/src/tag.rs
I ran into a bit of a surprise when trying to update fontc to the our latest release: it was unable to deserialize our Tag type, complaining that,
> Error("axes[0].tag: invalid type: string \"wght\", expected a borrowed string")
This caused some headscratching, since I couldn't reproduce it in tests. It turned out to be a funny set of things:
- My implementation involved temporarily deserializing to a &str
- The implementation of Deserialize for &str only works when the input can be borrowed
- The deserialization code in fontc uses yaml::from_reader
- from_reader involves reading from a byte stream, which is transient
- ergo you cannot deserialize &str from a reader
The solution is to do a slightly more principled Deserialize implementation, where I explicitly implement the Visitor trait.
> [font-types] Ensure Tag impls DeserializeOwned

- font-codegen/src/table.rs
- write-fonts/generated/generated_base.rs
- write-fonts/generated/generated_cmap.rs
- write-fonts/generated/generated_gdef.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/generated/generated_gsub.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/generated/generated_postscript.rs
- write-fonts/generated/generated_stat.rs
- write-fonts/generated/generated_test_formats.rs
- write-fonts/generated/generated_variations.rs
- write-fonts/src/offsets.rs
That is, if a table `T` has multiple formats, for each format `S` we generate `From<S>` for `T`.
This is a minor quality-of-life improvement that should let me offer a better API in some parts of write-fonts (it's motivated by the case of Device/VariationIndex tables, but I've been meaning to do this for a while)
> [codegen] Generate From impls for format tables

- write-fonts/src/tables/glyf.rs
Enabled fontc to dump_table, write to a file, and recover the write-fonts type by reading the read-fonts type then from_table_ref'ing it. SimpleGlyph already knows this trick.
> Implement FromObjRef, FromTableRef for CompositeGlyph

- font-types/src/tag.rs
Previously it would have been possible to disable default features and also enable the serde feature, which would have caused compilation to fail. This now makes explicit that the serde feature requires std.
JMM
> [font-types] Make serde feature explicitly require std

- font-codegen/src/fields.rs
- read-fonts/generated/generated_variations.rs
- read-fonts/src/tables/postscript/blend.rs
- read-fonts/src/tables/variations.rs
- write-fonts/generated/generated_variations.rs
Seeing 'variation_datas' was making me irrationally angry.
> [codegen] Fix getter plural names containing  'data'

- write-fonts/src/graph.rs
- write-fonts/src/tables/gpos.rs
- write-fonts/src/tables/value_record.rs
These are annoying to construct, and are additionally annoying now that we support both Device & VariationIndex tables; hopefully builder methods will improve this situation.
There is also an additional, more pressing motivation for this work: I am going to need to add support for records that have explicit (non computed) value formats, which will involve adding a private field to ValueRecord, which means a pattern I've used elsewhere of relying on ..Default::default() to fill in missing vlaues will break.
> [write-fonts] Add builder methods to ValueRecord

- font-types/src/offset.rs
- read-fonts/src/tables/value_record.rs
- write-fonts/src/tables/value_record.rs
This enables us to correctly write a valuerecord with a specific format, writing null offsets as needed.
Working on this also revealed that we did not correctly represent null offsets during reading either, and so that is also addressed here.
based on #538, since this adds a non-public field to `ValueRecord` we can no longer use the `..Default::default()` trick to construct records.
>  Allow specifying explicit value format

- write-fonts/src/error.rs
- write-fonts/src/font_builder.rs
- write-fonts/src/lib.rs
- write-fonts/src/validate.rs
This makes a number of tweaks to the FontBuilder API, intended to improve ergonomics:
- A 'copy_missing_tables' method was added to simplify the common step of bulk copying existing tables from a FontRef
- The existing 'add_table' method was renamed 'add_raw',
- and a new 'add_table' method was added that removes the need for the caller to manually compile the table and provide the appropriate tag to the builder.
> [write-fonts] Improve builder API

- write-fonts/Cargo.toml
- write-fonts/src/font_builder.rs
This has now happened twice, so I'm inclined to turn on the setting that requires branches to be up to date in order to be mergeable.
> Fixup breakage between two outstanding PRs

- write-fonts/src/round.rs
The inline link was creating a very long line in the rendered docs.
JMM
> [write-fonts] Tweak OtRound docs

- write-fonts/src/tables/glyf.rs
- write-fonts/src/tables/glyf/simple.rs
- avoid using 'kurbo' in method names: this feels likely to confuse people who are unfamiliar with the kurbo crate
- rename 'BadKurbo' error to 'MalformedPath' (ditto)
- wrap simple_glyphs_from_kurbo with a method on Glyph: this saves us having to rexport another top-level item
- add docs to this method (I didn't initially understand the invariants)
-----
I think this is the last bit of breakage I have planned, will make sure all of this works with fontc and then do a release.
> [write-fonts] SimpleGlyph construction tweaks

- write-fonts/src/tables.rs
- write-fonts/src/tables/glyf.rs
- write-fonts/src/tables/glyf/composite.rs
- write-fonts/src/tables/glyf/simple.rs
- write-fonts/src/tables/loca.rs
This adds a loca module and a Loca table, and also adds a Glyph enum to represent either a simple or composite glyph.
A follow-up patch will add a builder type for constructing the glyf and loca tables.
I noticed that a lot of this stuff had been implemented in fontc, but it feels like it really belongs here.
> [write-fonts] glyf & loca improvements

- write-fonts/src/error.rs
- write-fonts/src/tables/glyf.rs
- write-fonts/src/tables/glyf/glyf_loca_builder.rs
- write-fonts/src/tables/loca.rs
- write-fonts/src/write.rs
This attempts to be a nice ergonomic way to build the glyf & loca tables.
Based on #558.
I have a few questions about this, and the fontc impl (maybe @anthrotype can answer these?)
- I've added special logic here so that if a glyph contains no outline/contour, we write no data for that glyph, but still add a (zero-length) entry to the loca table. I was looking at fontc's current impl, and it doesn't seem to do this? I assume it is an oversight there, but I'd love someone to double-check my work.
- Additionally the spec says that the first glyph is always the placeholder/notdef glyph. Should we be enforcing this somehow, or is it up to the caller? It feels like it has to be up to the caller, since we don't really have the relevant information...
> Add GlyfLocaBuilder

- font-codegen/README.md
- font-codegen/src/parsing.rs
- font-codegen/src/table.rs
- resources/codegen_inputs/layout.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/src/tables/layout.rs
Per discussion at https://github.com/cmyr/fea-rs/pull/185#discussion_r1269749806, this is adds a new type and a new enum variant that can be used to store the temporary ids assigned to `VariationIndex` tables during compilation. I quite like this; it simplifies the code in the VarStore builder, and it guarantees we never accidentally write one of these temporary values.
----
This is intended as a sentinal, which can be assigned a unique ID during compilation, and then remapped to the final VariationIndex values once the ItemVariationStore has been compiled.
This type will panic if we attempt to serialize it, which will ensure that we never accidentally write temporary values to our VariationIndex tables.
Although this is not part of the spec I am generating this in codegen since it's much …
> [write-fonts] Add 'PendingVariationIndex' table

- write-fonts/src/tables/loca.rs
If I'm moving this type into write-fonts I might as well grab the tests at the same time...
> [write-fonts] Migrate LocaFormat tests from fontc

- Cargo.toml
- write-fonts/Cargo.toml
- write-fonts/src/tables/variations/iup.rs
Fixes #564 
the input and expected result is taken from what fontmake/fonttools spit out for Oswald's glyph "two"
EDIT: Commit [36a8929](https://github.com/googlefonts/fontations/pull/565/commits/36a8929947c1147cb5f56c2d6117b1bb9b28ee3b) also fixes https://github.com/googlefonts/fontations/issues/567
> iup_delta_optimize: fix interpretation of contour_ends

- write-fonts/Cargo.toml
Bumped minor because https://github.com/googlefonts/fontations/pull/565 introduced a breaking change to iup_delta_optimize
full changelog from `cargo release changes`:
Changes for write-fonts from write-fonts-v0.13.0 to 0.14.0
36a8929 iup: when all deltas equal (0,0) return all Nones
1fce739 iup_delta_optimize: contour_ends contains endpoint indices, not contour lengths
8f3cc9b iup: add failing test case for Oswald glyph 'two'
35d6d13 add pretty_assertions to write-fonts' dev-dependencies
472cfa3 [write-fonts] Migrate LocaFormat tests from fontc
> bump write-fonts minor version to 0.14.0

- write-fonts/Cargo.toml
Fixes iup_contour_optimize bug: https://github.com/googlefonts/fontations/pull/572
```
Changes for write-fonts from write-fonts-v0.14.0 to 0.14.1
8300ac4 bump write-fonts to 0.14.1
68cbc79 must rotate back the indices in the solution, as we rotated the deltas themselves
d4bd486 iup_delta_optimize: add failing test to repro #571
```
> bump write-fonts to 0.14.1

- otexplorer/src/main.rs
fixes #573 
I'm avoiding making a decision about otexplorer's future as I do still find it occasionally helpful, even if its interpretation of certain tables needs to be rethought; in the meantime it might as well be a bit easier to use.
JMM
> [otexplorer] Improve help message

- read-fonts/src/tables/postscript/dict.rs
- skrifa/src/scale/cff/hint.rs
This code implements the first stage of CFF hinting. It uses hinting parameters captured from the Private DICT (blue values, fuzz, shift, etc) and combines them with a desired scale to generate a set of "blue zones" that will (in future PRs) be used along with per-glyph stem hints to generate the final hint map for grid fitting.
This is based on `cf2_blues_init` at https://gitlab.freedesktop.org/freetype/freetype/-/blob/80a507a6b8e3d2906ad2c8ba69329bd2fb2a85ef/src/psaux/psblues.c#L66
> [skrifa] CFF hinting part 1: scaling the blues

- write-fonts/src/tables/value_record.rs
Sanity checking that these tables are writing correctly in the simple case.
----
this is part of my looking into https://github.com/googlefonts/fontc/issues/402; in inspecting the generated font with otexplorer it reported that two of the VariationIndex tables were missing, e.g. the offsets were out of bounds for the data in the table. These tests pass, but we might as well keep them.
> [write-fonts] Add more tests of ValueRecord compilation

- write-fonts/src/graph.rs
- write-fonts/src/graph/splitting.rs
- write-fonts/src/table_type.rs
- write-fonts/src/tables/layout.rs
- write-fonts/src/write.rs
Built on top of #400, this adds the ability to split overflowing PairPos format 1 lookups.
I wanted to implement splitting of at least one lookup subtable on top of the promotion work in order to be confident that the approach I'd chosen for promotion would be suitable for splitting as well. Looks like it is?
> Add table splitting for PairPos format1

- font-codegen/src/formatting.rs
- font-codegen/src/parsing.rs
- font-codegen/src/table.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gsub.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/src/offset_array.rs
- read-fonts/src/tables/postscript/fd_select.rs
- read-fonts/src/tables/variations.rs
- skrifa/src/charmap.rs
- skrifa/src/scale/scaler.rs
- write-fonts/src/graph.rs
- write-fonts/src/graph/splitting.rs
- write-fonts/src/tables/glyf/composite.rs
- write-fonts/src/tables/glyf/simple.rs
- write-fonts/src/tables/stat.rs
- write-fonts/src/tables/value_record.rs
> Rustfmt and clippy

- write-fonts/src/offsets.rs
- write-fonts/src/table_type.rs
- write-fonts/src/write.rs
We weren't correctly reporting the table type from behind an offset.
> [write-fonts] Fixups for table_type

- write-fonts/src/graph.rs
- write-fonts/src/graph/splitting.rs
- write-fonts/src/table_type.rs
This fixes a bug where we were not including the size of subtables when deciding on split points for pairpos format 1 tables.
This also removes the 'can_potentially_promote_subtables' check; if we reach this point we have already overflowed, which means we are probably in GPOS and GSUB, and this method complicated testing, since splitting & expansion wouldn't be triggered on a lookup subtable if it was not an ancestor of GPOS/GSUB.
> [write-fonts] Include children in pairpos f1 size

- font-codegen/README.md
- resources/codegen_inputs/gpos.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/src/tables/gpos.rs
- write-fonts/src/tables/layout.rs
- write-fonts/src/tables/value_record.rs
In write-fonts we have a 'validation' pass before compilation, which is an opportunity to go and inspect the tables we're writing and make sure that the data is sane. A bunch of these checks are generated automatically, but a lot of the validation logic we would want is case-specific; in this case we have a mechanism for naming additional methods to be called in particular places during validation.
We haven't made a ton of use of this custom validation logic, but we probably should, since it helps us be much more confident in the data that we're writing.
This adds some custom validation logic to the two PairPos subtable formats; there was something fishy happening here that was messing up my table packing.
Another thing I'm reminding of while doing this work is how tricky it is to …
> Improve PairPos validation

- write-fonts/src/font_builder.rs
This generally makes this error more useful, and makes it possible for an outside user (e.g. fontc) to generate a graphviz dump for a given failure.
~(also bumps version to 0.14.2, so I can release this if approved)~
> Make fields on BuilderError public

- read-fonts/src/tables/layout.rs
- read-fonts/src/tables/value_record.rs
- write-fonts/src/font_builder.rs
- write-fonts/src/graph.rs
- write-fonts/src/graph/splitting.rs
- write-fonts/src/tables/glyf/glyf_loca_builder.rs
- write-fonts/src/write.rs
Based on top of #595.
This implements subtable splitting for PairPos format 2 (class-based) subtables. It is based on the implementation in hb-repacker.
This is one of the more complicated tables to split, and writing this patch uncovered a number of other bugs in the existing implementation, which have been fixed separately.
With this patch, we are once again compiling our target fonts.
> [write-fonts] Split PairPos format 2 subtables

- write-fonts/src/graph/splitting.rs
I had run into a probley friday afternoon that I didn't have time to dig into, and I didn't want to block on getting fontc working again. This fixes that.
It turns out were incrementing the current index only when the subtable had not been seen before, which meant we would never advance the index and would not visit all subtables.
> [write-fonts] Fix miscalculation of ppf2 subgraph size

- write-fonts/src/graph/splitting.rs
The harfbuzz implementation tracks the max size of a few tables since it needs to know this in order to allocated space for them, which is not necessary for us.
This also removes an outdated comment.
JMM
> [write-fonts] Some PairPos f.2 cleanup

- write-fonts/src/graph.rs
- write-fonts/src/graph/graphviz.rs
This adds the ability to set an env var ('FONTC_PRUNE_GRAPH') that tells write-fonts to prune a generated dotviz file to only include spaces that contain an overflow. This was very helpful for debugging our PairPos format 2 packing failures.
It also cleanups up our graphviz code to not use subgraphs, which weren't adding much if anything.
> [write-fonts] Graphviz improvements

- write-fonts/src/graph/splitting.rs
We were using inclusive ranges in format 1 but exclusive ranges in format 2; now we're using exclusive ranges in both.
> [write-fonts] Consistent PairPos split range semantics

- write-fonts/src/tables/gvar.rs
- write-fonts/src/tables/gvar/iup.rs
This fixes #568; when presented with deltas that include interpolatable values, we will generate both representations and then choose the more compact.
This is mostly straightforward, but there is some API to bikeshed, particularly around the `iup_delta_optimize` API.
Previously, this returned the deltas as `Vec<Option<Vec2>>`, with `None` values representing deltas that could be interpolated. This meant that we did not have access to these deltas, which are necessary in order for us to generate the non-IUP representation.
We have some options here. The simplest one would be to return the `GlyphDelta` type that we use when building gvar; the only concern here is that this type represents a point as`(i16, i16)`, where we are currently using `Vec2`. I personally think this is fine, since as …
> Only use IUP representation when more compact

- write-fonts/src/tables/cmap.rs
Fixes https://github.com/googlefonts/fontc/issues/451
This is intended to match fontmake/fonttools output.
If the input mappings contain any characters beyond the basic multilingual plane (> 0xFFFF) we also build two cmap12 subtables (one for Unicode platform, another identical one for WIndows platform, both pointing to the same format 12 subtable) which will be a superset of the BMP-only cmap4 subtables.
> Also build format 12 subtables in Cmap::from_mappings if any char > BMP

- write-fonts/src/tables/gvar/iup.rs
We were checking the axes independently, instead of checking the overall length of the vector.
> [write-fonts] iup: fixup vector distance calculation

- read-fonts/src/tables/variations.rs
This would only be encountered if the user manually tried to iterate packed points with a single 0x0 byte (signifying that there are points for all deltas) and did not also know how many points there were; but there's no reason not to be more careful here and at least stop iterating after u16::MAX items.
JMM
> [read-fonts] Fix possible crash in PackedPointNumbersIter

- skrifa/src/instance.rs
- skrifa/src/metrics.rs
Updates the `Metrics` and `GlyphMetrics` types to use an intermediate fixed point calculation for scaling that matches FreeType.
Fixes #590
> [skrifa] update metrics scaling to match FreeType

- write-fonts/src/tables/gvar.rs
in gvar you can optionally store on set of point numbers that are referenced by multiple regions for the same glyph; we were not previously using this very efficiently.
- based off of #616
- fixes #614
> Use 'shared point numbers' in gvar

- write-fonts/Cargo.toml
- write-fonts/src/tables/variations.rs
- write-fonts/src/tables/variations/ivs_builder.rs
and make it `pub` so that fontc can use it to build stuff like HVAR or COLR
Fixes https://github.com/googlefonts/fontations/issues/633
fea-rs var_store.rs module was copied from this commit:
https://github.com/cmyr/fea-rs/blob/497f51c66530f0b685646fae1db192502cdab1fe/fea-rs/src/compile/tables/var_store.rs
> Copy fea-rs VariationStoreBuilder to write-fonts

- write-fonts/src/tables/gpos.rs
- write-fonts/src/validate.rs
This significantly reduces indent drift when dealing with arrays; where previously you needed to indent 1) to start an array, 2) to manually loop and 3) to declare each item, we now have a single method that lets you pass in an iterator and a closure to be called on each item, and we handle the rest.
The diff shows that this is significantly less painful.
- closes #598
> [write-fonts] Improve validation API

- read-fonts/src/tables/gvar.rs
- write-fonts/src/tables/gvar.rs
This was something I skipped in my initial implementation, but should save us a few kb in the common case.
closes #615
> [write-fonts] Use short offsets in gvar where appropriate

- font-codegen/src/parsing.rs
- read-fonts/generated/generated_cpal.rs
- resources/codegen_inputs/cpal.rs
- write-fonts/generated/generated_cpal.rs
> Add strongly typed PaletteType flags to CPAL

- .github/workflows/rust.yml
There's a new clippy with new lints, but when we fix these lints we're crashing the compiler, so let's just turn it off until this gets resolved.
I've opened https://github.com/rust-lang/rust-clippy/issues/11619 upstream, and we can turn clippy back on when that gets resolved.
> [ci] Disable clippy

- read-fonts/src/tables/layout.rs
I wanted this for testing the table splitting in Mark2Base, and it's something we will want anyway.
This also fixes a little mixup in the signature of CoverageTable::iter; the elided lifetime here meant the compiler tied the iterator to the lifetime of the table object, whereas we really want to tie it to the lifetime of the underlying data.
JMM
> [read-fonts] Add 'get' method to coverage tables

- font-codegen/src/table.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gsub.rs
Aka the lookup and extension enums in gpos/gsub.
fixes #605
This also renames an internal method to match the name used elsewhere in codegen.
> [codegen] Add missing debug impls to generic groups

- write-fonts/src/tables/gvar/iup.rs
This patch fixes an issue with iup not resolving, although I do not fully understand the problem.
Basically: in comparing our implementation with the one in fonttools, there is clear divergence in some of the numerical code, where we are using Option<usize> in places where python is just using an integer. More importantly, we are using None where Python is using -1, but our comparison code is never checking if a value == None, whereas python *does* check if a value == -1, which means that python is setting the solution in cases where we are not.
This can be fixed by using `checked_sub` instead of `saturating_sub`, at least for this input.
It feels like this is probably fine, since the structure of this loop is such that the only negative value that is possible is -1 (at the start) but it …
> [iup] Fix mismatch in behaviour with fonttools

- write-fonts/src/tables/layout.rs
- write-fonts/src/tables/variations.rs
fontc needs to build a DeltaSetIndexMap for the HVAR table and would like to not bother with encoding details like entry format or whether to build Format0 or Format1 depending on the number of mappings, etc.
The VariationStoreBuilder returns, alongside the ItemVariationStore, a VariationIndexRemapping (which maps from TemporaryDeltaSetId (u32) to VariationIndex).
After this PR, fontc can simply collect all these VariationIndex values into a new DeltaSetIndexMap.
> [write-fonts] Allow to construct DeltaSetIndexMap from VariationIndex iterator

- read-fonts/src/tables/variations.rs
- write-fonts/src/tables/variations.rs
> [{read,write}-fonts] Allow DeltaSetIndexMap repeated trailing entries to be omitted

- write-fonts/src/tables/variations/ivs_builder.rs
With this patch we will use a consistent ordering to sort both encodings (which correspond to outer indices, in a VariationIndex table) and individual delta sets (which correspond to inner indices.)
This PR is more complicated than expected because we had to jump through some hoops in order to precisely match the sorting behaviour in fonttools.
With this, https://github.com/googlefonts/fontc/pull/490 now produces identical output for HVAR.
> [write-fonts] Match fonttools sorting in var store

- write-fonts/src/tables/variations/ivs_builder.rs
this test currently fails because the VarStore ends up with two identical [0] delta-sets instead of one. The builder is treating glyphs without any variations (add_deltas([]) and glyphs with explicitly defined 0 deltas (add_deltas([0]) as different, whereas it should treat them the same and have all point to the same no-op delta-set row.
> [ivs_builder] Fix all-zero delta sets not being de-duplicated

- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
```
$ cargo release changes
Changes for read-fonts from read-fonts-v0.12.0 to 0.13.0
05f97e0 address a few review comments
648241a [hvar] test advance_with_delta() doesn't error when gid >= map_count
82b93a5 [{read,write}-fonts] Allow DeltaSetIndexMap repeated trailing entries to be omitted
05d977f review feedback
d4c4505 add a test font and some bitmap loading tests
b4d8653 appease clippy
181a2b2 add EBDT formats
37bf82b [codegen] Add missing debug impls to generic groups
b3a6f07 [read-fonts] Add 'get' method to coverage tables
55b496d [rustdoc] Now with smarter link detection?
282d90b [clippy] Push the rock back up the hill
10c0184 read location info and the png data formats
7098368 some codegen hacks for SbitLineMetrics
5128be2 [WIP] CBLC parsing
Changes for write-fonts from …
```
> bump minor versions of read-fonts and write-fonts

- skrifa/src/scale/cff/scaler.rs
Make us match `FT_LOAD_NO_SCALE` for CFF outlines.
The original code returned the exact unscaled values from charstring evaluation but FT actually performs a fixed point multiply by 1/64 followed by truncation. We now do the same.
> [skrifa] cff: correct "scaling" for unscaled outlines 

- skrifa/src/scale/cff/hint.rs
Adds a simple type to abstract working with the bits in a hint mask.
Separating this to reduce the size of forthcoming hinting PRs.
> [skrifa] cff hint mask 

- font-codegen/src/fields.rs
- read-fonts/generated/generated_base.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/generated/generated_colr.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_test_records.rs
- resources/codegen_inputs/cmap.rs
- resources/codegen_inputs/colr.rs
- write-fonts/generated/generated_cmap.rs
> [codegen] Improve generated docs for typed offset getters

- skrifa/src/scale/cff/hint.rs
- skrifa/src/scale/cff/scaler.rs
Adds the HintMap type (CF2_HintMap in FreeType).
This is basically the core of the CFF hinting engine. It generates a list of sorted edges from the "blues" alignment zones and per-glyph stem hints which can be used to transform from character space (font units) to device space (grid fitted pixels).
I'd expect one or two more PRs to hook it all up, but this should be the worst of it. Almost there!
> [skrifa] cff hintmap

- read-fonts/src/scaler_test.rs
- skrifa/src/scale/cff/scaler.rs
- skrifa/src/scale/mod.rs
Our CFF scaler didn't match TrueType in that it was emitting a closing line instead of an actual close command. This makes them consistent and updates testing infra to accommodate the change.
> [skrifa] make cff emit an actual close command

- write-fonts/src/graph.rs
- write-fonts/src/graph/splitting.rs
- write-fonts/src/graph/splitting/mark2base.rs
- write-fonts/src/table_type.rs
- write-fonts/src/write.rs
This is an initial port of the table splitting impl for this subtable.
Unlike with PairPos, we don't have any real-world failure cases to test this on yet, but I think it's ready as a checkpoint.
This is based on #647, which should go in first. We also need to resolve clippy & rustdoc complains (#648)
> Table splitting for MarkBase

- skrifa/src/scale/cff/hint.rs
- skrifa/src/scale/cff/scaler.rs
This adds a new `HintingSink` type that pulls all the pieces together and feeds the hinting engine from charstring evaluation.
> [skrifa] cff hinting sink

- read-fonts/src/tables/gpos.rs
This should save the client from needing to interact with the enum in the general case.
Way back when I was first doing codegen I thought it might be nice to autogenerate getters for shared fields, but I never got around to it. Maybe it's worth thinking about again?
This was motivated by https://github.com/googlefonts/fontc/pull/492, which was adding a helper method to do the same thing.
> [read-fonts] Add convenience methods to AnchorTable

- read-fonts/src/tables/gpos.rs
- read-fonts/src/tests/test_gpos.rs
- write-fonts/src/tests/test_gpos.rs
These had been disabled way back when because we didn't support device tables. We do now, so we might as well make these work again.
JMM
> Enable old gpos spec tests

- font-codegen/src/table.rs
- read-fonts/generated/generated_base.rs
- read-fonts/generated/generated_bitmap.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/generated/generated_colr.rs
- read-fonts/generated/generated_gdef.rs
- read-fonts/generated/generated_glyf.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gsub.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_postscript.rs
- read-fonts/generated/generated_stat.rs
- read-fonts/generated/generated_test_formats.rs
- read-fonts/generated/generated_variations.rs
This derives `Clone` for format switching tables matching what we do for other records and tables.
Been meaning to fix this for a while and I've been coding around it, but I now foresee a future issue with variable color stops where this will be a real pain.
If it looks good, JMM.
> [codegen] derive Clone for format tables

- .github/workflows/rust.yml
- fauntlet/src/compare_glyphs.rs
- fauntlet/src/font/freetype.rs
- fauntlet/src/main.rs
- skrifa/src/scale/cff/hint.rs
- skrifa/src/scale/glyf/deltas.rs
- skrifa/src/scale/glyf/scaler.rs
- skrifa/src/scale/mod.rs
Found a workaround for the clippy crash so this re-enables it in CI and fixes issues that snuck in while it was disabled.
Fixes #651
> Re-enable clippy and fix lints

- skrifa/src/scale/glyf/glyph.rs
- skrifa/src/scale/glyf/mem.rs
- skrifa/src/scale/glyf/scaler.rs
- skrifa/src/scale/scaler.rs
1. Capture required hinting tables (fpgm, prep, cvt)
2. Make hinting specific memory calculations dependent on a parameter at memory request time rather than at _outline request time_
> [skrifa] changes in support of TT hinting

- font-types/LICENSE-APACHE
- font-types/LICENSE-MIT
- read-fonts/LICENSE-APACHE
- read-fonts/LICENSE-MIT
- skrifa/LICENSE-APACHE
- skrifa/LICENSE-MIT
- write-fonts/LICENSE-APACHE
- write-fonts/LICENSE-MIT
This will ensure that license files are packaged with the crate when it is published, which is required by a downstream user.
- ~didn't bother doing this for `write-fonts`, since I do not anticipate that being used by chrome in the near future.~
- ~QQ: should/can these just be symlinks? I'm not sure how that works with git and searching was inconclusive.~
- fixes #711 
So my first version of this was just copying files, and this version is symlinking. @anthrotype points out that symlinks may [cause some issues on windows](https://www.scivision.dev/git-windows-symlink/)? I'm not sure how much windows use we expect, and there is an obvious fix available, so my instinct is to just go with this.
> [chore] Symlink license files to crate roots

- write-fonts/src/tables/avar.rs
as proposed in https://github.com/googlefonts/fontc/pull/586 to be used when building avar table in fontc
JMM
> [write-fonts] add SegmentMaps::is_identity method

- write-fonts/src/graph.rs
- write-fonts/src/tables/layout.rs
Two little changes motivated by investigating https://github.com/googlefonts/fontc/issues/559.
- the first tweaks how we assign the 'table type' for extension subtables, for a better debugging experience,
- and the second modifies some assertions in our graph packing code
> Packing fixups

- read-fonts/generated/generated_stat.rs
- read-fonts/src/tables/stat.rs
- resources/codegen_inputs/stat.rs
- write-fonts/generated/generated_stat.rs
- write-fonts/src/tables/stat.rs
Fixes https://github.com/googlefonts/fontc/issues/582
OTS gives a warning that our offset_to_axis_values is != 0 even though the count of axis_values == 0. This fixes it.
NOTE: this is a breaking change in that read-fonts offset_to_axis_values now returns an `Option<Result<...>>` instead of just a Result.
> [read/write-fonts] make STAT offset_to_axis_values nullable

- write-fonts/src/tables/gpos.rs
- write-fonts/src/tables/variations/ivs_builder.rs
I'm currently reworking the fea-rs API so that it has native types for variable `ValueRecord`s and `AnchorTable`s, which will let actually create the various lookup builders for marks & kerning before feature generation.
Previously fea-rs used the native write-fonts types for value records, and it was responsible for remapping the temporary indices before generating the final lookups. Now it converts to the native types later in the process, and it makes sense to just have a mechanism for walking all the lookups and remapping everything there.
> Add trait for remapping temporary delta set index ids to their final values

- skrifa/src/color/instance.rs
- skrifa/src/color/mod.rs
- skrifa/src/lib.rs
- skrifa/src/provider.rs
- skrifa/src/scale/colr/mod.rs
- skrifa/src/scale/mod.rs
https://github.com/googlefonts/fontations/pull/697#discussion_r1394224889 requests moving the color instance code from the scale module to the top level "metadata section" of the crate. This PR contains a proposal for such an API that meshes well with the current design of `MetadataProvider`.
This depends on #697 but is pulled out here for separate discussion.
One key point is the method for bounding box computation. It'd be nice to avoid a hard dependency on anything in the `scale` module so the function here takes a closure for that purpose.
@drott thoughts? There's some overlap with your `ColorPainter` work but I think this provides a nice entry point for that.
> [skrifa] public color API

- read-fonts/generated/generated_mvar.rs
- resources/codegen_inputs/mvar.rs
- write-fonts/generated/generated_mvar.rs
we jumped the gun :)
see https://learn.microsoft.com/en-us/typography/opentype/spec/mvar#table-formats
JMM
> [mvar] offset to IVS is actually 16-bit, not 32-bit

- font-types/src/bbox.rs
- skrifa/src/color/mod.rs
Allowing scaling of bounding boxes, this comes in handily
for example when dealing with clip boxes and scaling them to font size.
> Scale Bounding boxes

- write-fonts/src/graph.rs
We were still using a hashset in one place where the iteration order impacted our packing behaviour. This replaces that usage with a BTreeSet.
- a prior attempt was #591
- downstream issue: https://github.com/googlefonts/fontc/issues/647
> [packing] Ensure graph isolation is deterministic

- resources/codegen_inputs/variations.rs
- write-fonts/generated/generated_variations.rs
- write-fonts/src/tables/mvar.rs
- write-fonts/src/tables/variations.rs
- write-fonts/src/tables/variations/ivs_builder.rs
This can not be correctly computed in the case where we have pruned all regions, so we should require it to be set explicitly and then do that in the builder.
Note: this is *a* fix, but may not be the best one. In particular we will still not know the correct axis count in the case where an `ItemVariationStore` is built without having any deltas added to it. I believe this would still cause a miscompilation. If this is a case that we want to allow (instead of just erroring at compile time, which we could consider?) then we will need to change this API to require the user to pass in an explicit `axis_count` when constructing the builder. I'm not sure how much of a hassle that would be in practice.
So basically: I need a second opinion on this. I'm now leaning towards requiring an explicit …
> [write-fonts] Do not autocompute VariationRegion::axis_count

- read-fonts/src/array.rs
Although a zero-length item is meaningless and indicates an error it is entirely possible for input data to be corrupted, and we should be more defensive about validating our inputs.
> [read-fonts] ComputedArray should check for zero

- write-fonts/src/tables/gpos.rs
- write-fonts/src/tables/gsub.rs
The equivalent types in read-fonts are public already.
JMM
> [write-fonts] Make gpos/gsub lookuplist types public

- write-fonts/src/tables/gvar.rs
Meant to reproduce the issue discussed at https://github.com/googlefonts/fontc/issues/647
If we are lucky enough the CI should fail, otherwise flip the coin again and you'll see...
> [write-fonts] reproduce and fix non deterministic gvar serialization

- skrifa/src/color/mod.rs
- skrifa/src/color/traversal.rs
Workaround for [1] and [2] - issues in the Chrome sandbox requiring access to random number generators.
[1] https://bugs.chromium.org/p/chromium/issues/detail?id=1516634
[2] https://bugs.chromium.org/p/chromium/issues/detail?id=1516641
> [Skrifa] Avoid initialization of HashSet with system random numbers

- read-fonts/src/tables/layout.rs
The conditional logic for selecting the appropriate class record was not quite right leading to incorrect class values being returned. This implements the lookup using a binary search and adds a test for correct behavior.
JMM
> [read-fonts] fix ClassDefFormat2::get()

- write-fonts/src/tables/gvar.rs
Reproduce and fix https://github.com/googlefonts/fontc/issues/647#issuecomment-1892034218
> [write-fonts/gvar] Fix shared tuples unstable order

- fauntlet/Cargo.toml
- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
```
Changes for read-fonts from read-fonts-v0.15.1 to 0.15.2
5ecb3e4 bump patch for read-fonts, write-fonts and skrifa
74bdb79 [read-fonts] fix ClassDefFormat2::get() (#755)
2cd4ac5 [clippy] Push the rock back up the hill
Changes for write-fonts from write-fonts-v0.21.1 to 0.21.2
5ecb3e4 bump patch for read-fonts, write-fonts and skrifa
884a132 [write-fonts] Use stable sort_by_key when computing gvar shared tuples
5476e99 [write-fonts/gvar] repro shared tuples unstable order
Changes for skrifa from skrifa-v0.15.2 to 0.15.3
5ecb3e4 bump patch for read-fonts, write-fonts and skrifa
```
> bump patch for read-fonts, write-fonts and skrifa

- font-codegen/src/fields.rs
- font-codegen/src/lib.rs
- font-codegen/src/parsing.rs
- font-codegen/src/table.rs
- read-fonts/generated/generated_base.rs
- read-fonts/generated/generated_bitmap.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/generated/generated_colr.rs
- read-fonts/generated/generated_gdef.rs
- read-fonts/generated/generated_glyf.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gsub.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_postscript.rs
- read-fonts/generated/generated_stat.rs
- read-fonts/generated/generated_test_formats.rs
- read-fonts/generated/generated_variations.rs
- read-fonts/src/tables/glyf.rs
- read-fonts/src/tables/gpos.rs
This is for tables that have multiple formats, where all the formats have an identically named method; we will now generate a wrapper method on the enum itself that forwards to the inner methods.
In this patch this is only implemented for raw fields, and we do not generate the typed offset getters. This is quite a bit more complicated, and we can look into that as followup.
-----
This ended up producing less code than I had expected, and most of that code is just exposing the `format` field. The two main 'real' cases are the bbox on glyphs and the coords on anchor tables, both of which we had previously hand-written implementations for.
The main thing that we are missing here (pending support for offset getters) is resolving coverage tables on multi-format layout subtables.
progress on …
> [codegen] Add wrappers on enums for shared methods

- read-fonts/src/tables/glyf.rs
At some point I changed the off curve cubic flag from 0x2 to 0x8 to match the proposed cubic glyf spec and this happened to overlap with one of the IUP touched flags which leads to.. bad things. This makes the flags distinct and adds a test to prevent me from repeating the mistake in the future.
> [read-fonts] fix overlapping point flags

- write-fonts/src/tables/glyf.rs
- write-fonts/src/tables/glyf/glyf_loca_builder.rs
- write-fonts/src/tables/glyf/simple.rs
This is a cleaner way of representing the idea of a glyph with no outlines, but which should still be added to loca.
I played around with also adding this in read-fonts, but it doesn't really play well with codegen or parsing, there, because we expect a format enum to have a table for each variant, and in the empty case we have no data from which to parse a table.
- closes  #561
- this may require some minor changes in fontc, when it lands
JMM
> [write-fonts] Add Glyph::Empty

- font-codegen/src/table.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gsub.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/src/tables/gpos.rs
- read-fonts/src/tables/gsub.rs
- read-fonts/src/tables/layout.rs
- write-fonts/src/graph/splitting/mark2base.rs
- write-fonts/src/graph/splitting/pairpos.rs
This adds a new convenience API on top of the `PositionLookup` and `SubstitutionLookup` types, which obviates (in the common case) the need to dig into these enums in order to access their contents. In particular, it provides a uniform interface for accessing lookup subtables, regardless of whether or not the lookup in question is behind an extension table.
The main idea here is that the level lookup types now have a `subtables` method, which returns an enum, with a variant for each non-extension lookup type; this enum provides access to an array-like object that allows access and iteration of the underlying subtables.
In practice, this makes working with lookups *significantly* easier; for instance after updating `layout-normalizer` to use this API, I was able to replace about ~100 lines …
> Improved Lookup API

- skrifa/src/instance.rs
- skrifa/src/outline/cff/hint.rs
- skrifa/src/outline/cff/mod.rs
- skrifa/src/outline/embedded_hinting.rs
- skrifa/src/outline/glyf/mod.rs
- skrifa/src/outline/mod.rs
- skrifa/src/scale.rs
The `Size::new(ppem: f32)` constructor interpreted a ppem of 0.0 as a request for no scaling which might be surprising behavior for users. This changes the internal representation of size to hold an `Option` so that a ppem of 0.0 works as expected.
Fixes #627
> [skrifa] support Size::new(0)

- skrifa/src/lib.rs
- skrifa/src/outline/mod.rs
Adds a new example to the outline module and fixes the broken doc link at the crate root.
I have a local branch with a more ambitious overhaul of the skrifa docs but figured I'd push this now to fix our brokenness while I iterate on that one.
> [skrifa] restore outline example

- skrifa/src/outline/glyf/hint/code_state/mod.rs
- skrifa/src/outline/glyf/hint/engine/arith.rs
- skrifa/src/outline/glyf/hint/engine/graphics_state.rs
- skrifa/src/outline/glyf/hint/engine/logical.rs
- skrifa/src/outline/glyf/hint/engine/mod.rs
- skrifa/src/outline/glyf/hint/engine/stack.rs
- skrifa/src/outline/glyf/hint/graphics_state/mod.rs
Add implementations for the "managing the graphics state" group of TrueType instructions (https://learn.microsoft.com/en-us/typography/opentype/spec/tt_instructions#managing-the-graphics-state).
> [skrifa] tthint: managing the graphics state

- fauntlet/Cargo.toml
- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- skrifa/src/outline/mod.rs
- write-fonts/Cargo.toml
Also fixes a one letter typo in skrifa docs.
> [chore] Bump read/skrifa patch version

- skrifa/src/outline/glyf/hint/definition.rs
- skrifa/src/outline/glyf/hint/engine/graphics_state.rs
- skrifa/src/outline/glyf/hint/engine/mod.rs
- skrifa/src/outline/glyf/hint/error.rs
- skrifa/src/outline/glyf/hint/mod.rs
- skrifa/src/outline/glyf/hint/program.rs
Adds a new `Definition` type that is used to represent function and instruction definitions. Also includes a `DefinitionMap` type that is used to allocate and retrieve these.
This handles the case where `function_number >= max_function_defs` avoiding the question as to whether this is necessary. Well behaved fonts will hit the fast path and broken ones will fall back to a linear search.
There's a bit of churn around the `code_state` module. This was removed because it was meant to contain the decoder logic which was moved to `read-fonts`.
> [skrifa] tthint: fdef/idef storage

- skrifa/src/outline/glyf/hint/cow_slice.rs
- skrifa/src/outline/glyf/hint/cvt.rs
- skrifa/src/outline/glyf/hint/engine/cvt.rs
- skrifa/src/outline/glyf/hint/engine/mod.rs
- skrifa/src/outline/glyf/hint/engine/storage.rs
- skrifa/src/outline/glyf/hint/error.rs
- skrifa/src/outline/glyf/hint/mod.rs
- skrifa/src/outline/glyf/hint/storage.rs
Implements both "managing the control value table" (https://learn.microsoft.com/en-us/typography/opentype/spec/tt_instructions#managing-the-control-value-table) and "managing the storage area" (https://learn.microsoft.com/en-us/typography/opentype/spec/tt_instructions#managing-the-storage-area) sets of instructions.
Supports copy-on-write for these buffers to address the FT issue fixed in this MR: https://gitlab.freedesktop.org/freetype/freetype/-/merge_requests/23
Also of note is the "pedantic" flag that just ignores OOB accesses when disabled. Unfortunately, this is necessary to match FT with some fonts :(
> [skrifa] tthint: cvt and storage area

- font-test-data/Cargo.toml
This is very helpful when importing fontations into internal repositories. If it isn't published I have to either eschew the normal tools or do things like regex transformation to delete the tests.
IMHO publishing this crate is the least bad option.
JMM if happy.
> Make font-test-data publish

- skrifa/src/outline/glyf/hint/engine/data.rs
- skrifa/src/outline/glyf/hint/engine/definition.rs
- skrifa/src/outline/glyf/hint/engine/dispatch.rs
- skrifa/src/outline/glyf/hint/engine/mod.rs
- skrifa/src/outline/glyf/hint/engine/outline.rs
- skrifa/src/outline/glyf/hint/graphics_state/mod.rs
Implements some of the simpler outline instructions that deal with point flags and also a couple from the "reading and writing data" group.
Includes a small change to the definition code: move the remap of InvalidDefinition->UnhandledOpcode error to actual definition lookup.
> [skrifa] tthint: low hanging fruit

- skrifa/src/outline/glyf/hint/cvt.rs
- skrifa/src/outline/glyf/hint/engine/cvt.rs
- skrifa/src/outline/glyf/hint/engine/data.rs
- skrifa/src/outline/glyf/hint/engine/graphics_state.rs
- skrifa/src/outline/glyf/hint/engine/logical.rs
- skrifa/src/outline/glyf/hint/engine/mod.rs
- skrifa/src/outline/glyf/hint/engine/outline.rs
- skrifa/src/outline/glyf/hint/graphics_state/projection.rs
- skrifa/src/outline/glyf/hint/graphics_state/round.rs
- skrifa/src/outline/glyf/hint/graphics_state/zone.rs
- skrifa/src/outline/glyf/hint/value_stack.rs
This changes the `points` and `original` arrays in `Zone` to have an element type of `Point<F26Dot6>` as that is the type used in the outline scaler. The intention is to avoid a bit of unsafe code that was coming in a later PR and just better match the spec in general. Decided to do this now to avoid more pain later.
Lots of churn for the modified types but no functional changes.
> [skrifa] tthint: embrace the 26.6

- font-codegen/src/record.rs
- read-fonts/generated/font.rs
- read-fonts/generated/generated_avar.rs
- read-fonts/generated/generated_base.rs
- read-fonts/generated/generated_bitmap.rs
- read-fonts/generated/generated_cmap.rs
- read-fonts/generated/generated_colr.rs
- read-fonts/generated/generated_cpal.rs
- read-fonts/generated/generated_fvar.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_hmtx.rs
- read-fonts/generated/generated_layout.rs
- read-fonts/generated/generated_mvar.rs
- read-fonts/generated/generated_name.rs
- read-fonts/generated/generated_postscript.rs
- read-fonts/generated/generated_stat.rs
- read-fonts/generated/generated_test_enum.rs
- read-fonts/generated/generated_test_offsets_arrays.rs
- read-fonts/generated/generated_test_records.rs
- read-fonts/generated/generated_variations.rs
- read-fonts/src/tables/avar.rs
- read-fonts/src/tables/bitmap.rs
- skrifa/src/variation.rs
That is, if a record has a fixed size we will derive the Copy trait. This will be necessary if we want to use bytemuck, and should let us simplify some other things.
- See https://github.com/googlefonts/fontations/issues/659 for previous discussion
> [codegen] Derive Copy for simple records

- skrifa/src/outline/glyf/hint/engine/dispatch.rs
- skrifa/src/outline/glyf/hint/engine/graphics_state.rs
- skrifa/src/outline/glyf/hint/engine/outline.rs
- skrifa/src/outline/glyf/hint/graphics_state/mod.rs
Finishes up the "managing outlines" instruction group. Adds implementations for 70 opcodes.
Also changes a few other graphics state types to `F26Dot6`.
Instructions added to #803
> [skrifa] tthint: finish outline instructions

- skrifa/src/color/mod.rs
- skrifa/src/color/traversal.rs
This reverts commit eef6a26640ace05d48c4e2150e303e5c6ac32201.
See details in [1] and [2]. Rust upstream landed a change switching to a different, sandbox-compatible call for PRNG, except on Windows
7. Windows 7 is no longer supported by Chromium. Chromium is our only known sandboxed environment where this call would fail. Remove the workaround.
[1] https://issues.chromium.org/40277768
[2] https://github.com/rust-lang/rust/commit/08caefbb103d1809113172d16eaf8f66c2edc2f1
> Revert "[Skrifa] Avoid initialization of HashSet with system random numbers (#751)

- read-fonts/src/tables/glyf.rs
I found the original code, directly ported from FreeType, a bit hard to follow and attempted to break it into smaller more tractable parts. Meant to make #818, which will rebase on top, simpler.
> Attempt to simplify glyf to_path

- read-fonts/src/tables/lookupflag.rs
This was annoying to use from fontc, and these two bits of functionality should make that cleaner.
> [read-fonts] Add consts & bitor impls to LookupFlag

- skrifa/src/outline/embedded_hinting.rs
- skrifa/src/outline/error.rs
- skrifa/src/outline/glyf/hint/engine/definition.rs
- skrifa/src/outline/glyf/hint/engine/dispatch.rs
- skrifa/src/outline/glyf/hint/engine/graphics_state.rs
- skrifa/src/outline/glyf/hint/engine/mod.rs
- skrifa/src/outline/glyf/hint/engine/outline.rs
- skrifa/src/outline/glyf/hint/graphics_state/mod.rs
- skrifa/src/outline/glyf/hint/graphics_state/zone.rs
- skrifa/src/outline/glyf/hint/instance.rs
- skrifa/src/outline/glyf/hint/mod.rs
- skrifa/src/outline/glyf/mod.rs
- skrifa/src/outline/mod.rs
This wires up the TrueType hinting code in a working state that matches FreeType for all of Noto and Google Fonts collections with the following exceptions:
1. Some fonts with buggy bytecode
2. Fonts with control value programs that are not idempotent over multiple runs (these are newish Win11 fonts)
3. Variable fonts with a cvar table (https://github.com/googlefonts/fontations/issues/831)
> [skrifa] tthint working checkpoint 

- skrifa/src/color/mod.rs
- skrifa/src/color/traversal.rs
Adds a maximum recursion depth for COLRv1 paint graphs. The limit chosen is 64 which matches the one used in HarfBuzz.
This makes skrifa more robust to potential stack overflow attacks and will enable no_std support without taking a hashbrown dependency for the visited set.
> [skrifa] color: add traversal depth limit

- write-fonts/src/tables/cmap.rs
Step one of https://github.com/googlefonts/fontc/issues/457
This checks for collisions as part of sorting, avoiding another walk of the mappings.
As this is a breaking change, is there a changelog I should update or a version number I should bump as part of this?
> Make Cmap::from_mappings fallable.

- font-types/src/fixed.rs
- read-fonts/src/tables/avar.rs
- read-fonts/src/tables/postscript/dict.rs
- skrifa/src/outline/cff/hint.rs
We had two implementations for float to fixed conversion based on whether std was available and the no_std implementation had a very subtle rounding bug (adding -0.5 for negative values but 0.0 for positive ones) causing some tests to fail.
This fixes the bug, restores the original tests and adds a new one to check rounding behavior in font-types.
> [font-types] float to fixed point rounding

- font-codegen/Cargo.toml
- font-types/Cargo.toml
- font-types/README.md
- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- read-fonts/README.md
- skrifa/README.md
- write-fonts/Cargo.toml
There is now some unsafe in font-types, which lets us remove unsafe in crates with more churn.
> Fix font-types docs, and bump patch version

- skrifa/src/outline/glyf/hint/engine/data.rs
- skrifa/src/outline/glyf/hint/engine/misc.rs
- skrifa/src/outline/glyf/hint/engine/mod.rs
Working toward #803
Covers GETINFO, GETVARIATION, GETDATA, GC, SCFS and MD
> [skrifa] tthint tests batch 1

- read-fonts/src/tables/layout.rs
- read-fonts/src/tables/variations.rs
This is a tiny quality-of-life improvement, since this conversion is necessary in order to get the variation data out of the data store.
JMM
> [read-fonts] impl From<VariationIdx> for DeltaSetIdx

- font-codegen/src/parsing.rs
- read-fonts/generated/generated_variations.rs
- read-fonts/src/tables/variations.rs
- resources/codegen_inputs/variations.rs
We were previously just taking all remaining data here, but we have enough information to compute the expected length exactly. This will let us better handle the case where data is missing.
- closes #857
> [read-fonts] Properly compute length of delta sets

- read-fonts/src/font_data.rs
- read-fonts/src/tables/value_record.rs
- write-fonts/src/tables/value_record.rs
ValueRecords have an explicit format, which is generally stored once in their parent table. In the case of records with device or variation tables, we need to know the format in order to write them correctly, since it's possible for these fields to be legitimately null, and we cannot distinguish between a record which where a field is None because it is not included versus when it is intended to be null.
Previously, we would use the format when reading the table but would then discard it. This led to a bug where we would not know the correct format when we went to write the table back.
With this patch, we hold onto the format after reading, and pass it to write-fonts if we convert to write-fonts types. This ensures that we roundtrip tables correctly in this case.
closes #858
> Preserve format of value records after reading

- fauntlet/src/font/skrifa.rs
- skrifa/src/outline/embedded_hinting.rs
- skrifa/src/outline/glyf/hint/cow_slice.rs
- skrifa/src/outline/glyf/hint/cvt.rs
- skrifa/src/outline/glyf/hint/engine/data.rs
- skrifa/src/outline/glyf/hint/engine/dispatch.rs
- skrifa/src/outline/glyf/hint/engine/mod.rs
- skrifa/src/outline/glyf/hint/engine/outline.rs
- skrifa/src/outline/glyf/hint/error.rs
- skrifa/src/outline/glyf/hint/instance.rs
- skrifa/src/outline/glyf/hint/value_stack.rs
Propagate the `is_pedantic` flag to a few places and reduce the strictness in various parts of the hinter based on that flag.
With these changes we match FT hinting for all of Google Fonts and Noto.
> [skrifa] reduce pedantry

- README.md
Split out from https://github.com/googlefonts/fontc/pull/746#pullrequestreview-1950256804
> Add depgraph showing relationships among the crates

- skrifa/src/outline/embedded_hinting.rs
- skrifa/src/outline/glyf/hint/instance.rs
- skrifa/src/outline/glyf/mod.rs
This fixes a weird edge case where the user requests a strong hinting mode (FT_LOAD_TARGET_MONO) but no instructions are present in a simple glyph. FreeType still rounds the phantom points in this case but we weren't doing so causing some glyphs to be offset a tiny bit in the x direction.
With this fix we now have 100% matching fauntlet runs for all of Google Fonts and Noto with all four hinting modes.
> [skrifa] tthint: rounding phantom points

- Cargo.toml
- font-types/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
Switch bytemuck version from `=1.31.1` to `1.31.1`. Also moves bytemuck to a workspace dependency to make it easier to update the version in the future.
> Unlock bytemuck version

- fauntlet/src/font/skrifa.rs
- skrifa/README.md
- skrifa/src/outline/hint.rs
- skrifa/src/outline/mod.rs
Just some housekeeping:
* Remove gratuitous `Embedded` prefix from the `HintingInstance` type
* Update glyph format section of the readme to reflect our current state
JMM
> [skrifa] tidy up before release

- fauntlet/Cargo.toml
- font-codegen/Cargo.toml
- font-types/Cargo.toml
- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
* patch update for font-types just to capture changed bytemuck dependency version
* minor for read-fonts and skrifa due to breaking change in CBLC fix
> bump types/read/skrifa for release

- read-fonts/src/tables/hmtx.rs
- read-fonts/src/tables/vmtx.rs
- skrifa/src/outline/glyf/mod.rs
Adds `advance()` and `side_bearing()` methods to `Hmtx`/`Vmtx`.
Feels like I've hand written this code often enough that it's now time to put it in its proper place.
JMM
> [read-fonts] add helpers to hmtx/vmtx

- fauntlet/Cargo.toml
- font-codegen/Cargo.toml
- font-types/Cargo.toml
- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
To release #880 so I can use it in https://github.com/googlefonts/sleipnir
> Bump font-types, read-fonts, skrifa patch versions

- read-fonts/src/tables/cmap.rs
The cmap4 subtable iterator would give up when encountering an out of bounds range offset. The equivalent HB code continues to the next character in this case so now we do the same.
Should fix #897
> [read-fonts] cmap4 iterator fix

- fauntlet/Cargo.toml
- font-codegen/Cargo.toml
- font-test-data/Cargo.toml
- font-types/Cargo.toml
- int-set/Cargo.toml
- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
* font-types as a useful GlyphId::new from u32
* Skrifa COLRv1 fix (#911)
* read-fonts cmap4 iterator fix (#899)
* write-fonts release while I am at it
* font-test-data for test for #911
> Bump for release

- Cargo.toml
- fuzz/Cargo.toml
- fuzz/README.md
- fuzz/fuzz_targets/fuzz_skrifa.rs
First step toward #420. Fuzzer is currently nop. Meant to enable oss-fuzz setup and establish a pattern we can use to add additional fuzzers for subsetting, etc.
For context, first swing at oss-fuzz rigging in https://github.com/google/oss-fuzz/pull/12011.
JMM
> Outline of a Skrifa fuzzer

- int-set/Cargo.toml
- int-set/benches/int_set_benchmark.rs
These benchmark functions are setup up to mirror the ones we have in harfbuzz for hb-set.
> [IntSet] Add benchmark suite for int set.

- font-types/Cargo.toml
- font-types/src/lib.rs
- font-types/src/tag.rs
- read-fonts/Cargo.toml
This is not enabled by default, but is turned on by read-fonts when read-fonts' 'std' feature is enabled.
The main thing that enabling 'std' does now is provide an impl of std::error::Error for the InvalidTag error type.
> Add back 'std' feature for font-types

- write-fonts/src/tables/gvar.rs
this ensures that we (e.g. fontc) can make valid empty gvar tables where the axis_count matches the expected (fvar's) axis_count as per OT spec. 
Will eventually fix https://github.com/googlefonts/fontc/issues/815 once fontc is updated to use the new API.
This is a breaking changes which warrants minor write-fonts version bump.
> [write-fonts/gvar] add axis_count param to Gvar::new

- write-fonts/src/offsets.rs
- write-fonts/src/validate.rs
lest recursive data structures like COLR Paint (not yet generating a write-fonts impl) or Conditions in #930 get upset about infinite recursion to get size.
```
// This is OK, presumably because we don't generate compile (write-fonts) for colr
format u8 Paint {
Glyph(PaintGlyph),
}
table PaintGlyph {
paint_offset: Offset24<Paint>,
}
// This is NOT OK; reading is fine but writing fails
// error[E0072]: recursive types `tables::layout::Condition` and `ConditionFormat5` have infinite size
format u16 Condition {
Format5Negate(ConditionFormat5),
}
table ConditionFormat5 {
condition_offset: Offset24<Condition>,
}
```
Fix suggested by @dfrg , errors all by me. 
Meant to unblock https://github.com/googlefonts/fontations/pull/930.
> Box write-fonts offset markers

- read-fonts/generated/generated_varc.rs
- read-fonts/src/tables/varc.rs
- resources/codegen_inputs/varc.rs
https://github.com/fonttools/fonttools/blob/5e6b12d12fa08abafbeb7570f47707fbedf69a45/Lib/fontTools/ttLib/tables/otData.py#L3471-L3473 says these can be NULL. JMM.
> Add nullable annotations on VARC

- read-fonts/src/tables/cvar.rs
- read-fonts/src/tables/gvar.rs
- read-fonts/src/tables/variations.rs
- write-fonts/src/tables/gvar.rs
- write-fonts/src/tables/variations.rs
https://github.com/harfbuzz/boring-expansion-spec/blob/main/VARC.md#tuplevalues makes the previously invalid combination of DELTAS_ARE_ZERO and DELTAS_ARE_WORDS mean the value is an i32.
> Add support for 4 byte deltas

- read-fonts/src/tables/lookupflag.rs
now that we have a `contains` method (or will as of #938) and the `BitOr` and `BitOrAssign` impls for this type, these methods are redundant and unnecessarily verbose.
> [read] Remove methods from LookupFlag

- read-fonts/src/tables/cmap.rs
- skrifa/src/charmap.rs
As discovered by fuzzing.
ref https://oss-fuzz.com/testcase-detail/5141969742397440 and  https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69547
First commit contains the failing test.
> Fix integer overflow in Cmap12::group()

- font-codegen/src/parsing.rs
- read-fonts/generated/generated_varc.rs
- read-fonts/src/tables/varc.rs
- resources/codegen_inputs/varc.rs
Read the fields of the MultiItemVarStore. This gives us raw and fairly unfriendly access to VARC and hopefully positions us to start thinking providing friendlier access, such as by loading paths in Skrifa.
> Read the fields of the multitem variation store

- read-fonts/src/tables/cmap.rs
- skrifa/src/charmap.rs
Limits iteration to the range of valid Unicode characters. Also ensures that we don't waste time iterating over the overlapping portions of subsequent ranges. This guarantees that we'll only ever loop a maximum of `char::MAX` times.
Addresses fuzzer timeout in https://oss-fuzz.com/testcase-detail/4628971063934976 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69540
> [read-fonts] limit iteration of cmap12

- font-types/src/lib.rs
- read-fonts/src/lib.rs
The `Zycon.ttf` test font at https://github.com/unicode-org/text-rendering-tests/tree/main/fonts uses this.
JMM
> Support 'true' SFNT version

- font-codegen/src/fields.rs
- font-codegen/src/record.rs
- read-fonts/generated/generated_fvar.rs
- read-fonts/generated/generated_gpos.rs
- read-fonts/generated/generated_gvar.rs
- read-fonts/generated/generated_test_records.rs
- read-fonts/generated/generated_variations.rs
- read-fonts/src/array.rs
- read-fonts/src/font_data.rs
- read-fonts/src/read.rs
- read-fonts/src/tables/gvar.rs
- read-fonts/src/tables/instance_record.rs
- read-fonts/src/tables/value_record.rs
This will ensure we do not panic on overflow when handling pathological inputs.
> [read] Make ComputeSize fallible

- read-fonts/src/array.rs
- read-fonts/src/font_data.rs
- read-fonts/src/read.rs
based on #966.
This enables the `clippy::arithmetic_side_effects` lint in the `read`, `font_data` and `array` modules, which are the most obvious places in read-fonts where overflow could occur, and it reworks all arithmetic in those modules to be checked.
This collides a bit with #960, but I think this is a reasonably clean and unobtrusive way to ensure that we're handling arithmetic edge cases in these files.
@drott does this work for you?
> [read] Remove & deny overflow in key modules

- README.md
A small addition that might be useful.
JMM
> [docs] Add link to cargo-fuzz in README

- fuzz/Cargo.toml
- fuzz/fuzz_targets/fuzz_skrifa_outline.rs
- read-fonts/src/array.rs
- read-fonts/src/font_data.rs
- read-fonts/src/read.rs
The `data` provided to the fuzz target is likely to look like a font. If some fool cut the front off it would become unlikely to do so. I suspect this is why fuzzing outlines has near zero coverage:
https://storage.googleapis.com/oss-fuzz-coverage/fontations/reports/20240625/linux/src/fontations/skrifa/src/outline/report.html.
What if instead we try a crossproduct of likely and random options against the fuzzer provided data?
Contributes to #420.
JMM if happy
> Try to play nicer with the seed corpus

- read-fonts/src/tables/sbix.rs
Add test case from crbug.com/347835680 which triggered overflows in font data reading, which are fixed after #966.
Test for #959. 
Test fails only on 32 bit, for example building and testing with: `--target=i686-unknown-linux-gnu`:
`cargo test --target=i686-unknown-linux-gnu "sbix_strikes_count_overflow"`
> [read-fonts] Add test case for SBIX overflow

- fuzz/fuzz_targets/helpers.rs
Just as predicted in https://github.com/googlefonts/fontations/pull/973#discussion_r1655433789 and reported in https://oss-fuzz.com/testcase-detail/6213391169945600
Part of #420
> Don't generate an absurd # of test cases when the fuzzer produces a large # of axes

- fuzz/fuzz_targets/fuzz_skrifa_charmap.rs
Ref https://storage.googleapis.com/oss-fuzz-coverage/fontations/reports/20240627/linux/src/fontations/skrifa/src/charmap.rs.html (from https://storage.googleapis.com/oss-fuzz-coverage/fontations/reports/20240627/linux/src/fontations/skrifa/src/report.html)
Contributes to #420. JMM.
> Adjust charmap fuzzer based on coverage

- int-set/src/input_bit_stream.rs
- int-set/src/lib.rs
- int-set/src/sparse_bit_set.rs
- Switch to reading and processing a node at a time instead of bit by bit.
- Using count trailing zeroes to find the '1' bits instead of checking all bits.
- Make branch factor during decode a compile time constant to allow the compiler to generate specialized versions for each of the four branch factors.
Yields a ~45% speedup versus the previous implementation.
> [int-set] Optimize the sparse set decoding operation.

- int-set/src/bitpage.rs
- int-set/src/bitset.rs
- int-set/src/lib.rs
Provides an iterator which iterates over ranges present in the set. Uses a specialized implementation where possible to quickly locate ranges in the underlying bit sets.
> [int-set] Add a iter_ranges() method to int set

- int-set/src/bitset.rs
- int-set/src/lib.rs
- int-set/src/sparse_bit_set.rs
- Make specialized sorted insert available and use it during the decoding operation.
- Results in speedups up to 60% for the decoding of large sets (32k elements).
> [int-set] Optimize set building time during sparse set decoding.

- skrifa/src/attribute.rs
I want to convert standard ratios to those used by fontconfig, so I would want to construct these constants:
``` fs
const WEIGHT_RATIO: f32 = FC_WEIGHT_EXTRABLACK as f32 / Weight::EXTRA_BLACK.value();
const STRETCH_RATIO: f32 = FC_WIDTH_ULTRAEXPANDED as f32 / Stretch::ULTRA_EXPANDED.ratio();
```
There doesn't seem to be any reason why these fns (value, ratio) can't be const. I also changed the new fns to const, for the same reason.
> fix: make Weight and Stretch getters const

- font-types/Cargo.toml
- write-fonts/Cargo.toml
Provide explicit features for optional dependencies rather than implicit ones. This is slated to be required in Rust 2024 Edition.
> Use explicit features for `serde`, `bytemuck`, `dot2`

- int-set/src/bitpage.rs
- int-set/src/bitset.rs
- int-set/src/lib.rs
iter_after() creates an iterator of values in the set that come after a given value.
intersects(range) checks if any values in the set intersect a range.
> [int-set] Add iter_after() and intersects(range) to IntSet

- fuzz/Cargo.toml
- fuzz/fuzz_targets/fuzz_int_set.rs
The fuzzer input is treated as a series of op codes which can invoke any of the int sets public api methods. The operations are performed on both and IntSet and BTreeSet in parallel and then method results and set contents are checked for equivalence.
> [int-set] Add an IntSet fuzzer that checks for correctness.

- .github/workflows/rust.yml
This helps to address a deprecation notice within the GitHub Actions UI.
> ci: Update to `actions/checkout` v4 from v3

- fauntlet/src/pen.rs
- skrifa/src/charmap.rs
- skrifa/src/color/mod.rs
- skrifa/src/metrics.rs
- write-fonts/src/graph/splitting.rs
This improves readability and is a new lint coming next week in Rust 1.80.
> Fix `clippy::doc_lazy_continuation` lints

- int-set/src/output_bit_stream.rs
- int-set/src/sparse_bit_set.rs
Given that we decode to a u32 int set, added two guards:
1. Enforce a maximum height per branch factor which will allow values up to u32 to be encoded, reject decoding sets with heights beyond this. Since the maximum value possible at each height in some cases still exceeds u32, the second guard is needed as well.
2. Do computations during decode using u64's and check for overflow before populating the output set. Reject decoding sets that exceed the u32 maximum.
> Update sparse bit set decode to avoid numerical overflows.

- fuzz/fuzz_targets/fuzz_sparse_bit_set_decode.rs
- int-set/src/sparse_bit_set.rs
It's very easy to construct a sparse bit set which contains all values in u32, which can be quite slow to decode. Add an alternate decoding method which can be given a maximum set size for callers who want to avoid long decoding times. Use the bounded version in the fuzzer.
> [int-set] Add a second version of sparse bit set decode with max set size.

- fuzz/Cargo.toml
- fuzz/fuzz_targets/fuzz_int_set.rs
- fuzz/fuzz_targets/int_set_op_processor.rs
- int-set/src/bitset.rs
- Add hash and equals ops
- Add all of the int types which domains are provided for.
> [int-set] Expand Int Set Fuzzer Coverage

- skrifa/src/lib.rs
In trying to use gid16 in harfruzz I discovered we don't re-export it. Perhaps we should?
> Re-export both glyph ids

- .github/workflows/rust.yml
- .typos.toml
False positives can be addressed by adding them into `.typos.toml`.
> ci: Add a check for common typos.

- .typos.toml
- read-fonts/src/tables/postscript/fd_select.rs
Followon to #1030, fix use of "datas" and promot "ot" to word status because it is a very common abbreviation of OpenType
JMM
> Tweak typos

- skrifa/src/outline/autohint/cycling.rs
- skrifa/src/outline/autohint/latin.rs
- skrifa/src/outline/autohint/mod.rs
- skrifa/src/outline/autohint/outline.rs
Implements the initial point analysis common to all writing systems:
1. Detect subsequent points within a heuristic threshold and mark them near
2. Compute dominant input/output directions for each point pair, skipping intermediate sequences of near points
3. Simplify, marking directionless points as weak
4. Identify remaining weak interpolation points
> [skrifa] autohint: point analysis

- fuzz/fuzz_targets/int_set_op_processor.rs
- read-fonts/src/collections/int_set/mod.rs
This is redundant, since it is always equal to `Self`.
> [int-set] Remove unnecessary generic param on Domain

- read-fonts/src/collections/int_set/mod.rs
This is a common way to initialize construct sets (particularly for testing), and is implemented for both HashSet and BTreeSet; having it here will make it easier to use IntSet as a drop-in replacement for those types.
> [int-set] Impl From<[T; N]> for IntSet<T>

- skrifa/src/outline/autohint/cycling.rs
- skrifa/src/outline/autohint/outline.rs
* Rework `IndexCycler` into just a `Contour` type that is now used in `Outline`.
* Add next/prev indices to `Point`.
> [skrifa] autohint outline cleanup

- .github/workflows/rust.yml
* Use a `no_std` target to be sure that nothing is linking with `std`.
* Use `cargo build` rather than `cargo check` to go all the way through the linking stage.
* Use `-p` rather than `--manifest-path` as it is shorter and should still work here.
Fixes #1006.
> ci: More complete check for `no_std` builds

- read-fonts/src/tables/fvar.rs
- skrifa/src/variation.rs
Moves coordinate conversion logic from skrifa to read-fonts to support this functionality in harfruzz.
> [read-fonts] Fvar::user_to_normalized()

- read-fonts/src/tables/gvar.rs
- skrifa/src/metrics.rs
Basically just moves our gvar phantom point delta computation from skrifa to read-fonts since we'll need this for glyph metrics in harfruzz.
> [read-fonts] gvar: phantom point deltas

- skrifa/src/outline/autohint/latin/blues.rs
- skrifa/src/outline/autohint/latin/metrics.rs
- skrifa/src/outline/autohint/latin/mod.rs
- skrifa/src/outline/autohint/metrics.rs
Computes unscaled (and then scaled) style-specific metrics for Latin-like hinting.
This basically ties all the previous work together then applies a scaling factor and adjusts and selects active blue zones.
> [skrifa] autohint: Latin metrics

- fuzz/fuzz_targets/fuzz_int_set.rs
- fuzz/fuzz_targets/fuzz_sparse_bit_set_encode.rs
- fuzz/fuzz_targets/int_set_op_processor.rs
- klippa/src/lib.rs
- read-fonts/src/collections/int_set/bitpage.rs
- read-fonts/src/collections/int_set/bitset.rs
- read-fonts/src/collections/int_set/mod.rs
- read-fonts/src/collections/int_set/sparse_bit_set.rs
A u32 containing intset can have up to u32::MAX + 1 elements in it which can overflow a usize when usize is a u32. Fixes #1057
> Change IntSet::len() to return u64 instead of usize.

- Cargo.toml
- fauntlet/Cargo.toml
- font-codegen/Cargo.toml
- fuzz/Cargo.toml
- klippa/Cargo.toml
- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
This eliminates having to specify the version for the library crates in each thing that depends upon them.
> Use workspace dependencies for libs in this repo.

- read-fonts/src/tables/postscript/index.rs
- skrifa/src/outline/base.rs
- skrifa/src/outline/cff/hint.rs
- skrifa/src/outline/cff/mod.rs
- skrifa/src/outline/common.rs
- skrifa/src/outline/glyf/hint/engine/mod.rs
- skrifa/src/outline/glyf/hint/instance.rs
- skrifa/src/outline/glyf/mod.rs
- skrifa/src/outline/mod.rs
- skrifa/src/patchmap.rs
- skrifa/src/provider.rs
Per IM, changes skrifa to use `FontRef` directly rather than `TableProvider`.
Extracts some shared functionality into a `BaseOutlines` type for outlines in preparation for more autohinting work but no real functional changes.
> [skrifa] FontRef instead of TableProvider

- skrifa/src/outline/autohint/instance.rs
- skrifa/src/outline/autohint/mod.rs
- skrifa/src/outline/autohint/style.rs
- skrifa/src/outline/mod.rs
Exposes the glyph style map as a public type and wrapped in an `Arc` to make it shareable among multiple autohinting instances.
> [skrifa] autohint: public GlyphStyles type

- write-fonts/src/tables/gdef.rs
Specifically this is required for the LigCaretList, because it is possible (and for fontc, *probable*) to have caret positions that include deltas.
> [write] impl RemapVariationIndices for Gdef

- read-fonts/src/collections/int_set/bitset.rs
- read-fonts/src/collections/int_set/mod.rs
For exclusive sets this avoids iterating over all of the individual members of the set which can be extremely large.
> [int-set] special case IntSet::cmp to compare ranges when comparing mixed inclusive/exclusive sets.

- font-codegen/src/table.rs
- read-fonts/generated/generated_test_conditions.rs
- read-fonts/src/codegen_test.rs
- read-fonts/src/lib.rs
- read-fonts/src/tests/test_helpers.rs
- resources/codegen_inputs/test_conditions.rs
- write-fonts/generated/generated_test_conditions.rs
- write-fonts/src/codegen_test.rs
This relaxes a constraint where previously non-conditional fields could not follow conditional ones, which will make codegen more expressive (and be particularly useful for the in-progress IFT work)
- closes #1093
> [codegen] non-conditional fields after conditionals

- fuzz/fuzz_targets/fuzz_int_set.rs
- fuzz/fuzz_targets/fuzz_sparse_bit_set_encode.rs
- fuzz/fuzz_targets/int_set_op_processor.rs
- read-fonts/src/collections/int_set/input_bit_stream.rs
- read-fonts/src/collections/int_set/sparse_bit_set.rs
Values beyond the max are ignored instead of causing the decoding to fail. This matches changes in the IFT specification handling of sparse bit set decoding (See: https://github.com/w3c/IFT/pull/203).
> Change sparse bit set decode to take a max value instead of max number of elements.

- read-fonts/src/tables/glyf.rs
- skrifa/src/outline/autohint/hint.rs
- skrifa/src/outline/autohint/latin/segments.rs
- skrifa/src/outline/autohint/outline.rs
- skrifa/src/outline/cff/mod.rs
- skrifa/src/outline/unscaled.rs
Adds support for converting the autohinter outline data to a path.
Additionally adds the const qualifier to some `PointFlags` methods and fixes an oversight in CFF where we weren't emitting a close path command for unhinted outlines (this was detected here because the autohinting conversion always emits close path).
> [skrifa] autohint outline to path

- font-test-data/Cargo.toml
- font-test-data/src/lib.rs
- read-fonts/src/tables/ift.rs
- read-fonts/src/tests/test_helpers.rs
- skrifa/src/patchmap.rs
This allows constructing test data which tests can then modify specific parts of the data via the tag names. Updates one of the IFT test data items to use BeBuffer.
> Extend BeBuffer to allow locations to be tagged.

- skrifa/src/outline/autohint/hint.rs
- skrifa/src/outline/autohint/latin/edges.rs
- skrifa/src/outline/autohint/latin/hint.rs
- skrifa/src/outline/autohint/latin/mod.rs
- skrifa/src/outline/autohint/metrics.rs
Updates latin outline hinting to return a structure describing positions of the left and right-most edges which will be used for advance width adjustment. Updates the outer hinting function test to check these.
Includes a bit of additional code shuffling in the edge computation to better match FT.
> [skrifa] autohint: latin edge metrics

- font-test-data/src/ift.rs
- read-fonts/generated/generated_ift.rs
- read-fonts/src/tables/ift.rs
- resources/codegen_inputs/ift.rs
- skrifa/src/patchmap.rs
- write-fonts/generated/generated_ift.rs
When a string data block is present then entry id deltas are instead interpretted as string lengths in order to assign string ids to entries (instead of the usual numeric ones).
See: https://w3c.github.io/IFT/Overview.html#mapping-entry-entryidstringlength
> [IFT] Add support for handling Format 2 entries with string IDs.

- otexplorer/Cargo.toml
- read-fonts/Cargo.toml
- read-fonts/src/traversal.rs
- write-fonts/Cargo.toml
This also adds a note to the docs of the 'traversal' module explaining that they are not really public API.
> Make traversal non-default feature

- skrifa/src/outline/autohint/axis.rs
- skrifa/src/outline/autohint/latin/edges.rs
- skrifa/src/outline/autohint/latin/hint.rs
- skrifa/src/outline/autohint/latin/metrics.rs
- skrifa/src/outline/autohint/latin/mod.rs
- skrifa/src/outline/autohint/latin/segments.rs
- skrifa/src/outline/autohint/latin/widths.rs
- skrifa/src/outline/autohint/style.rs
Adds the segment computation for CJK.
There's some dead code here that exists in FT but is never executed due to bugs. See #1129
Based on #1130 which should land first
> [skrifa] autohint: CJK segments

- read-fonts/src/collections/int_set/bitset.rs
- read-fonts/src/collections/int_set/input_bit_stream.rs
Current nightly Rust has a new warning about elided named lifetimes enabled by default:
https://doc.rust-lang.org/nightly/rustc/lints/listing/warn-by-default.html#elided-named-lifetimes
> Use `Self` to avoid new `elided_named_lifetime` warning.

- font-types/Cargo.toml
- font-types/src/lib.rs
- read-fonts/Cargo.toml
- read-fonts/src/lib.rs
- skrifa/Cargo.toml
- skrifa/src/lib.rs
- write-fonts/Cargo.toml
- write-fonts/src/lib.rs
This generates docs for all features in `font-types`, `skrifa`, and `write-fonts`. In `read-fonts`, only for `libm`, `serde`, and `std`.
> Generate docs for most features on docs.rs

- read-fonts/src/tables/fvar.rs
Fixes a slight oversight in the new avar2 code where we will panic if the given slice is not exactly the expected size which does not match our API guarantees according to the docs.
First commit contains a test that demonstrates the panic.
Also add link to issue for fixing 64 axis limit.
> [read-fonts] avar2 resolution might panic

- read-fonts/generated/generated_head.rs
- resources/codegen_inputs/head.rs
- write-fonts/generated/generated_head.rs
It's true that the OpenType spec doesn't contain a description for this field, but "See somewhere else" was an odd thing to see pop up in my IDE.
> Improve head.macStyle docs

- font-codegen/src/table.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/generated/generated_gsub.rs
Generate From<Lookup<_>> for PositionLookup/SubstitutionLookup.
This is a little ergonomics improvement, addressing a lingering frustration with these types.
> [codegen] From<Lookup<_>> for lookup enums

- skrifa/src/outline/glyf/mod.rs
- skrifa/src/outline/glyf/outline.rs
In `ScaledOutline::adjusted_advance_width()` prefer widths from `hdmx` over phantom points to better match FreeType.
> [skrifa] use hdmx table if available

- fauntlet/src/compare_glyphs.rs
- fauntlet/src/font/freetype.rs
- fauntlet/src/font/skrifa.rs
- read-fonts/src/tables/glyf.rs
- skrifa/src/outline/autohint/instance.rs
- skrifa/src/outline/autohint/outline.rs
- skrifa/src/outline/autohint/style.rs
- skrifa/src/outline/glyf/mod.rs
- skrifa/src/outline/hint.rs
- skrifa/src/outline/mod.rs
- skrifa/src/outline/path.rs
Reworks the TrueType->path conversion code to capture states explicitly to reduce branches along with some inlining and other code motion.
This gives a roughly 10% improvement based on measured fonts.
Example for Noto Sans Regular (all glyphs 100x):
| FreeType | skrifa (current) | skrifa (this PR) | skrifa (this PR + LTO) |
|-----------|-------------|--------------|--------------------|
| 308ms     | 337ms      |  295ms        | 213ms                  |
The significant difference when enabling LTO suggests that we might be missing some inlining opportunities across the `read-fonts`/`font-types` boundaries. Note that current skrifa + LTO is roughly the same as this PR without it.
> [skrifa] path conversion perf improvements

- font-types/src/raw.rs
- skrifa/src/outline/glyf/mod.rs
- skrifa/src/outline/hint.rs
- skrifa/src/outline/mod.rs
Follow up to #1171 for even faster outline loading:
* Some targeted inlining, specifically `<i8 as Scalar>::from_raw` was showing up in the profile. This is a big win
* Use a borrow of the largish `glyf::Outlines` type when constructing a scaler to save the copy.. removes some `_platform_memcpy`
* Add bucketed stack allocations to avoid zeroing excessive memory.. significantly reduces cost of `_platform_memset` in the profile
These changes reduce average time for loading all Noto Sans Regular glyphs from 295ms (previous PR) to 254ms (206ms with LTO). This is down from our starting point of 337ms.
> [skrifa] more scaler perf

- Cargo.toml
- font-types/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
Release FreeType advance diff fix and
two perf improvements in path retrieval.
> [chore] bump font-types/read-fonts/skrifa patch

- font-test-data/src/cmap.rs
- font-test-data/src/lib.rs
- read-fonts/src/tables/cmap.rs
#954 (the same for cmap12) has raw bytes which are presumably the minimized test repro (?)
The fuzzer repro for this is 137K so we use hand-crafted data to demonstrate the Cmap4Iter used to be happy to reprocess codepoints.
IMHO the floor for the next range should be `cur_range.end + 1` but this somehow breaks a klippa integrate test so I deferred that to https://github.com/googlefonts/fontations/issues/1166.
Fixes #1100
> Fix fuzzer bug with cmap4

- skrifa/src/outline/autohint/style.rs
Missing test for this noted in https://github.com/googlefonts/fontations/pull/1171#discussion_r1786735390
JMM
> [skrifa] test ASCII digit capture for autohint styles

- Cargo.toml
- skrifa/Cargo.toml
This is breaking because the `patchmap` module was moved to the new `incremental-font-transfer`crate.
> [chore] bump skrifa minor

- font-codegen/README.md
- font-codegen/src/parsing.rs
- font-test-data/src/ift.rs
- incremental-font-transfer/src/font_patch.rs
- read-fonts/generated/generated_ift.rs
- read-fonts/src/lib.rs
- read-fonts/src/tables/ift.rs
- resources/codegen_inputs/ift.rs
- write-fonts/generated/generated_ift.rs
Second patch format for IFT, see: https://w3c.github.io/IFT/Overview.html#glyph-keyed
> [IFT] Add code gen definitions for GlyphKeyed patches

- font-test-data/Cargo.toml
- font-test-data/src/ift.rs
- incremental-font-transfer/Cargo.toml
- incremental-font-transfer/src/font_patch.rs
- incremental-font-transfer/src/glyph_keyed.rs
- incremental-font-transfer/src/lib.rs
- incremental-font-transfer/src/patchmap.rs
- read-fonts/src/tables/ift.rs
https://w3c.github.io/IFT/Overview.html#glyph-keyed
Currently only supports glyf/loca modification and is missing functionality to mark applied patches in the IFT tables.
> [IFT] Add beginning implementation for Glyph Keyed patches

- read-fonts/src/tables/cmap.rs
A rust update changed binary search logic which is causing these tests to fail (likely because the table directory is not properly sorted in the fuzzing test cases).
This PR adds the ignore attribute to these tests so that we can push more urgent fixes without CI failures.
Filed #1194 to restore tests
> [read-fonts] ignore failing cmap 12 tests

- read-fonts/src/tables/postscript/stack.rs
- skrifa/src/outline/cff/hint.rs
Add targeted `wrapping_add` and `wrapping_sub` calls to avoid panics on arithmetic overflows for the specific case in #1193
> Avoid various overflows in CFF

- skrifa/src/color/mod.rs
Fixes abort caused by `todo!()` and caught by fuzzing.
ref
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71277 and https://oss-fuzz.com/testcase?key=5794538109599744
JMM if happy
> [skrifa] replace todo! with None for color bbox

- read-fonts/src/tables/postscript/dict.rs
Another overflow when computing the range for a private dict.
ref https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71746 and https://oss-fuzz.com/testcase?key=4591358306746368
First commit contains a failing test.
> [read-fonts] avoid overflow in private dict range

- skrifa/src/color/traversal.rs
Avoid a panic when a degenerate linear gradient occurs and an empty color line is passed.
Fixes #1205.
> [Skrifa] Fix panic in degenerate linear gradient drawing

- write-fonts/src/round.rs
this will come in handy for rounding master values before passing them on to VariationModel::deltas while keeping them as floats (without the need to temporarily cast them to integer types), https://github.com/googlefonts/fontc/issues/1043
JMM
> define OtRound for/to float types

- font-test-data/src/ift.rs
- incremental-font-transfer/src/font_patch.rs
- incremental-font-transfer/src/glyph_keyed.rs
- read-fonts/src/tables/ift.rs
- read-fonts/src/tables/loca.rs
Adds a variety of tests that cover error cases when parsing and applying glyph keyed patches.
> [IFT] Add tests for error cases in Glyph Keyed patching.

- skrifa/src/outline/autohint/latin/blues.rs
- skrifa/src/outline/autohint/latin/metrics.rs
- skrifa/src/outline/autohint/latin/widths.rs
- skrifa/src/outline/autohint/shape.rs
Some autohinter styles have associated features like `c2sc` (caps to small caps). When generating metrics for these styles, we want to compute widths and alignment zones on the result of applying the relevant GSUB feature to our "blue" and standard width strings.
This patch adds support for simple single substitution GSUB lookups and applies them when requested.
> [skrifa] autohinting: apply GSUB to styles with features

- Cargo.toml
- read-fonts/Cargo.toml
- write-fonts/Cargo.toml
```
$ cargo release changes
Changes for read-fonts from read-fonts-v0.23.0 to 0.23.1
7914440 [IFT] enforce loca offset sortedness in glyph keyed patching.
9bed00d [IFT] Add checks in glyph keyed patches.
f5e359d [read-fonts] helper methods for layout tables (#1208)
d52fd0c [read-fonts] avoid overflow in private dict range (#1203)
Changes for write-fonts from write-fonts-v0.29.0 to 0.30.0
002872e define OtRound for/to float types
aa417e7 [write] Fixup doctest
fa707c0 write-fonts: Fix `clippy::single_match` lint
1110a3f [IFT] Add codegen definitions for Glyph Keyed patches.
a9377e3 Mention trait in first example
b4bea97 Highlight to_owned_table more strongly
221c525 [IFT] Add a CompatibilityId type.
f535d81 [IFT] in font_patch.rs add public method comments.
a8ae76d Fix pluralization of …
```
> bump read-fonts to 0.23.1 and write-fonts to 0.30.0

- skrifa/src/outline/glyf/hint/engine/graphics.rs
Fuzzing caught a subtraction overflow when the provided selector value is 0. This simply moves the selector range check above the flag computation so we early out before the overflowing operation.
ref https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70426 and https://oss-fuzz.com/testcase?key=6243979511791616
> [skrifa] tthint: avoid overflow in INSTCTRL

- skrifa/src/outline/autohint/latin/blues.rs
Changes to signed arithmetic to match FreeType.
See #1218 for context
> [skrifa] autohint: avoid overflow in long blues

- .typos.toml
This would have caught 45d9e53 (PR #1225).
> typos: Check for `sftn` instead of `sfnt`

- write-fonts/src/font_builder.rs
- write-fonts/src/tables/cmap.rs
- write-fonts/src/util.rs
This is shared in a few places, so it makes sense to have a single implementation. 
Ran into this in the context of the `kern` table, which I'll PR shortly; this code is shared in a few places.
(CI is failing for other reasons, so let's hold off on this until that gets cleared up)
> [write] Add common util for computing searchRange

- resources/codegen_inputs/cmap.rs
- write-fonts/generated/generated_cmap.rs
- write-fonts/src/tables/cmap.rs
There are a bunch of computed fields on some of these subtables, so we should handle that in one place instead of asking the implementor to compute them.
> [write] Handle more cmap fields in codegen

- write-fonts/src/tables/cmap.rs
This produces significantly smaller cmap tables by combining segments where possible, and taking advantage of of the `offset_range_id` array to store glyphids directly where this is beneficial.
This fixes the issue where our cmap tables were often significantly larger than the ones produced by the python toolchain.
I believe there may be one further optimization possible here, which i am curious to explore but am holding back because I think the size savings are negligible: but I believe it is theoretically possible to reuse glyph ids in the `glyphIDArray`, if two segments have glyphs identical spacing patterns, due to the fact that the idDelta is still applied even if the glyphidarray is used.
> More efficient cmap compilation

- Cargo.toml
- font-types/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
It turns out the commit that said "typo fix" was fixing a typo in a piece of public API in our lowest crate, so everyone needs a minor bump?
> [chore] Bump more versions

- font-test-data/Cargo.toml
The 'categories' section is basically an enum, you can't just put whatever you want in there. See https://crates.io/category_slugs
> [chore] Fixup test data manifest

- font-test-data/src/ift.rs
- incremental-font-transfer/Cargo.toml
- incremental-font-transfer/src/font_patch.rs
- incremental-font-transfer/src/glyph_keyed.rs
- incremental-font-transfer/src/lib.rs
- incremental-font-transfer/src/patch_group.rs
- incremental-font-transfer/src/patchmap.rs
- incremental-font-transfer/src/table_keyed.rs
Adds a new patch_group module which generates a candidate set of URIs to be applied next based on the list of intersecting patches. The candidate URI group is structured to enforce compatibility constraints between patches. PatchGroup's can then be used to trigger the next iteration of patch application.
Example usage:
```
loop {
let g = PatchGroup::select_next_patches(font, &subset_definition).unwrap();
if !g.has_uris() {
break;
}
// g.uris() lists patches to be downloaded, 
// patch_data is populated with downloaded data.
let patch_data = ...;
font = g.apply_next_patches(&mut patch_data).unwrap();
}
```
> [IFT] major rework to the IFT API around patch intersection and application.

- read-fonts/src/tables/variations.rs
Determining the delta count and offset to the y-deltas requires processing the full stream, but we really only need to read the control byte for each run to do so.
This gives a roughly 30%(!) boost in loading outlines from variable TrueType fonts.
> [read-fonts] gvar: improve delta decoding perf

- fuzz/fuzz_targets/fuzz_ift_patch_group.rs
- shared-brotli-patch-decoder/Cargo.toml
- shared-brotli-patch-decoder/src/lib.rs
To make this effective the brotli decoder has been configured to be disabled during fuzzing. This is needed because the brotli decoder code is c++ based and the fuzzer isn't able to instrument and track coverage through it, which results in the fuzzer being extremely unlikely to generate valid brotli encoded data.
> [IFT] add patch application call to patch group fuzzer.

- font-codegen/src/fields.rs
- write-fonts/generated/generated_avar.rs
- write-fonts/generated/generated_base.rs
- write-fonts/generated/generated_cmap.rs
- write-fonts/generated/generated_font.rs
- write-fonts/generated/generated_gdef.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/generated/generated_gsub.rs
- write-fonts/generated/generated_gvar.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/generated/generated_name.rs
- write-fonts/generated/generated_postscript.rs
- write-fonts/generated/generated_sbix.rs
- write-fonts/generated/generated_stat.rs
- write-fonts/generated/generated_test_formats.rs
- write-fonts/generated/generated_test_offsets_arrays.rs
- write-fonts/generated/generated_test_records.rs
- write-fonts/generated/generated_variations.rs
- write-fonts/generated/generated_vorg.rs
- write-fonts/src/collections.rs
- write-fonts/src/lib.rs
- write-fonts/src/tables/cmap.rs
This fixes an issue where we were incorrectly truncating all computed lengths to u16, even if the resulting value is storedwould be stored as a u32.
We now keep computed values as usize and then generate a conversion for the appropriate type only at the callsite, instead of blindly converting to a u16 earlier on.
(this issue was pointed out in https://github.com/googlefonts/fontations/pull/1244#discussion_r1847439465; thanks @Hoolean!)
> [codegen] Better handling of computed lengths

- write-fonts/generated/generated_meta.rs
This somehow ended up broken on main after I merged the autohint reorg which amusingly didn't even touch that code.
This patch is just a rerun of codegen to fix the error.
JMM
> [write-fonts] update meta codegen

- resources/codegen_inputs/name.rs
- write-fonts/generated/generated_name.rs
- write-fonts/src/tables/name.rs
It is an invariant that entries in the name_records array are sorted, and to enforce this at the type level the initial design used a BTreeSet for these records.
This didn't fully help, though, because it was still possible to have a duplicate entry in the array (the same
platform/encoding/language/nameId, mapped to different strings) since the string itself is included in the Eq method of `NameRecord`.
This patch tries to be less cute: it is now the responsibility of the caller to make sure that their data is right, and we will verify this at validation time.
Ultimately this probably deserves a builder (there's one in fea-rs that should maybe get moved over here?)
cc @simoncozens; I recall you not enjoying the ergonomics of the `BTreeSet` approach, so here you go 💁
> [write] Use Vec instead of BTreeSet for name records

- write-fonts/src/tables/glyf.rs
- write-fonts/src/tables/glyf/simple.rs
This solves #1253 for me...
- **Rename and expose instructions**
- **Expose contours**
- **Allow construction of empty Glyph**
- **Recompute bounding box method**
- **Contour to Vec<ContourPoint> and back again**
> Allow manipulating the write_fonts::tables::glyf::Glyph structure

- font-test-data/src/ift.rs
- incremental-font-transfer/src/font_patch.rs
- incremental-font-transfer/src/glyph_keyed.rs
- incremental-font-transfer/src/patch_group.rs
- incremental-font-transfer/src/patchmap.rs
When multiple candidate invalidating patches match a target subset def the client must pick a specific one to proceed with. The specification provides specific criteria for making this selection: https://w3c.github.io/IFT/Overview.html#invalidating-patch-selection
This adds an implementation of a spec compliant selection criteria. We track the size of the intersections of the subset definition sets and then use those to make the selection.
> [IFT] Implement spec compliant selection order for invalidating patches

- write-fonts/src/tables/name.rs
This only stabalized in 1.82 and is causing us to fail in oss-fuzz, which isn't there yet.
JMM
> [write] Remove use of is_sorted

- read-fonts/Cargo.toml
- read-fonts/src/tables/glyf.rs
- skrifa/Cargo.toml
- skrifa/src/outline/mod.rs
- skrifa/src/outline/unscaled.rs
We don't want to ship experimental functionality in Chrome. Resolved per #1221 to mask out the bit and re-enable later. Also ignores two tests for this.
cc @drott
> [read-fonts] feature gate cubic glyf support

- write-fonts/src/tables/variations.rs
Specifically, this addresses one optimization we were missing, which is to combine a single byte-encodable item into the preceding word-encodable run if it is also followed by a word-encodeable run, since it lets us combine three runs into one.
- https://github.com/googlefonts/fontc/issues/1164
> [write] Improve efficiency of delta run encoding

- read-fonts/src/tables/glyf.rs
Fixes #1279
ref https://issues.oss-fuzz.com/issues/382732980
> [read-fonts] avoid overflow in midpoint computation

- skrifa/src/outline/glyf/hint/engine/outline.rs
first commit has failing test
ref https://issues.oss-fuzz.com/issues/377736138
> [skrifa] tthint: fix overflow in flip region instruction

- read-fonts/src/tables/variations.rs
first commit contains failing test
ref https://issues.oss-fuzz.com/issues/378159154
> [read-fonts] var: fix overflow in packed point numbers

- skrifa/src/outline/glyf/mod.rs
Fixes a small oversight: we explicitly didn't account for phantom point memory for empty glyphs. Just removes the explicit check and adds a test to ensure it works.
JMM
> [skrifa] empty glyphs have phantom points too

- skrifa/src/outline/glyf/hint/value_stack.rs
ref https://oss-fuzz.com/testcase-detail/5765856825507840 which wasn't filed as an issue yet due to similar failing test case
> [skrifa] tthint: overflow in move_index stack op

- read-fonts/src/tables/postscript/charstring.rs
first commit contains failing test
ref https://g-issues.oss-fuzz.com/issues/383609770
> [read-fonts] fix overflow in charstring eval

- skrifa/src/outline/autohint/shape.rs
Adds a stack to detect cycles in GSUB lookups while computing shaper coverage for autohinting.
Fixes #1295
> [skrifa] autohint: cycle detection for GSUB lookups

- read-fonts/src/tables/gvar.rs
First commit contains failing test.
ref https://g-issues.oss-fuzz.com/issues/385918147
> [read-fonts] avoid overflow when computing glyph data range

- font-test-data/src/ift.rs
- incremental-font-transfer/Cargo.toml
- incremental-font-transfer/src/font_patch.rs
- incremental-font-transfer/src/glyph_keyed.rs
- incremental-font-transfer/src/patch_group.rs
- incremental-font-transfer/src/patchmap.rs
The uri-template crate panics when encountering errors so switch to the uri-template-system crate which has error handling built into the API. Fixes fuzzer crashes from #1280.
> [IFT] switch to uri_template_system crate for URI template expansion.

- skrifa/src/outline/glyf/deltas.rs
- skrifa/src/outline/glyf/mod.rs
We were using gvar to compute deltas for left side-bearings but not for advance widths when the HVAR table is missing.
This only affects the TrueType interpreter (for Skia's usage) and hinted VFs are rare so it took a while to catch this one.
Fixes #1311
> [skrifa] glyf: use gvar for advance delta when HVAR is missing

- skrifa/src/outline/glyf/deltas.rs
- skrifa/src/outline/glyf/mod.rs
Additional code cleanup suggested after merging #1312
JMM
> [skrifa] cleanup phantom deltas

- font-test-data/src/ift.rs
- incremental-font-transfer/Cargo.toml
- incremental-font-transfer/src/bin/ift_extend.rs
- incremental-font-transfer/src/font_patch.rs
- incremental-font-transfer/src/glyph_keyed.rs
- incremental-font-transfer/src/patch_group.rs
Adds --design-space flag to ift_extend to specify design space as part of the target subset definition.
Also fix a bug in glyph keyed patch application on long loca tables.
> [IFT] Update ift_extend to support design space

- Cargo.toml
- font-test-data/src/ift.rs
- incremental-font-transfer/Cargo.toml
- incremental-font-transfer/src/font_patch.rs
- incremental-font-transfer/src/glyph_keyed.rs
- incremental-font-transfer/src/patchmap.rs
- klippa/src/lib.rs
- klippa/src/serialize.rs
- read-fonts/src/tables/gvar.rs
Glyph keyed format: https://w3c.github.io/IFT/Overview.html#glyph-keyed
Due to the nature of gvar, complex serialization with offset calculation was needed so I made the klippa Serializer public and used it here as it is designed specifically to handle this type of situation.
Also added a method to read_fonts::Gvar to provide more direct access to underlying bytes.
> [IFT] Add support for applying glyph keyed patches to gvar tables.

- font-test-data/src/ift.rs
- incremental-font-transfer/src/glyph_keyed.rs
additionally in long loca test since offsets are divided by 2 we actually need > 131072 bytes to trigger long loca.
> [IFT] divide loca offsets before casting down to u16 to avoid overflows.

- fuzz/fuzz_targets/fuzz_basic_metadata.rs
- read-fonts/generated/generated_hhea.rs
- read-fonts/generated/generated_vhea.rs
- read-fonts/src/table_provider.rs
- read-fonts/src/tables/hhea.rs
- resources/codegen_inputs/hhea.rs
- resources/codegen_inputs/vhea.rs
- write-fonts/generated/generated_hhea.rs
- write-fonts/generated/generated_vhea.rs
- write-fonts/src/lib.rs
This matches the spec; the old name was a relic of when we used a single common type to represent both vhea and hhea.
Also fixes the docs of both tables.
- closes #1213
> Rename Hhea::number_of_long_metrics => ...h_metrics

- skrifa/src/outline/error.rs
- skrifa/src/outline/glyf/mod.rs
- skrifa/src/outline/glyf/outline.rs
Fuzzing caught an overflow in contour end point shifts which occurs when a composite glyph contains more than 64k points. Since we compute the total point count up front, this simply rejects those glyphs when we try to generate an outline, returning an error instead.
For good measure, also ensures that contour end point indices are properly ordered when loading a glyph so that we don't end up with intermediate values that might overflow since point count only checks the final end point index.
ref https://issues.oss-fuzz.com/391753684
Fixes #1328
> [skrifa] reject composite outlines with more than 64k points

- klippa/src/gvar.rs
- read-fonts/src/tables/gvar.rs
- skrifa/src/metrics.rs
- skrifa/src/outline/glyf/deltas.rs
- skrifa/src/outline/glyf/mod.rs
- write-fonts/src/tables/gvar.rs
Instead of just Result<_,_>. This better represents the underlying semantics, where there is a potentially important distinction between deltas that do not exist at all and deltas that are expected to exist but cannot be read.
- closes #1277
> Gvar delta getters return Result<Option<_>,_>>

- skrifa/src/outline/glyf/hint/engine/delta.rs
- skrifa/src/outline/glyf/hint/value_stack.rs
Adds a new `ValueStack::pop_count_checked()` method that checks for negative stack values when we're popping a value intended for a count. Changing `ValueStack::pop_usize()` directly could affect our compatibility with FreeType when dealing with other instructions so that one is left unchanged.
Additionally limits the counts for DELTAP and DELTAC to point count and cvt size respectively since we don't expect those instructions to modify the same value more than once.
ref https://issues.oss-fuzz.com/issues/42538387
Fixes #1290
> [skrifa] avoid timeout in DELTA instructions

- font-types/src/tag.rs
We'd already decided to use this value (four spaces) as the value of Tag::default(), and it turns out that it is also allowed in OS/2, so exposing it as a constant seems useful.
> [types] Add Tag::NULL associated constant

- read-fonts/generated/generated_bitmap.rs
- read-fonts/src/tables/bitmap.rs
- resources/codegen_inputs/bitmap.rs
To better represent the actual structure of the bitmap location tables in the spec.
Adds `BitmapSize::index_subtable_list()` which can be used to enumerate the index subtables for a given size.
@qxliu76 please let me know if this is sufficient for subsetting
> [read-fonts] expose IndexSubtableList for bitmaps

- font-codegen/src/fields.rs
- font-codegen/src/parsing.rs
- font-test-data/src/ift.rs
- incremental-font-transfer/src/patch_group.rs
- incremental-font-transfer/src/patchmap.rs
- read-fonts/generated/generated_ift.rs
- read-fonts/generated/generated_name.rs
- read-fonts/generated/generated_post.rs
- read-fonts/src/lib.rs
- read-fonts/src/tables/ift.rs
- resources/codegen_inputs/ift.rs
- write-fonts/generated/generated_ift.rs
Copy indices becomes child indices. Intersection is now based on the intersection of the child entries instead of forming a union of the child entry subset definitions.
> Update copy indices implementation to match spec changes in https://github.com/w3c/IFT/pull/252

- write-fonts/Cargo.toml
- write-fonts/src/tables/variations/ivs_builder.rs
the fonttools VarStore.optimize() algorithm performs a sorting step on the input encodings (i.e. groups of delta sets characterized by the same row shape) to be processed before the heap-based priority queue is populated. This is to make sure the optimizer's output is stable no matter the order in which delta sets are processed.
Our Rust port currently does not perform any such sorting on the inputs; these get stored in an IndexMap and thus their order is not random, but depends on the order in which delta sets are added to the builder (usually e.g. for HVAR this means the glyph order); we only sort the output matching fonttools sort key.
But since this is a greedy algorithm the order in which things are processed matters. 
Moreover, while the priority queue is sorted by decreasing gain …
> [ivs_builder] match fonttools VarStore optimizer's stable ordering

- skrifa/src/outline/glyf/hint/engine/delta.rs
We limited these to point count/cvt size respectively but there are fonts (Arial is one) where these limits are not sufficient. Notably, you can have one exception per point/entry _and_ ppem so we can't use these counts for hard limits.
Instead limit both to `(stack_size / 2)` since each iteration requires two elements from the stack.
> [skrifa] tthint: adjust DELTAP/DELTAC limits

- read-fonts/src/tables/cmap.rs
- skrifa/src/charmap.rs
Meant to address fuzzing timeouts that all seem to point back to iterating cmap format 12 subtables. We previously limited characters to the max assigned codepoint and this extends that to limit glyphs to `maxp.numGlyphs`.
Reverts `Cmap12::iter()` to yield the raw mappings and adds a new `Cmap12::iter_with_limits()` that allows custom limits for both characters and glyphs. `Cmap12IterLimits::default_for_font(&FontRef)` produces the expected limits.
We _could_ have modified the cmap table to add these limits directly but reasons for not doing so are two-fold:
1. This prevents the read-fonts code from accurately representing the font data
2. Would require a lot of manual definitions and impls for many cmap types
Skrifa changed to use the limited version internally.
Avoids timeout for …
> Apply limits to cmap12 iterator

- write-fonts/src/tables/gvar.rs
Moved from original implementation in googlefonts/fontc#1225.
Motivation for moving:
> I've hit a road block adding tests: fontations' `GlyphDeltas` is public but its fields are not, and so `intermediate_region` cannot be inspected after construction.
> 
> We could make this field public, but I am tempted to argue that we make the wider change of moving the abstraction boundary lower into fontations, and treat this as serialisation logic.
> 
> e.g. give `GlyphDeltas` a `Vec<(F2Dot14, F2Dot14, F2Dot14)>` (or custom struct equivalent) and determine whether explicit intermediate coordinates are needed to be written at serialisation time.
> 
> I think this optimisation is higher-level than delta set optimisation but lower-level than IUP optimisation -- it is lossless, ttx does not expose it, …
> Only write explicit tuple min/maxes if there is an intermediate tent

- read-fonts/generated/generated_postscript.rs
- read-fonts/src/tables/cff.rs
- read-fonts/src/tables/postscript.rs
- read-fonts/src/tables/postscript/charset.rs
- read-fonts/src/tables/postscript/string.rs
- resources/codegen_inputs/postscript.rs
- write-fonts/generated/generated_postscript.rs
Lets us parse CFF charsets which enables support for reading glyph names from CFF fonts.
Makes some progress on #1261 and will soon be needed for harfruzz tests which depend on glyph names.
> [read-fonts] CFF charsets

- font-codegen/src/fields.rs
- font-codegen/src/record.rs
- read-fonts/src/tables/aat.rs
- write-fonts/generated/generated_avar.rs
- write-fonts/generated/generated_base.rs
- write-fonts/generated/generated_cff.rs
- write-fonts/generated/generated_cff2.rs
- write-fonts/generated/generated_cmap.rs
- write-fonts/generated/generated_cpal.rs
- write-fonts/generated/generated_font.rs
- write-fonts/generated/generated_fvar.rs
- write-fonts/generated/generated_gasp.rs
- write-fonts/generated/generated_gdef.rs
- write-fonts/generated/generated_gpos.rs
- write-fonts/generated/generated_gsub.rs
- write-fonts/generated/generated_hmtx.rs
- write-fonts/generated/generated_ift.rs
- write-fonts/generated/generated_layout.rs
- write-fonts/generated/generated_meta.rs
- write-fonts/generated/generated_name.rs
- write-fonts/generated/generated_postscript.rs
- write-fonts/generated/generated_sbix.rs
- write-fonts/generated/generated_stat.rs
- write-fonts/generated/generated_test_formats.rs
- write-fonts/generated/generated_test_records.rs
- write-fonts/generated/generated_variations.rs
- write-fonts/generated/generated_vmtx.rs
- write-fonts/generated/generated_vorg.rs
- write-fonts/src/tables/mvar.rs
- clarifies some #[repr(packed)] to #[repr(C, packed)]
- updates codegen to generate fewer useless `Into` conversions in constructor methods
> [chore] Clippy day

- skrifa/src/outline/autohint/shape.rs
- skrifa/src/outline/autohint/style.rs
- skrifa/src/outline/memory.rs
- skrifa/src/outline/mod.rs
Adds a visited set to GSUB traversal for autohinting to prevent redundant processing of lookups. This can cause a perceived hang on fonts with large complex lookup graphs (like Noto Nastaliq Urdu) even when there are no cycles.
Also removes the existing cycle detection code since it is no longer needed.
Fixes #1363
> [skrifa] autohint: use visited set when processing GSUB lookups

- Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
Release tip of tree with fix for #1363 hang in gsub processing during autohinting of Noto Nastaliq.
Changes for read-fonts from read-fonts-v0.27.1 to 0.27.1
5657ab8 [chore] Clippy day
53407d0 [read-fonts] CFF charsets (#1361)
Changes for write-fonts from write-fonts-v0.36.0 to 0.36.0
5657ab8 [chore] Clippy day
029f62f [font_builder] provide more expository comment
7f95b52 [font_builder] test recommended table order
a49be74 [font_builder] test checksum_adjustment
ffc69ee [font_builder] compute head.checksum_adjustment and sort table in recommended order
53407d0 [read-fonts] CFF charsets (#1361)
Changes for skrifa from skrifa-v0.28.0 to 0.28.0
e250138 [skrifa] autohint: use visited set when processing GSUB lookups (#1365)
441a388 [skrifa] Remove unused write-fonts dev-dep
652b3ca Apply …
> Bump version numbers to release fix for autohint hanging

- incremental-font-transfer/src/font_patch.rs
- shared-brotli-patch-decoder/Cargo.toml
- shared-brotli-patch-decoder/src/c_brotli.rs
- shared-brotli-patch-decoder/src/decode_error.rs
- shared-brotli-patch-decoder/src/lib.rs
- shared-brotli-patch-decoder/src/rust_brotli.rs
The pure rust decoder implementation is needed when compiling to WASM which can't easily work with the c version.
> Set up shared-brotli-patch-decoder to be able to utilize a rust or c brotli decoder implementation.

- incremental-font-transfer/src/patchmap.rs
SubsetDefinition is used in the ift public api so make it's members actually accessible so it's possible to modify one.
> Make SubsetDefinition members public.

- skrifa/src/attribute.rs
- skrifa/src/color/mod.rs
- skrifa/src/metrics.rs
- skrifa/src/string.rs
- skrifa/src/variation.rs
We needed a full `FontRef` for outlines anyway so this changes all other constructors to take `FontRef` as well for consistency.
JMM
> [skrifa] impl TableProvider -> FontRef in ctors (breaking)

- skrifa/src/glyph_name.rs
- skrifa/src/glyph_names.rs
- skrifa/src/lib.rs
- skrifa/src/provider.rs
Adds an API for accessing glyph names. Tries the `post` and `CFF` tables in that order. If neither are available or do not contain glyph names, then this generates synthesized names in the format `gidDDD` to match HarfBuzz.
Fixes #1261
> [skrifa] glyph names API

- Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
Changes for read-fonts from read-fonts-v0.27.2 to 0.27.3
85352c0 Collection of glyf/gvar performance improvements (#1390)
1bb6245 [read-fonts] fix slow cmap 12 test (#1383)
dd282f7 Fix some typos, update `typos` check in CI
6680a36 [klippa] subset HVAR/VVAR tables
Changes for skrifa from skrifa-v0.28.1 to 0.29.0
85352c0 Collection of glyf/gvar performance improvements (#1390)
720f49d [skrifa] glyph names API (#1387)
3baac34 [skrifa] malloc free cycle detection (#1388)
53ccad4 clippy
ab4680c [skrifa] impl TableProvider -> FontRef in ctors (breaking)
> [chore] bump read (patch), skrifa (minor)

- read-fonts/src/tables/cff.rs
We were treating CIDs as SIDs for CID-keyed fonts leading to incorrect glyph names.
Fixes #1404
> [read-fonts] no glyph names for CID-keyed CFF fonts

- write-fonts/Cargo.toml
- write-fonts/src/hex_diff.rs
It is available in google3, ansi-term isn't. 
JMM
> Migrate to nu-ansi-term

- incremental-font-transfer/src/lib.rs
- incremental-font-transfer/src/uri_templates.rs
In the IFT spec we're restricting the URI template to a small subset of the general URI template syntax (see: https://github.com/w3c/IFT/pull/263). This makes it reasonable to write our own template expansion functionality instead of relying on a general parser implementation.
This takes a pass at implementing one (to see how it looks in practice), but does not yet hook it up to the rest of the IFT client. Ultimately it should allow us to drop the dependency on "uri-template-system".
> Prototype implementation of the IFT specific subset of URI templates.

- read-fonts/src/tables/cmap.rs
- skrifa/src/charmap.rs
- write-fonts/src/tables/cmap.rs
Changes both read-fonts and skrifa so that read-fonts always returns explicitly mapped notdef glyphs and skrifa never does. Covers both map functions and iterators.
Fixes #1400
> cmap/charmap: consistent notdef results

- skrifa/src/glyph_name.rs
Follow up to #1403 which did this for `GlyphNames::get()`.
Fixes #1410
> [skrifa] synthesize glyph names for empty strings in iterator

- Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
Changes for read-fonts from read-fonts-v0.27.3 to 0.27.4
16b9a52 cmap/charmap: consistent notdef results (#1414)
2eac260 [klippa] subset GDEF table step 1: collect/map variation indices
cce82fb [read-fonts] no glyph names for CID-keyed CFF fonts (#1406)
c022daf [klippa] subset COLR and CPAL
Changes for skrifa from skrifa-v0.29.0 to 0.29.1
b673471 [skrifa] synthesize glyph names for empty strings in iterator (#1415)
16b9a52 cmap/charmap: consistent notdef results (#1414)
2dadd89 [skrifa] Synthesize glyph name if it's empty string
> [chore] bump patch for read/skrifa

- incremental-font-transfer/Cargo.toml
- incremental-font-transfer/src/bin/ift_graph.rs
- incremental-font-transfer/src/lib.rs
- incremental-font-transfer/src/patch_group.rs
- incremental-font-transfer/src/patchmap.rs
- incremental-font-transfer/src/uri_templates.rs
- Also syncs up to some recent spec changes with regards to handling undefined expansion variables.
> Drop uri-template-system and instead use our own template expander in IFT client.

- skrifa/src/color/mod.rs
- skrifa/src/color/traversal.rs
We spill to the heap for more than 32 color stops, but will only use one allocation per glyph.
> [skrifa] use SmallVec for color stop resolution

- skrifa/src/outline/memory.rs
Let's try to keep some more work off the heap.
Motivated by our excessive allocations for NotoSansCJK-VF as documented by @behdad here: https://docs.google.com/document/d/1S47f3E--yqvFdG7lmmufxRoFi_wMzotC03v8UvS_p54/edit?tab=t.0#heading=h.bfj7urloz3oe
JMM
> [skrifa] add 8k and 16k buckets to stack allocator

- Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
Changes for read-fonts from read-fonts-v0.27.4 to 0.27.5
c32c0a6 Bypass variation processing for default location (#1423)
Changes for skrifa from skrifa-v0.29.1 to 0.29.2
3a6a9f2 [Skrifa/COLRv1] Add pop_layer_with_mode()
c32c0a6 Bypass variation processing for default location (#1423)
756d450 [skrifa] add 8k and 16k buckets to stack allocator
8209ac2 [skrifa] use SmallVec for color stop resolution (#1420)
> [chore] bump patch for read-fonts/skrifa

- incremental-font-transfer/src/uri_templates.rs
- This avoids needing to use OnceLock and removes the run time initialization of the byte info map on first use.
- Also do some refactoring to reduce the amounts of arguments being passed around in the handle_* methods.
> In URI Template impl build the byte info map at compile time

- font-test-data/src/ift.rs
- incremental-font-transfer/src/glyph_keyed.rs
As mentioned in the spec: https://w3c.github.io/IFT/Overview.html#apply-glyph-keyed a glyph keyed patch application should upgrade the size of offsets in the patched table when needed. Implement this for gvar.
> Allow gvar offset size to be upgraded during IFT patch application.

- incremental-font-transfer/src/bin/ift_extend.rs
- klippa/src/main.rs
- read-fonts/generated/generated_os2.rs
- read-fonts/src/tables/name.rs
- resources/codegen_inputs/os2.rs
- resources/raw_tables/head.txt
- write-fonts/generated/generated_os2.rs
This includes changes to use "Unicode" as a proper noun more often as well as to use the term "codepoint" rather than the occasional usage of "code points".
> Reduce typo count

- skrifa/src/charmap.rs
Add a comment that mappings may contain glyph ids beyond maxp::num_glyphs.
Compare https://issues.chromium.org/405286754
> [Skrifa] Update documentation for mappings

- Cargo.toml
- fuzz/fuzz_targets/int_set_op_processor.rs
- read-fonts/Cargo.toml
- read-fonts/src/codegen_test.rs
- read-fonts/src/collections/int_set/bitpage.rs
- read-fonts/src/collections/int_set/bitset.rs
- read-fonts/src/collections/int_set/mod.rs
- read-fonts/src/tables/variations.rs
This is slightly tricky because we need to ensure on deserialization that the data is valid for the given domain.
We need these impls in order to be able to use int set more broadly.
Also: adding serde_json as a dev dependency to read-fonts caused a bunch of existing code to stop compiling in a way that really looks like a rustc bug; I've changed the offenders here but it makes this a noisier patch than I'd hoped.
> [int-set] Impl Serialize, Deserialize

- read-fonts/src/collections/int_set/bitpage.rs
- read-fonts/src/collections/int_set/bitset.rs
This was something we'd wanted to do a while ago but now I'm motivated by clippy not liking `Cell` to be used in any type that could be stored in a {hash,btree}set.
> [int-set] Remove use of Cell

- read-fonts/src/collections/int_set/mod.rs
Because the derived one was not very intelligible.
... also cleans up some imports because I'm impulsive.
JMM
> [int-set] Add a manual Debug impl

- write-fonts/src/tables/layout.rs
- write-fonts/src/tables/layout/builders.rs
This will replace the previous, simpler ClassDef builder as the public API: the new builder includes a bit more opinionated logic, like sorting classes to match what fonttools does.
- this is a part of the larger program of moving a bunch of generally-useful builders out of fea-rs and into write-fonts.
- based on #1438 and #1440, (which were required in order for this to work)
> [write] Move over ClassDefBuilder from fea-rs

- read-fonts/src/collections/int_set/mod.rs
- read-fonts/src/tables/gsub/closure.rs
This was originally written before we had a nice integer set type, which should make it quite a bit more efficient.
(this is technically a breaking change, although it should only break fontc)
> [read] Update gsub closure code to use IntSet

- write-fonts/src/tables/gpos.rs
- write-fonts/src/tables/gpos/builders.rs
- write-fonts/src/tables/gsub.rs
- write-fonts/src/tables/gsub/builders.rs
- write-fonts/src/tables/layout/builders.rs
These types are all generally a much better way of generating the relevant tables than the generated API.
This surgery was a bit more involved than I'd expected, and required a few little tweaks to make it suited to the general case (and not just the case of working from FEA).
Overall though this doesn't change any observable behaviour.
based on #1441.
> Move layout builders over from fea-rs

- write-fonts/src/tables/gsub/builders.rs
- write-fonts/src/tables/layout.rs
This is much easier than splitting them during packing.
This fixes at least one crater crash, and also resolves an error that we encounter when compiling a brand font (although, unfortunately, we seem to hit another unrelated error afterwards)
> [write] Split ligature subtables during compilation

- read-fonts/src/tables/stat.rs
AxisValue table formats 1, 2 and 3 are very similar; STAT table consumers often want to know the values (or nominal values), axis indices, etc. for axis value tables, without wanting to match and extract from the inner data structure. This is a handy abstraction to make this more pleasant for consumers.
> Add accessors to common axis values

- font-test-data/src/ift.rs
- incremental-font-transfer/src/glyph_keyed.rs
- read-fonts/generated/generated_ift.rs
- read-fonts/src/tables/ift.rs
- resources/codegen_inputs/ift.rs
- write-fonts/generated/generated_ift.rs
Context: https://w3c.github.io/IFT/Overview.html#cff
In the IFT mapping tables of fonts with CFF or CFF2 tables the offsets to the charstrings INDEX structures are stored. Parse and utilize these to locate the charstring data structures during patch application instead of pulling the offsets out of the CFF tables.
> [IFT] Use stored charstring offsets to locate charstring tables

- fuzz/Cargo.toml
- fuzz/fuzz_targets/fuzz_ift_patch_group.rs
- incremental-font-transfer/src/bin/ift_extend.rs
- incremental-font-transfer/src/bin/ift_graph.rs
- incremental-font-transfer/src/font_patch.rs
- incremental-font-transfer/src/glyph_keyed.rs
- incremental-font-transfer/src/patch_group.rs
- incremental-font-transfer/src/table_keyed.rs
- shared-brotli-patch-decoder/src/lib.rs
This is needed to support a WASM version of the rust IFT client which can't use the c brotli used by default. As an added bonus this opens the door for increasing fuzzing coverage by allowing the fuzzer to provide a custom implementation that can generate errors.
> [IFT] allow a custom brotli implementation to be provided for patch application.

- fauntlet/Cargo.toml
- read-fonts/src/tables/postscript/dict.rs
- read-fonts/src/tables/postscript/stack.rs
- skrifa/src/outline/cff/hint.rs
- skrifa/src/outline/cff/mod.rs
* Don't truncate fixed values when parsing (blue zones, scale, shift, fuzz, etc)
* Match FreeType's parsing of binary coded decimal numbers
* Fix bug where we were overwriting "family blues" with "family other blues"
* Update fauntlet to latest available FreeType via freetype-rs (2.13.2)
Basically follows FreeType fix https://gitlab.freedesktop.org/freetype/freetype/-/commit/8eab511017a65026985523cab14aff07f1bb9746
> Update CFF hinting to match FreeType

- read-fonts/generated/generated_test_records.rs
- read-fonts/src/array.rs
- resources/codegen_inputs/test_records.rs
- write-fonts/generated/generated_test_records.rs
Since we use the item length to track the iterator state, zero length items will cause the iterator to loop forever.
JMM if happy
> [read-fonts] VarLenArray: stop iteration at zero length item

- .github/workflows/rust.yml
- Cargo.toml
- font-test-data/Cargo.toml
- font-test-data/src/ift.rs
- font-types/Cargo.toml
- font-types/src/uint24.rs
- font-types/src/version.rs
- read-fonts/Cargo.toml
- read-fonts/src/collections/int_set/mod.rs
- read-fonts/src/tables/gsub/closure.rs
- read-fonts/src/tables/meta.rs
- read-fonts/src/tables/postscript/index.rs
- skrifa/Cargo.toml
- skrifa/src/glyph_name.rs
- skrifa/src/outline/autohint/outline.rs
- skrifa/src/outline/autohint/style.rs
- skrifa/src/outline/autohint/topo/mod.rs
- write-fonts/Cargo.toml
- write-fonts/src/tables/glyf/simple.rs
Let's go ahead and get something merged. This supersedes #1450.
- I'm going with 1.75, which gives us impl trait in traits, and tracks ubuntu LTS.
- I'm turning this on for all production crates, but not yet for other stuff (including klippa)
> MSRV take two

- font-types/src/version.rs
- read-fonts/src/tables/cmap.rs
Also indirectly tested with a real-life font I found in a PDF file.
> Support mapping codepoints for cmap0 and cmap6 subtables

- Cargo.toml
- font-test-data/Cargo.toml
- font-types/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
Changes for font-types from font-types-v0.8.4 to 0.9.0
4f802e9 [chore] bump minor for everything
7d6b8d5 [chore] Set MSRV to 1.75
126d981 Set MSRV for font-types, read-fonts, write-fonts and skrifa to 1.71
d418836 Reformat
b42f5b2 Fix wrong message
Changes for read-fonts from read-fonts-v0.28.0 to 0.29.0
4f802e9 [chore] bump minor for everything
c181a5a [read-fonts] small perf improvement in IVS (#1461)
4ba610c unify code for cmap 12/13, add cmap13 tests
b413669 [chore] Get cargo test working on 1.75
7d6b8d5 [chore] Set MSRV to 1.75
3d3bd85 Replace get_or_insert_default with get_or_insert_with(Default::default)
126d981 Set MSRV for font-types, read-fonts, write-fonts and skrifa to 1.71
3ebd31c Use predicate matcher instead of array matches
bee845d Remove eprintln
ce09c6f Fix clippy …
> [chore] bump minor for everything

- font-test-data/src/ift.rs
- fuzz/fuzz_targets/fuzz_ift_patch_group.rs
- incremental-font-transfer/src/bin/ift_extend.rs
- incremental-font-transfer/src/bin/ift_graph.rs
- incremental-font-transfer/src/patch_group.rs
- incremental-font-transfer/src/patchmap.rs
- read-fonts/generated/generated_ift.rs
- read-fonts/src/tables/ift.rs
- resources/codegen_inputs/ift.rs
- write-fonts/generated/generated_ift.rs
This updates the fontations IFT client to match spec changes made in: https://github.com/w3c/IFT/pull/262
Overview:
- Format 2 entries now have the ability to specify lists of entry id deltas (previously each entry had exactly one delta)
- These delta lists become a list of URIs where the first URI is the patch to be applied as usual and any additional URIs should be preloaded if the entry is selected.
- The format 2 parsing is updated to handle multiple deltas and all of the patch map handling has been updated to correctly handle preloads specified in this way.
> Support preload lists on patch map entries.

- write-fonts/src/tables/gsub/builders.rs
This is needed in fea-rs to match the current behaviour of fonttools.
> [write] Add helper for promoting single -> liga subs

- read-fonts/src/tables/variations.rs
Try to avoid the overhead for inactive tuple variations.
> [read-fonts] custom ActiveTupleVariationIter

- skrifa/generated/generated_autohint_styles.rs
- skrifa/scripts/gen_autohint_styles.py
Invisible Unicodes such as U+200D in source code can get flagged as "suspicious". Using visible escape sequences makes it clearer exactly what's present.
> Avoid invisible Unicode chars in source code

- font-test-data/src/lib.rs
- skrifa/src/metrics.rs
- skrifa/src/outline/pen.rs
Fixes #1528. Adds a ControlBoundsPen structure, stores the FontRef in the GlyphMetrics struct (with appropriate changes to lifetimes everywhere), and uses outlining to get the glyph bounds when the font has variations or a CFF/CFF2 table.
> Provide glyph bounds in VF and CFF cases

- fauntlet/src/font/mod.rs
- incremental-font-transfer/src/glyph_keyed.rs
- incremental-font-transfer/src/table_keyed.rs
- klippa/src/lib.rs
- otexplorer/src/main.rs
- read-fonts/src/lib.rs
- write-fonts/src/font_builder.rs
This does a few things:
* Makes all `FontRef` fields private and adds accessor methods. Hopefully will avoid breaking changes on this type in the future.
* Adds a new field/accessor for the ttc index of the font.
* Adds a new `FontRef::all_in(&[u8])` method that returns an iterator over all fonts in the given data (as `Result<FontRef, _>`).
There were some uses of the `FontRef::table_directory` field in other crates. Updates those to use the new method.
> FontRef API changes

- Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
Changes for read-fonts from read-fonts-v0.29.3 to 0.30.0
02ace2e FontRef API changes (#1536)
f37c230 inline some commonly used methods (#1535)
920c801 Change the `is_sorted` implementation
e606cba [cff] handle implied seac operator (#1533)
d035a15 Update remaining IFT code for the URL template change.
687f07a [klippa] clousre glyphs
de9558c Don't use `is_sorted`
03c3294 Support loading hmtx tables with missing left side bearings
f92657a Support fonts with unsorted table directories
f47a300 [klippa] layout closure: closure lookups
d776fd6 Test that we select the correct shallow component to derive metrics from
51f6ea4 Prefer the last component in the tree with USE_MY_METRICS set
Changes for skrifa from skrifa-v0.31.3 to 0.32.0
e606cba [cff] handle implied seac operator (#1533)
5f3ea6c Save …
> [chore] bump minor for read/skrifa

- read-fonts/src/lib.rs
Temporarily, to fix roll in Skia/Chrome
> make FontRef::table_directory field public

- skrifa/src/outline/glyf/hint/engine/outline.rs
There was a panic reported here (#1524) which can only be an overflow on multiply or abs so replace it with wrapping variants to match FreeType.
JMM
> [skrifa] tthint: use wrapping mul/abs in ISECT

- font-test-data/src/ift.rs
- incremental-font-transfer/src/patchmap.rs
Patch selection order requires us to order based on the intersection of the union of all child entries. We were only using the intersection of the root entry (ignoring children).
Context: https://w3c.github.io/IFT/Overview.html#invalidating-patch-selection
> [IFT] Fix patch selection order for entries with child indices.

- read-fonts/src/tables/postscript/dict.rs
FreeType uses an internal scaling factor of 1000 when parsing BlueScale, presumably to increase precision of the fractional part. This adjust our code to match.
Note: this adds a field to the public `dict::Token::Operand` variant so is a breaking change for read-fonts.
> [read-fonts] parse PrivateDICT/BlueScale with additional scaling factor

- fauntlet/src/font/freetype.rs
Both Skrifa and FreeType have this optimization but the FT patch hasn't made it to our `freetype-sys` dependency yet so just avoid setting coordinates on the FreeType instance when they represent the default location.
> [fauntlet] don't enable var processing for FT at default instance

- fauntlet/src/compare_glyphs.rs
- fauntlet/src/font/freetype.rs
- fauntlet/src/font/mod.rs
- fauntlet/src/font/skrifa.rs
- fauntlet/src/main.rs
Adds new `--hinting-engine` and `--hinting-target` CLI options to select the hinting mode. Allows specifying `all` for each to run the full matrix of modes.
> [fauntlet] add CLI options for hinting modes

- skrifa/src/outline/glyf/mod.rs
- skrifa/src/outline/hint.rs
- skrifa/src/outline/mod.rs
When hinting, round ppem prior to computing scale when the font has bit 3 set in `head.flags`. This matches FreeType behavior when scaling at fractional sizes.
Additional fix for #1544, specifically targeting the MS core web fonts
@drott we can't really match this behavior for glyph metrics because we don't know when hinting was requested. This patch adds a new `OutlineGlyphCollection::fractional_size_hinting() -> bool` method. When Skia constructs a `GlyphMetrics` object, it should check the result of this method and round the size passed to ` GlyphMetrics::new()` when hinting is enabled to ensure matching metrics.
> [skrifa] tthint: round ppem based on head.flags 

- skrifa/src/outline/autohint/outline.rs
- skrifa/src/outline/path.rs
I'm playing around with a port of ab_glyph to skrifa, and it's a bit slower than ttf_parser currently.
The biggest culprit currently, at least for TrueType outlines, is `contour_to_path`. I *think* the issue is that it creates a peekable iterator for the contour points, and that iterator seems to not be getting fully inlined or optimized.
I've specialized the function into two separate "FreeType-style" and "HarfBuzz-style" functions, and now also pass in the first point. This lets us get rid of the peekable iterator in the FreeType path, as well as removing code paths not taken for the given `PathStyle`, and improves performance by ~13% on an outlining-only benchmark.
Before:
After:
> Optimize/specialize `outline::path::contour_to_path`

- klippa/src/gpos/cursive_pos.rs
- klippa/src/gpos/mark_array.rs
- klippa/src/gpos/mark_base_pos.rs
- klippa/src/gpos/mark_lig_pos.rs
- klippa/src/gpos/mark_mark_pos.rs
- klippa/src/gpos/pair_pos.rs
- klippa/src/gpos/single_pos.rs
- klippa/src/layout.rs
Besides subsetting MarkBasePos table, this PR also replaces some duplicate iterating logic with a fn in other GPOS tables.
Note this PR is dependent on #1570.
> [klippa] subset MarkBasePos table

- Cargo.toml
- read-fonts/Cargo.toml
Changes for read-fonts from read-fonts-v0.31.2 to 0.31.3
436bf9e [read-fonts] Avoid overflow in matrix degeneracy check (#1596)
641471f [Coverage/ClassDef] Add a cost() method (#1591)
> [chore] bump patch for read-fonts

- read-fonts/src/collections/int_set/bitset.rs
- read-fonts/src/collections/int_set/mod.rs
- read-fonts/src/collections/int_set/sparse_bit_set.rs
This is a lower level set container that only works with u32's and unlike IntSet is not invertible. However, this means there's less overhead for most of the basic operations. This set will be useful in performance critical areas where the custom int types and invertibility aren't needed.
Fixes #1600
> Rename BitSet -> U32Set and make it public.

- resources/codegen_inputs/gvar.rs
- write-fonts/generated/generated_gvar.rs
- write-fonts/src/tables/gvar.rs
fontc/fontations was writing the gvar components in a wrong order, it was pushing the Shared Tuples to the end of the table, while the spec mandates that they are between the table header and the Glyph Variation Data.
https://learn.microsoft.com/en-us/typography/opentype/spec/gvar#shared-tuples-array
> The shared tuples array follows the GlyphVariationData offsets array at the end of the 'gvar' header.
We believe this fixes the Windows 10 crashes of the Google Sans Code release: https://github.com/googlefonts/googlesans-code/issues/22
This also fixes unpacking the gvar table in OT Master.
We tested the previous release versus a TTF built with fontc using this fontations branch, and the new version didn't crash or mess up the system as the official release did.
> Write gvar table shared tuples in the expected place

- Cargo.toml
- font-test-data/Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
```
Changes for read-fonts from read-fonts-v0.31.3 to 0.32.0
a68280b [read-fonts] Fix BCD parsing when fraction len <= 0 (#1618)
5f5c6b3 [U32Set] internally cache the last page index used.
f2b2a2a [avar] Port updated interpolation algorithm from HarfBuzz (#1616)
4fa0288 Clippy (#1613)
9fb668d [read-fonts] small update to use newly added APIs
1d460a4 Fix IntSet refs in U32Set docs.
b485e0e Rename BitSet -> U32Set and make it public.
79a14dc Add read and write for `DSIG` table (#1589)
a48e954 [read-fonts] take Into<GlyphId> for ClassDef types (#1605)
f44f407 [read-fonts] small fix for cmap10  (#1604)
7feff0f [read-fonts] new Value type and PairPos2 fast path (#1602)
Changes for font-test-data from font-test-data-v0.4.1 to 0.5.0
e3ef9fa [skrifa] tthint: round value for MPPEM instruction …
```
> bump read-fonts minor version and all the others that reexport it

- resources/scripts/release.sh
#1620 didn't quite work as intended... This time it will work! I tested by replacing all the `cargo` calls with `sleep` and CTRL-C this time around was intercepted.
> use explicit trap to handle SIGINT in release.sh

- read-fonts/src/tables/cmap.rs
This is a first small step towards unifying some duplicated code between skrifa and harfrust.
Adds some utility methods to `Cmap` and related types that assist in selecting appropriate subtables for symbol, unicode and variation sequences.
> [read-fonts] add some cmap helpers

- Cargo.toml
- write-fonts/Cargo.toml
To release a version that is usable with the latest read-fonts/skrifa/harfrust.
> [chore] bump minor for write-fonts

- Cargo.toml
- read-fonts/Cargo.toml
This brings in a fix for a bug in glyph closure, needed by fontc.
> [chore] Bump read-fonts to 0.33.1

- Cargo.toml
- read-fonts/Cargo.toml
- skrifa/Cargo.toml
- write-fonts/Cargo.toml
Changes for read-fonts from read-fonts-v0.33.1 to 0.34.0
3f3793c Fix CFF scaling with a nested font matrix (#1644)
88494f0 [read-fonts] aat: preparse some state table fields (#1645)
b57298c [aat/state-machine] Drop a check, since can't overflow (#1642)
7f47a32 [aat] Inline a hot method (#1641)
2daecae [read-fonts/bitset] Inline a hot function
15c3543 [read-fonts/aat] Make StateMachine header public (#1637)
c1c519d [IntSet] Correct U32Set::intersects() implementation.
7818a9c [U32Set] Implement intersects()
29bbde0 [read-fonts] Avoid timeout when computing array len (#1634)
5efa529 [read_fonts/aat] Expose more of the lookup internals (#1633)
Changes for skrifa from skrifa-v0.35.0 to 0.36.0
3f3793c Fix CFF scaling with a nested font matrix (#1644)
> [chore] bump minor for read/writes/skrifa

- skrifa/src/charmap.rs
It looks like we're recomputing the `cmap12_limits` when building a charmap from a `MappingIndex` despite it already being calculated within `MappingSelection`:
https://github.com/taj-p/fontations/blob/07df8391a0b33f2402cf8ab78f5bf01c90c3a647/skrifa/src/charmap.rs#L398
This PR uses the precomputed `cmap12_limits` instead of recomputing its value.
> Don't recompute cmap12 limits

- skrifa/src/outline/autohint/topo/segments.rs
OSS fuzz ref: https://oss-fuzz.com/testcase-detail/5446493076258816 and https://oss-fuzz.com/testcase-detail/5446493076258816
First commit contains failing test.
> Subtract overflow in autohint State::apply_to_segment

- skrifa/src/outline/cff/mod.rs
OSS fuzz ref: https://oss-fuzz.com/testcase-detail/6498790355042304 and https://issues.oss-fuzz.com/issues/444024349
Extracted the hint scale logic into a separate function for testing.
First commit contains failing test.
> Add with overflow in CFF hint scale computation
