googlefonts/fontations

font-tables/examples/inspect.rs, font-tables/src/tables.rs, font-tables/src/tables/hhea.rs, font-tables/src/tables/hmtx.rs, font-tables/src/tables/name.rs, font-tables/src/tables/post.rs, font-types-macro/src/lib.rs, font-types-macro/src/parse.rs, font-types-macro/src/parse/attrs.rs, font-types/src/fword.rs, font-types/src/version.rs, resources/tables/hhea.txt, resources/tables/hmtx.txt, resources/tables/name.txt, resources/tables/post.txt
This impls the hhea, hmtx, name, and post tables.
=> Other req tables

font-tables/examples/inspect.rs, font-tables/src/tables.rs, font-tables/src/tables/stat.rs, font-types-macro/src/bin/codegen.rs, font-types-macro/tests/tuple-format-enum.rs, font-types/src/version.rs, resources/tables/stat.txt
Also includes some improved diagnostics in the codegen tool.
=> Add STAT table

font-tables/examples/inspect.rs, font-tables/src/layout.rs, font-tables/src/tables.rs, font-tables/src/tables/gdef.rs, font-tables/src/tables/name.rs, font-tables/src/tables/stat.rs, font-types-macro/src/lib.rs, font-types/src/version.rs, resources/tables/gdef.txt
I want to have a table in the repo that has more of a graph structure, but maybe not as much of a graph structure as GPOS/GSUB? 🤷
=> Basic GDEF impl

font-types/src/version.rs, read-fonts/examples/inspect.rs, read-fonts/generated/generated_glyf.rs, read-fonts/src/table_provider.rs, read-fonts/src/tables/glyf.rs, read-fonts/src/tables/loca.rs, resources/codegen_inputs/glyf.rs
This PR includes a few commits that were part of the subset work, but which are general enough that they should be PR'd independently.
=> Commits from subset work

read-fonts/src/read.rs
This was an old TODO that I finally ran into 😅
=> Impl Display for ReadError

font-types/src/tag.rs
=> [font-types] Fix typo in error impl

font-types/src/version.rs, otexplorer/README.md, write-fonts/src/from_obj.rs, write-fonts/src/lib.rs
This is all little stuff I encountered in the process of writing the architecture document.
=> A variety of small doc-related fixups

read-fonts/generated/generated_cpal.rs, read-fonts/src/tables/cpal.rs, resources/codegen_inputs/cpal.rs, write-fonts/generated/generated_cpal.rs
~This is on top of #75, which will be merged first.~
I'm encouraged by how much code this deletes.
=> Update CPAL to use offsets to arrays

README.md, docs/codegen-tour.md, font-codegen/README.md
This is a big brain dump explaining the various bits of code that we generate, and how they fit together.
[Rendered](https://github.com/cmyr/fontations/blob/codegen-tour/docs/codegen-tour.md)
=> Add docs/codegen-tour.md

font-codegen/README.md, font-codegen/src/parsing.rs, font-codegen/src/record.rs, font-codegen/src/table.rs, read-fonts/generated/generated_gpos.rs, read-fonts/generated/generated_gsub.rs, read-fonts/generated/generated_layout.rs, resources/codegen_inputs/gpos.rs, resources/codegen_inputs/gsub.rs, resources/codegen_inputs/layout.rs
This better expresses this attribute's purpose.
=> Rename #[phantom] to #[generic_offset]

docs/codegen-tour.md, read-fonts/src/array.rs
=> Basic documentation of array types in codegen-tour.md

font-codegen/src/lib.rs, font-codegen/src/parsing.rs, resources/codegen_inputs/gpos.rs
=> Add extern record and scalar notation, use in gpos

read-fonts/src/table_provider.rs
=> Fix arg order in TableProvider::hmtx

font-types/src/fword.rs
This adds default, as well as From/Into the inner numerical types.
=> More basic traits for FWord and UfWord

presubmit.sh
=> Add script to do a local check that CI will probably pass

write-fonts/src/collections.rs, write-fonts/src/tables/stat.rs
There were changes added after this PR was made that were broken by it.
=> Fix breakage around no-option OffsetMarker

font-types/src/fixed.rs, font-types/src/fword.rs, font-types/src/glyph_id.rs, font-types/src/longdatetime.rs, font-types/src/offset.rs, font-types/src/tag.rs, font-types/src/uint24.rs, font-types/src/version.rs
I needed one of these, so why not all?
=> Make font-types fns const where possible

read-fonts/generated/generated_layout.rs, resources/codegen_inputs/layout.rs, write-fonts/generated/generated_layout.rs
=> Use GlyphId for type of layout glyph sequences

read-fonts/src/array.rs, read-fonts/src/font_data.rs, read-fonts/src/lib.rs, read-fonts/src/offset.rs, read-fonts/src/read.rs, read-fonts/src/table_provider.rs, read-fonts/src/tables/avar.rs, read-fonts/src/tables/cmap.rs, read-fonts/src/tables/colr.rs, read-fonts/src/tables/cpal.rs, read-fonts/src/tables/gdef.rs, read-fonts/src/tables/gsub.rs, read-fonts/src/tables/head.rs, read-fonts/src/tables/hhea.rs, read-fonts/src/tables/hmtx.rs, read-fonts/src/tables/hvar.rs, read-fonts/src/tables/loca.rs, read-fonts/src/tables/lookupflag.rs, read-fonts/src/tables/maxp.rs, read-fonts/src/tables/mvar.rs, read-fonts/src/tables/os2.rs, read-fonts/src/tables/post.rs, read-fonts/src/tables/stat.rs, read-fonts/src/tables/value_record.rs, read-fonts/src/tables/vhea.rs, read-fonts/src/tables/vmtx.rs, read-fonts/src/tables/vvar.rs, read-fonts/src/tests/test_gdef.rs, read-fonts/src/traversal.rs
This matches the style in write-fonts.
=> Use extern crate reexport style, update use stmts

read-fonts/src/font_data.rs, resources/codegen_inputs/head.rs, write-fonts/generated/generated_head.rs, write-fonts/src/font_builder.rs
This is a rollup of three small commits fixing issues I encountered while hacking on feature compilation.
=> A few more compile-motivated tweaks

write-fonts/src/tables/post.rs
This lets us write out a valid post table, which is useful for fea-rs.
=> Add builder for post 2.0

write-fonts/src/tables/name.rs
We were counting bytes and not chars.
=> Fix incorrect size calculation for MacRoman strings

docs/codegen-tour.md, font-codegen/README.md, font-codegen/src/fields.rs, font-codegen/src/parsing.rs, font-codegen/src/record.rs, font-codegen/src/table.rs, resources/codegen_inputs/base.rs, resources/codegen_inputs/colr.rs, resources/codegen_inputs/cpal.rs, resources/codegen_inputs/font.rs, resources/codegen_inputs/gdef.rs, resources/codegen_inputs/gpos.rs, resources/codegen_inputs/gsub.rs, resources/codegen_inputs/maxp.rs, resources/codegen_inputs/name.rs, resources/codegen_inputs/os2.rs, resources/codegen_inputs/post.rs, resources/codegen_inputs/stat.rs, resources/codegen_inputs/test_offsets_arrays.rs
This is hopefully clearer to the reader.
=> [codegen] Rename #[available] -> #[since_version]

read-fonts/src/tables/glyf.rs
Was looking at glyf while thinking about gvar.
=> Small tweaks to docs in glyf.rs

font-codegen/src/fields.rs, write-fonts/generated/generated_base.rs, write-fonts/generated/generated_cpal.rs, write-fonts/generated/generated_font.rs, write-fonts/generated/generated_gdef.rs, write-fonts/generated/generated_gpos.rs, write-fonts/generated/generated_gsub.rs, write-fonts/generated/generated_hmtx.rs, write-fonts/generated/generated_layout.rs, write-fonts/generated/generated_name.rs, write-fonts/generated/generated_post.rs, write-fonts/generated/generated_stat.rs, write-fonts/generated/generated_test_formats.rs, write-fonts/generated/generated_test_offsets_arrays.rs, write-fonts/generated/generated_test_records.rs, write-fonts/generated/generated_variations.rs, write-fonts/generated/generated_vmtx.rs, write-fonts/src/tables/layout.rs
I'm willing to conceed that this was my mistake.
(just merge me)
=> [codegen] Learn to spell 'exceed'

read-fonts/src/tables/glyf.rs, write-fonts/Cargo.toml, write-fonts/src/tables.rs, write-fonts/src/tables/glyf.rs
This can naively compile non-component, non-variable glyphs.
Very much a checkpoint, but I think it makes sense to iterate in-repo for this work?
=> Initial simple glyph compilation

write-fonts/src/tables/glyf.rs
I'd left this as a TODO in the first patch.
=> Compute repeating flags when compiling glyphs

write-fonts/src/tables/glyf.rs
This uncovers a difference in how we encode SimpleGlyphFlags in the case where there is a single repeat, and changes our implementation to match fontmake's.
=> Add test for glyph with multiple contours

Cargo.toml, font-types/Cargo.toml, otexplorer/Cargo.toml, punchcut/Cargo.toml, read-fonts/Cargo.toml, write-fonts/Cargo.toml
=> Make it easy to set the version

write-fonts/src/pens.rs
Cannot add to font-types due to lack of kurbo.
=> Add fn to convert PathEl => PenCommand, write a BezPath to a Pen

Cargo.toml, resources/scripts/version-requirements.txt, resources/scripts/version.py
TIL we have dependencies and dev-dependencies
Merge me.
=> Script to update version

Cargo.toml, font-codegen/Cargo.toml, otexplorer/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml, write-fonts/Cargo.toml
Ran `Ran python3 resources/scripts/version.py --ver 0.0.6`
Built on top of #243. Merge me.
=> Set version to 0.0.6

Cargo.toml, font-codegen/Cargo.toml, otexplorer/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml, write-fonts/Cargo.toml
Ran `python3 resources/scripts/version.py --ver 0.0.6`
Merge me
=> Be 0.0.6 please

Cargo.toml, font-codegen/Cargo.toml, otexplorer/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml, write-fonts/Cargo.toml
Ran `python3 resources/scripts/version.py --ver 0.1.0`
Fixes #247.
=> Update version to 0.1.0

read-fonts/src/tables/layout.rs
=> [clippy]: Push the rock back up the hill

Cargo.toml, README.md
=> Fixup release docs, set release branch

resources/test_fonts/rebuild.sh
Use venv like a pro.
Merge me!
=> rebuild.sh again

font-types/src/uint24.rs
Just merge. Helps with #269.
Hoisted out of #271
=> Make Uint24 Default

write-fonts/src/tables/cmap.rs
Add an api to write a cmap from a high level definition. Builds on #272.
I intend the internals of `from_mappings` to change over time, but the entrypoint to remain stable.
=> Helper for constructing a simple cmap4

font-codegen/Cargo.toml, font-types/Cargo.toml, otexplorer/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml, write-fonts/Cargo.toml
Ran `./resources/scripts/bump-version.sh font-types read-fonts write-fonts patch`
Just merge.
=> Bump the patch version of font-types, read-fonts, write-fonts

write-fonts/src/round.rs
See https://github.com/googlefonts/fontmake-rs/issues/147
=> Add ot_round => u16 for hmtx

write-fonts/src/tables/glyf.rs
To match the one for components.
Just merge.
=> contour accessor

skrifa/src/meta/metrics.rs, skrifa/src/scale/glyf/hint/mod.rs, skrifa/src/scale/glyf/scaler.rs
Fix some comment typos and pass mutable contour slice to hinter.
Merge me!
=> [skrifa] small fixes

write-fonts/Cargo.toml
=> write-fonts => 0.1.5

font-codegen/src/fields.rs, font-codegen/src/parsing.rs, font-codegen/src/record.rs, resources/codegen_inputs/fvar.rs, resources/codegen_inputs/test_records.rs, write-fonts/generated/generated_fvar.rs, write-fonts/generated/generated_test_records.rs, write-fonts/src/codegen_test.rs, write-fonts/src/tables/fvar.rs
And use it on fvar and prove it works.
=> Add the ability to attach validation to a table

write-fonts/src/tables/cmap.rs
Test exposes and fixes what I believe to be the issue underlying https://github.com/googlefonts/fontmake-rs/issues/223.
I have also tested by building Texturina with this fontmake-rs with this fix, fontmake-rs no longer kerplodes and produces a cmap that ttx can read.
=> Fix cmap4 construction for large deltas

write-fonts/src/tables/glyf.rs
The lack of iter on Contour is confusing given it does have into iter. Maybe it could just have iter? Or if not I can at least learn why not.
=> Wherefore aren't thou iter?

write-fonts/src/write.rs
This writes nothing in the None case and the contents in the Some case.
(just merge me)
=> Impl<T: FontWrite> FontWrite for Option<T>

font-types/src/fixed.rs
=> Derive Hash for fixed-point types

read-fonts/src/tables/variations.rs
=> Expose constructors & consts on variation flag types

README.md
=> Fixup githooks info in readme

skrifa/src/meta/charmap.rs
Saw this mentioned in https://github.com/googlefonts/fontations/pull/316/files#r1158733973 and thought it was a reasonable little bit of cleanup?
JMM
=> Use let else guards where appropriate

skrifa/src/meta/charmap.rs
Moves the symbol check directly into the `or_else` closure in `CodepointSubtable::map_impl`. Removes the extra indirection.
If this is desirable, JMM.
=> [skrifa] inline and simplify symbol lookup

write-fonts/src/tables/gvar.rs
I just adore printing and copying things. JMM.
=> Add Clone, Debug for a couple of gvar things

write-fonts/src/tables/glyf.rs
@anthrotype said wise things that I don't want to forget :)
=> Comment tweaks

font-codegen/Cargo.toml, font-types/Cargo.toml, otexplorer/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml, write-fonts/Cargo.toml
font-types => 0.1.4
read-fonts => 0.1.4
write-fonts => 0.1.9
=> Bump patch versions to release recent changes

read-fonts/build.rs
=> Fix release blockade

.github/workflows/rust.yml
=> [ci] Run 'cargo package' in ci

write-fonts/src/font_builder.rs
JMM
Fixes https://github.com/googlefonts/fontations/issues/350
=> Pad tables to 4 bytes

write-fonts/src/tables/variations.rs
Split out from #353 
JMM if looks ok
=> Expose and fix issue with packing delta runs of 0

write-fonts/src/tables/variations.rs
=> No more than 64 zeros please, we use 6 bits to encode run length

write-fonts/Cargo.toml
=> write-fonts => 0.1.11

write-fonts/src/tables/glyf.rs
Allocates temporary  `pts` and `quad_pts` buffers in `simple_glyphs_from_kurbo` that are reused for each path element.
Also changes the `first` and `last` contour point methods in `InterpolatableContourBuilder` to return iterators which can be compared with the `Iterator::eq` method (rather than allocating vecs for comparison).
=> Reuse temporary allocations for implied on curve filtering

font-test-data/Cargo.toml
this should unblock publishing the rest of the crates
=> add publish = false to font-test-data

font-test-data/Cargo.toml
=> add release=false to font-test-data for cargo-release

write-fonts/src/graph.rs
My previous implementation was a looser interpretation of hb, but for the promotion/splitting work I want to have as much of the general code match HB has possible, so I can know bugs are in the implementation, not in the design.
based on #385, which should go in first.
=> More closely follow hb-repacker when isolating/assigning spaces

font-types/Cargo.toml, font-types/src/bbox.rs, font-types/src/fixed.rs, font-types/src/fword.rs, font-types/src/glyph_id.rs, font-types/src/lib.rs, font-types/src/longdatetime.rs, font-types/src/name_id.rs, font-types/src/offset.rs, font-types/src/pen.rs, font-types/src/point.rs, font-types/src/raw.rs, font-types/src/serde_test.rs, font-types/src/tag.rs, font-types/src/uint24.rs, font-types/src/version.rs
=> Add optional serde support to font-types

write-fonts/src/tables/variations.rs
=> Add comment with link

read-fonts/src/tables/gvar.rs, write-fonts/src/tables/gvar.rs
IIUC we currently require that all deltas are present which seems like it woulud make sparse points for iup difficult
=> Make it possible to write sparse tuple stores

write-fonts/src/tables/variations.rs
=> Test to expose iup loop stopping one cycle early + fix

font-codegen/Cargo.toml, font-types/Cargo.toml, otexplorer/Cargo.toml, read-fonts/Cargo.toml, write-fonts/Cargo.toml
#393 seems to have never been released. JMM.
=> font-types => 0.1.6

write-fonts/src/pens.rs, write-fonts/src/tables/glyf.rs
See https://github.com/googlefonts/fontmake-rs/issues/285#issuecomment-1552385007
=> Use control box for glyf

write-fonts/Cargo.toml
Intended use is releasing #415
=> write-fonts => 0.3.4

font-types/README.md, font-types/src/lib.rs
=> Forbid unsafe in font-types

write-fonts/Cargo.toml
Intended to be used to release #422
=> write-fonts patch bump => 0.3.6

write-fonts/src/error.rs, write-fonts/src/graph.rs
Some fixups motivated by trying to actually use these errors in fea-rs.
- Reexport errors at top-level
- Don't impl Debug for Graph, since it ends up being unintelligable
JMM™️
=> [write-fonts] Error tweaks

write-fonts/src/tables/variations.rs
Fixes https://github.com/googlefonts/fontc/issues/313
=> [write-fonts] Fix writing of PackedPointNumbers

font-types/src/uint24.rs, read-fonts/src/tables/postscript.rs, read-fonts/src/tables/postscript/index.rs
Adds support for reading data from CFF INDEX arrays.
=> CFF: add parsing for INDEX data

write-fonts/src/tables/layout.rs
=> Improve docs and add as_inner to layout newtypes

skrifa/src/variation.rs
=> Don't panic!

write-fonts/src/tables/glyf.rs
=> Make Bbox union public and fix a bug in it

write-fonts/Cargo.toml
=> write-fonts patch bump to 0.5.1

write-fonts/src/tables/name.rs
Something funny is up in fontc, where it looks like NameRecords are being sorted incorrectly in some circumstances? See https://github.com/googlefonts/fontc/pull/321.
This test is probably redundant, but it should more clearly assert that the order of records in a vec does not influence the order they end up in in the name table.
=> Add another test of Name sort order

read-fonts/src/font_data.rs
This should be useful for ffi; see https://skia-review.googlesource.com/c/skia/+/709376
=> [read-fonts] Make FontData::as_bytes pub

font-types/src/tag.rs
=> [font-types] Add Tag::from_u32

write-fonts/Cargo.toml
=> write-fonts 0.6.1 => 0.6.2

resources/scripts/release.sh
=> Support pushing all or one package

resources/codegen_inputs/variations.rs, write-fonts/generated/generated_variations.rs
=> [codegen] Add #[compile] attr to IVS format

font-types/src/tag.rs
That is, if the target format is human-readable we will serialize Tag as a string, and otherwise we will serialize it as raw bytes.
Does this make sense? mmaaaaybe? It's definitely nice to serialize as a string. Whether we even need to think about supporting non-utf8 tags is unclear to me; they may exist in fonts in the wild, but they shouldn't be used in new fonts.
=> [font-types] Serde Tag as str when target is text

skrifa/benches/scale.rs
Such that the calculations for points are not all optimized away.
=> [scaler-bench] Do some work in the callbacks

read-fonts/generated/generated_variations.rs, resources/codegen_inputs/variations.rs, write-fonts/generated/generated_variations.rs
I need this for the ItemVariationStore builder type.
=> [codegen] More traits for VariationRegion

font-codegen/Cargo.toml, font-codegen/src/parsing.rs
There were a bunch of breaking changes in syn that took a bit of hacking to fix.
=> Update font-codegen deps

font-codegen/Cargo.toml, font-types/Cargo.toml, otexplorer/Cargo.toml, read-fonts/Cargo.toml, write-fonts/Cargo.toml
I need the fix for deserializing tags (#527) and might as well also take the ergonomics improvements in write-fonts (#526, #525)
=> We love publishing our crates :)

write-fonts/Cargo.toml
To release #530 so fontc can consume
=> write-fonts => 0.10.1

font-codegen/Cargo.toml, font-codegen/src/main.rs, otexplorer/Cargo.toml, otexplorer/src/main.rs
Only used in non-published crates, this minorly changed some syntax.
JMM
=> Update xflags to 0.3

write-fonts/src/lib.rs, write-fonts/src/util.rs
As it doesn't seem to actually be used by any public consumer; we can revist this if somebody needs it.
JMM
=> [write-fonts] Make util module private

skrifa/src/scale/cff/hint.rs
This completes the "blues" portion of hinting by implementing hint capture-- determining whether incoming hints fall within one of the blue zones and, if so, adjusting for alignment accordingly.
Based on `cf2_blues_capture` at https://gitlab.freedesktop.org/freetype/freetype/-/blob/80a507a6b8e3d2906ad2c8ba69329bd2fb2a85ef/src/psaux/psblues.c#L465
=> [skrifa] CFF hinting: blue capture

write-fonts/src/error.rs
The main motivation here was to provide more information about how to debug a packing error.
=> [write-fonts] Improve error docs

write-fonts/src/graph.rs
This is three small commits that came out of my work on splitting pairpos format 2, with rationale in the individual commit messages. Nothing in these commits changes any observable behaviour.
=> Graph packing fixups

write-fonts/src/lib.rs
In looking at #622 I noticed a missing word, and then rereading the paragraph I had a few
other little nits.
JMM
=> [docs] Fixup write-fonts lib docs

write-fonts/Cargo.toml, write-fonts/src/tables/glyf/simple.rs
because now we can: https://github.com/linebender/kurbo/pull/306
JMM
=> use latest kurbo's BezPath::control_box instead of ControlBoundsPen

font-codegen/src/fields.rs, font-codegen/src/table.rs, read-fonts/generated/generated_glyf.rs, read-fonts/generated/generated_layout.rs, read-fonts/src/array.rs, read-fonts/src/read.rs, read-fonts/src/tables/gsub.rs, read-fonts/src/tables/postscript/index.rs, read-fonts/src/tests/gpos.rs, write-fonts/src/tables/glyf/simple.rs, write-fonts/src/tables/stat.rs, write-fonts/src/tests/test_gpos.rs
Apparently running clippy on skrifa is crashing the compiler on my machine, will open something for that in rustc shortly. Let's see if it works in CI?
=> clippy & rustdoc fixups

write-fonts/src/tables/variations/ivs_builder.rs
I ended up very confused in the course of investigating #652, which led me to try and improve a bunch of names and docs in the ItemVariationStore builder code. This includes the test from #652 as well as a fix that is slightly more efficient than the one there, although that solution was also correct :)
cc @anthrotype
- closes #652
=> Fix Incorrect region indexes in ItemVariationStore

write-fonts/src/tables/variations/ivs_builder.rs
This change lets us build the 'unoptimized' version of this table which can be a more efficient choice in HVAR, in some cases.
cc @anthrotype, is this fit for your needs?
=> [write-fonts] Tweak VariationStoreBuilder for HVAR case

skrifa/Cargo.toml
for we bumped read-fonts minor and skrifa depends on it
=> bump skrifa minor

skrifa/src/scale/scaler.rs
Simply flips the hinting bit on the CFF scaler if a hinting mode is requested in `ScalerBuilder`.
JMM
=> [skrifa] plumb hinting request to CFF scaler

read-fonts/src/tables/layout.rs
This was something I needed in the process of trying to decompose class-based kern rules.
=> [read-fonts] Add ClassDef::iter

read-fonts/src/tables/layout.rs
This is not something we really expect to see in the wild very much, but it feels like something we will want for completeness in any case, so here we are.
=> [read-fonts] Decoding Device table values

font-codegen/Cargo.toml, font-types/Cargo.toml, otexplorer/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml, write-fonts/Cargo.toml
=> [chore] Bump patch version on read-fonts & font-types

read-fonts/src/tables/variations.rs, skrifa/src/color/instance.rs
Make use of the type system to appropriately apply floating point deltas to target values.
Motivated by comments on API design in #725. If it looks good, will merge into that PR.
=> Maybe better API for floating point IVS

write-fonts/src/tables/variations/ivs_builder.rs
Fixes #733
#735 reproduces the bug, this one fixes it
=> [ivs_builder] prune unused regions

skrifa/src/outline/cff/hint.rs
Fixes a midpoint calculation that overflows at larger sizes.
Effectively replaces `(a + b) / 2` with `a + (b - a) / 2` to avoid the overflow (as FT does). Adds a hint map test with the data from the specific font/glyph/size that triggered this.
=> [skrifa] fix CFF hinting overflow

skrifa/src/outline/glyf/hint/engine/control_flow.rs, skrifa/src/outline/glyf/hint/engine/dispatch.rs, skrifa/src/outline/glyf/hint/engine/mod.rs
Implements the "managing the flow of control" group of instructions (https://learn.microsoft.com/en-us/typography/opentype/spec/tt_instructions#managing-the-flow-of-control)
=> [skrifa] tthint: control flow

skrifa/src/outline/mod.rs
Reading this with an eye to exposing it to people who don't work with fonts I think it's worth linking to docs on path commands.
JMM
=> Not everyone knows about path commands, add link

skrifa/src/outline/glyf/hint/definition.rs, skrifa/src/outline/glyf/hint/engine/control_flow.rs, skrifa/src/outline/glyf/hint/engine/definition.rs, skrifa/src/outline/glyf/hint/engine/dispatch.rs, skrifa/src/outline/glyf/hint/engine/graphics_state.rs, skrifa/src/outline/glyf/hint/engine/mod.rs, skrifa/src/outline/glyf/hint/error.rs, skrifa/src/outline/glyf/hint/graphics_state/mod.rs, skrifa/src/outline/glyf/hint/program.rs
Implements the "defining and using functions and instructions" group (https://learn.microsoft.com/en-us/typography/opentype/spec/tt_instructions#defining-and-using-functions-and-instructions).
=> [skrifa] tthint: function definition and dispatch

write-fonts/src/tables/layout.rs
For format1 we were just taking the number of glyphs, but as the values stored are u16 it should be number of glyphs * 2.
This was the root cause of an unexpected packing failure.
=> [write-fonts] Fix bug in ClassDef format selection

.gitignore
=> Add a .gitignore entry for venv/

font-types/src/glyph_id.rs
=> [font-types] From<u16> for GlyphId

fauntlet/Cargo.toml, skrifa/Cargo.toml
Primarily to release #818
minor bump due to @dfrg's hinting changes
=> Skrifa to 0.17.0

font-test-data/Cargo.toml, otexplorer/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml, write-fonts/Cargo.toml
=> Version bumps

write-fonts/Cargo.toml
=> [write-fonts] Make dot2 feature non-default

skrifa/src/outline/glyf/hint/engine/delta.rs, skrifa/src/outline/glyf/hint/engine/outline.rs, skrifa/src/outline/glyf/hint/engine/round.rs
Just grinding out the remaining tests.
Closes #803
=> [skrifa] tthint: finish up unit tests

read-fonts/src/tables/variations.rs
To support computation of glyph deltas as HarfBuzz does
=> [read-fonts] tvs: compute f32 scalar

read-fonts/src/tables/glyf.rs
Adds a new `PointCoord` trait that allows us to abstract over the coordinate type for glyf outline points. Changes `SimpleGlyph::read_points_fast()` and `to_path()` to support this, allowing usage of `F26Dot6`, `i32` and `f32` coordinate types for both.
Mostly to support HarfBuzz style glyf processing but also just makes the code more flexible in general.
=> [read-fonts] abstract type for glyf point coords

skrifa/src/outline/glyf/hint/engine/definition.rs, write-fonts/src/collections.rs
=> Clippy day

font-types/src/glyph_id.rs, klippa/Cargo.toml, klippa/src/hmtx.rs, klippa/src/lib.rs, klippa/src/main.rs
Also replace BTreeSet with IntSet.
--unicodes option is needed for setting up test suite because we use harfbuzz tests. I only added most basic support for this option.
=> [subset] Add --unicodes command line option

int-set/src/bitpage.rs, int-set/src/bitset.rs, int-set/src/lib.rs
To allow for reverse iteration.
=> Make IntSet iterator double ended.

skrifa/src/color/mod.rs, skrifa/src/color/traversal.rs
A missing ClipList was passed up as a PaintError resulting in a paint failure. 
Remove confusion about how to handle a missing ClipList vs. a missing entry in a ClipList
by not returning a nested Result<Option<>> but a simpler Option<>.
Fixes #909.
=> [skrifa] Fix COLRv1 painting for font without ClipList

otexplorer/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml, write-fonts/Cargo.toml
Missed in previous release ver bump.
=> Bump read-fonts for release

int-set/src/bitpage.rs, int-set/src/bitset.rs, int-set/src/lib.rs
This processing framework allows applying arbitrary bitwise operations between two bit sets. Ported fairly directly from the harfbuzz implementation in https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-bit-set.hh#L483. In the public api of IntSet I've added support for union() and intersect().
=> [IntSet] Implement the set processing framework.

write-fonts/src/tables/layout.rs
=> [write-fonts] Fix incorrect classdef format selection

read-fonts/src/tables/post.rs
I want to ensure we have a test encoding how versioned fields work.
---
so this table is the only real example of a place where we have the funky business of a later version of a table (3.0) having fewer fields than an earlier version (2.x), but it as it happens we are already handling this correctly; when a field is versioned and the table has a (major, minor) version pair than we follow something like semver: after the first version (generally 1.0 but 0.5 in the case of maxp) then any subsequent major version changes extend the first table version, but do not include fields from previous major versions.
In the process of figuring this all out I noticed the useful [table version numbers](https://learn.microsoft.com/en-us/typography/opentype/spec/otff#table-version-numbers) section of the …
=> [read] Add test case for parsing post table

read-fonts/generated/generated_varc.rs, read-fonts/src/tables/varc.rs, resources/codegen_inputs/varc.rs
What luck we already have an Index2.
=> Make the VARC axis index list accessible

README.md
Part of #420
[rendered](https://github.com/googlefonts/fontations/tree/rsheeter-patch-1)
JMM
=> Add badges and fuzzing documentation to README.md

font-types/src/fixed.rs, font-types/src/lib.rs, read-fonts/generated/generated_varc.rs, read-fonts/src/font_data.rs, read-fonts/src/read.rs, read-fonts/src/tables/varc.rs, read-fonts/src/tables/variations.rs, resources/codegen_inputs/varc.rs, write-fonts/src/tables/variations.rs
Not done but a significant enough step I'd like to land it.
=> Begin to parse VARC glyphs

.github/workflows/rust.yml, Cargo.toml, read-fonts/Cargo.toml, read-fonts/src/tables/varc.rs, resources/githooks/pre-push, skrifa/Cargo.toml
Reading the decomposed transform is relatively useless so I added a method to get affine matrix. That took me on a wee bit of a core_maths adventure.
Builds on #943.
=> Read the VARC transform

fuzz/Cargo.toml, fuzz/fuzz_targets/fuzz_basic_metadata.rs, fuzz/fuzz_targets/fuzz_name.rs
=> A little more fuzzing

fuzz/Cargo.toml, fuzz/fuzz_targets/fuzz_skrifa_outline.rs, read-fonts/src/tables/glyf.rs
Let's boost https://storage.googleapis.com/oss-fuzz-coverage/fontations/reports/20240615/linux/src/fontations/report.html a little :)
Part of #420.
JMM if happy.
=> First crack at fuzzing for Skrifa outlines

fuzz/fuzz_targets/fuzz_skrifa_outline.rs
Followup to https://github.com/googlefonts/fontations/pull/955#pullrequestreview-2123321332 from #955.
Contributes to #420.
JMM if happy.
=> Randomize the HintingMode

int-set/Cargo.toml, int-set/src/input_bit_stream.rs, int-set/src/lib.rs, int-set/src/output_bit_stream.rs, int-set/src/sparse_bit_set.rs
https://w3c.github.io/IFT/Overview.html#sparse-bit-set-decoding
=> [IntSet] Add an implementation of encoding/decoding IntSet's to/from the IFT sparse bit set encoding.

read-fonts/src/tables/fvar.rs
Fixes #958.
Do not overflow in scaling computations in axis normalization by using saturating math.
=> [read-fonts] Avoid overflow in axis normalization

fuzz/Cargo.toml, fuzz/fuzz_targets/fuzz_skrifa_color.rs, fuzz/fuzz_targets/fuzz_skrifa_outline.rs, fuzz/fuzz_targets/helpers.rs
Contributes to #420. Built on #973.
JMM if happy
=> Add a rudimentary COLR fuzzer

README.md
=> Document fuzzer issue reproduction

klippa/Cargo.toml, klippa/src/hmtx.rs, klippa/src/lib.rs, klippa/src/parsing_util.rs, read-fonts/Cargo.toml, read-fonts/src/tables/cmap.rs
populate_gids is incomplete yet, we need to do closure for COLR and layout tables later.
=> [klippa] populate_unicodes and closure glyphs for cmap, composite glyphs

read-fonts/generated/generated_layout.rs, read-fonts/src/tables/gpos.rs, read-fonts/src/tables/gsub.rs, read-fonts/src/tables/lookupflag.rs, resources/codegen_inputs/layout.rs, write-fonts/generated/generated_layout.rs, write-fonts/src/graph.rs, write-fonts/src/graph/splitting/mark2base.rs, write-fonts/src/graph/splitting/pairpos.rs, write-fonts/src/table_type.rs, write-fonts/src/tables/gpos.rs
Based on #937.
This has one funny issue where some of the code we are generating isn't being formatted correctly by rustfmt; this is a known issue in rustfmt and I'll look into a fix in a separate PR.
=> [read/write] Make mark_filter_set conditonal on flag

int-set/src/bitset.rs, int-set/src/lib.rs
=> [int-set] Fix subtraction overflow in remove_range.

int-set/src/bitset.rs
It was incorrectly using page.index in place of page.major_value when calculating the page end.
=> [int-set] fix bug in iter_ranges() of IntSet.

int-set/src/bitpage.rs, int-set/src/lib.rs
- Fix IntSet::len() for inverted sets with domains smaller than u32.
- Fix overflow bug in BitPage iter: next() was casting an i32 (backwards_index) to u32 prior to comparison. If backwards_index is -1 this leads to unexpected behaviour.
- Fix iter_ranges() on discontinous domains: consider two values adjacent if they are adjancent in the ordered_values() iterator instead of requiring them to be adjacent in the u32 domain.
- Fix iter_ranges() on inclusive sets w/ discontinous domains. Adjacent ranges need to be merged together.
=> [int-set] Fix several bugs in IntSet found by the fuzzer:

fuzz/fuzz_targets/fuzz_int_set.rs
Further extends the IntSet fuzzer to allow it to exercise the remaining parts of the public API that the current implementation does not cover:
- Inverted sets (invert(), is_inverted())
- Limited domain types (including discontinous domain types).
- Inclusive Iteration.
Additionally address some comments from the review of #1008 including switching to use "Cursor".
=> [int-set] Extend the IntSet fuzzer to exercise remaining public api methods.

klippa/src/lib.rs, read-fonts/src/tables/colr.rs, read-fonts/src/tables/variations.rs
Planning for COLR is not done yet. Things left: remapping for layer/palette indices, varstore planning.
=> [klippa] closure for COLR table

int-set/src/bitpage.rs, int-set/src/bitset.rs
Iterate over only the existing pages contained within the range instead of all possible pages in the range.
=> [int-set] Optimize remove_range.

fauntlet/Cargo.toml, font-codegen/Cargo.toml, font-types/Cargo.toml, klippa/Cargo.toml, otexplorer/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml, write-fonts/Cargo.toml
that is, types/read/write/skrifa
=> [chore] Bump all crate versions

read-fonts/src/collections/int_set/mod.rs
Consider two sets with different membership types, but equivalent effective member sets to be equal (and update hash to match).
=> [int-set] Fix equality and hash for intset.

write-fonts/src/tables/layout.rs
This is in write-fonts so it isn't really used much, but this was still definitely wrong.
=> [write-fonts] Fix logic in ClassDef::get

skrifa/src/outline/autohint/axis.rs, skrifa/src/outline/autohint/latin/edges.rs, skrifa/src/outline/autohint/latin/mod.rs, skrifa/src/outline/autohint/latin/segments.rs, skrifa/src/outline/autohint/latin/widths.rs, skrifa/src/outline/autohint/metrics.rs
Edges are sets of segments that all lie within a threshold based on stem widths.
Here we compute edges from the segment list, assign properties (round, serif, links) and then associate them with blue zones.
=> [skrifa] autohint: Latin edges

font-codegen/README.md, font-codegen/src/fields.rs, font-codegen/src/parsing.rs, read-fonts/generated/generated_test_conditions.rs, read-fonts/src/codegen_test.rs, resources/codegen_inputs/test_conditions.rs, write-fonts/generated/generated_test_conditions.rs, write-fonts/src/codegen_test.rs
This allows for custom conditions to be tested against. Will be needed for IFT format 2 code gen. To begin with add any_flag condition which is true if any of the input flags are set.
=> Add 'if_cond(...)' to codegen.

fuzz/fuzz_targets/fuzz_basic_metadata.rs
=> Read rudimentary axis metadata from avar

font-test-data/src/lib.rs, font-types/src/uint24.rs, fuzz/fuzz_targets/fuzz_sparse_bit_set_decode.rs, fuzz/fuzz_targets/int_set_op_processor.rs, read-fonts/generated/generated_ift.rs, read-fonts/src/collections/int_set/bitset.rs, read-fonts/src/collections/int_set/input_bit_stream.rs, read-fonts/src/collections/int_set/mod.rs, read-fonts/src/collections/int_set/sparse_bit_set.rs, read-fonts/src/tables/ift.rs, resources/codegen_inputs/ift.rs, skrifa/src/patchmap.rs, write-fonts/generated/generated_ift.rs, write-fonts/src/write.rs
Define the structure and implement parsing of codepoint only entries.
Specification is here: https://w3c.github.io/IFT/Overview.html#patch-map-format-2
=> Begin Implementation of IFT Format 2 Parsing.

read-fonts/src/array.rs
=> [read] Make VarLenArray::get docs scarier

font-test-data/src/lib.rs, read-fonts/generated/generated_ift.rs, resources/codegen_inputs/ift.rs, skrifa/src/patchmap.rs, write-fonts/generated/generated_ift.rs
Add tests for feature and design space intersection.
=> Implement IFT format 2 design space parsing.

skrifa/src/collections.rs, skrifa/src/instance.rs
I hope that's okay to add, I want to be able to store location's in a hashmap so I can map combinations of fonts + location to specific PDF fonts in my crate.
=> Add Hash impl for Location

font-test-data/src/lib.rs, read-fonts/src/tests/test_helpers.rs
Simplifies the construction of test data via BeBuffer.
=> Add be_buffer! macro.

read-fonts/generated/generated_gasp.rs, read-fonts/src/table_provider.rs, resources/codegen_inputs/gasp.rs
Add a tag and accessor for it.
Tests are failing for me locally, but they are on main as well.
=> gasp is a top-level table

skrifa/src/outline/autohint/latin/edges.rs, skrifa/src/outline/autohint/latin/metrics.rs, skrifa/src/outline/autohint/style.rs
Computes scaled style metrics for CJK autohinting.
=> [skrifa] autohint: scale CJK metrics

Cargo.toml, font-types/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml
Patch for font-types, minor for read-fonts and skrifa
=> [chore] Bump font-types, read-fonts, skrifa

font-codegen/Cargo.toml
This removes a duplicated dependency in the build tree.
=> font-codegen: Update to toml 0.8

skrifa/src/outline/autohint/hint.rs, skrifa/src/outline/autohint/instance.rs, skrifa/src/outline/autohint/latin/blues.rs, skrifa/src/outline/autohint/latin/edges.rs, skrifa/src/outline/autohint/latin/hint.rs, skrifa/src/outline/autohint/latin/metrics.rs, skrifa/src/outline/autohint/latin/widths.rs, skrifa/src/outline/autohint/metrics.rs, skrifa/src/outline/autohint/mod.rs, skrifa/src/outline/autohint/shape.rs
Adds the infrastructure to support shaping without making any functional changes.
A little bit of churn but the intention is to allow future PRs to be more focused.
=> [skrifa] autohint shaper abstraction

Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml
=> [chore] bump read/skrifa patch

fauntlet/src/font/skrifa.rs
As suggested in https://github.com/googlefonts/fontations/pull/1171#discussion_r1786734469
JMM
=> [fauntlet] improve readability in skrifa outline extraction

read-fonts/src/tables/cmap.rs
Use manually constructed buffers containing cmap12 tables rather than just including the full fuzz test case font.
Fixes #1194
=> [read-fonts] restore cmap 12 tests

klippa/src/lib.rs, klippa/src/serialize.rs
Also added a few APIs like push/embed/copy_bytes
=> [klippa] custom serializer step 1: add struct definition

font-types/src/fixed.rs
Per f2f, let's just stop chasing these panics.
JMM
=> [font-types] wrapping add/sub for fixed point types

font-types/src/lib.rs, read-fonts/src/lib.rs
=> Small typo in CFF_SFTN_VERSION

skrifa/src/outline/cff/mod.rs
ref #1223 and https://issues.oss-fuzz.com/issues/377574377
first commit contains failing test
=> [skrifa] cff: fix overflow in ivs offset

skrifa/src/outline/cff/mod.rs
Detected add with overflow with computing the private subroutines offset.
ref https://issues.oss-fuzz.com/issues/377965575
Factored out the private dict parsing to enable testing this directly. First commit contains failing test.
=> [skrifa] cff: prevent overflow in subrs offset

Cargo.toml, font-test-data/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml, write-fonts/Cargo.toml
Minor for write-fonts, patch for most everything else
=> [chore] Bump versions

font-codegen/src/parsing.rs, fuzz/Cargo.toml, fuzz/fuzz_targets/fuzz_ift_patch_group.rs, read-fonts/generated/generated_ift.rs, read-fonts/src/lib.rs
Fix a found addition overflow in IFT parsing.
=> [IFT] begin to implement a fuzzer for the patch_group.rs API.

font-types/src/name_id.rs
- define a LAST_RESERVED_NAME_ID const
- mark a bunch of things as #[inline]
- add is_reserved and saturating_add methods
- tweak the debug representation
=> [types] API additions to NameId

skrifa/src/outline/autohint/outline.rs
FreeType's outline orientation function computes the control box and then uses the extents to calculate a shift value that drops up to 14 bits of precision for each coordinate to avoid overflows when accumulating signed area.
Our inputs are always 16 bits so this does nothing but waste cycles and this patch drops that code. Also updates the accumulator to 64 bits just to be defensive against overflows.
=> [skrifa] simplify orientation computation

write-fonts/src/tables/glyf/simple.rs
=> [write] Reexport CurvePoint type from read-fonts

Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml
To release bugfixes for Skia roll.
=> [chore] bump patch for read-fonts/skrifa

Cargo.toml, skrifa/Cargo.toml
For Skia/Chrome roll.
Relevant changes:
5e4ce813 [skrifa] more advance width adjustments (#1320)
=> [chore] bump skrifa patch

read-fonts/src/tables/gvar.rs
This was intended to be applied to #1332 but didn't get pushed.
JMM
=> Gvar delta API fixup

write-fonts/src/tables/variations.rs
This gives a small file size saving with a large test font, although I am unsure if it is always optimal; most importantly, it makes fontations [match exactly the behaviour of fontTools](https://github.com/fonttools/fonttools/blob/eeaa499981c587/Lib/fontTools/ttLib/tables/TupleVariation.py#L467), as linked in the adjacent comment of the modified source.
=> Do not inline single bytes if they are followed by a zero

Cargo.toml, font-test-data/Cargo.toml, font-types/Cargo.toml, read-fonts/Cargo.toml, skrifa/Cargo.toml, write-fonts/Cargo.toml
Minor for read/write/skrifa (because of ift changes) and patch for test-data and font-types.
=> [chore] Bump crate versions

write-fonts/src/graph.rs, write-fonts/src/graph/splitting.rs
An oversight. This was causing an OTS failure in fontc's CI.
=> [write] Fix table splitting dropping markFilteringSet

Cargo.toml, write-fonts/Cargo.toml
=> [chore] Bump write-fonts patch version

write-fonts/src/tables.rs, write-fonts/src/tables/cpal.rs
=> [write-fonts] minimal cpal

Cargo.toml, write-fonts/Cargo.toml
=> write-fonts 0.36.3

read-fonts/src/tables/cmap.rs
This keeps the test with a group that ends at max value but reduces the range so that the test completes in reasonable time.
Fixes #1370 
JMM
=> [read-fonts] fix slow cmap 12 test

write-fonts/src/font_builder.rs
There is code for modifying 'head' for checksum computation which didn't ensure there was enough bytes in the head table.
Fixes fuzzer crash: https://oss-fuzz.com/testcase-detail/5496811662147584
=> Fix buffer overflow in font builder.

skrifa/src/glyph_name.rs
Not the most idiomatic, but does the job for me.
=> [skrifa] Synthesize glyph name if it's empty string

skrifa/src/color/mod.rs, skrifa/src/color/traversal.rs
Fixes https://github.com/googlefonts/fontations/issues/1418
=> [Skrifa/COLRv1] Add pop_layer_with_mode()

write-fonts/src/graph.rs
=> [write] Log types of overflowing tables

read-fonts/generated/generated_base.rs, resources/codegen_inputs/base.rs, write-fonts/generated/generated_base.rs
This looks like it was a typo/thunko?
A breaking change unfortunately...
JMM
=> [read/write] Fix offset type in FeatMinMaxRecord

fuzz/fuzz_targets/int_set_op_processor.rs, read-fonts/src/collections/int_set/bitpage.rs, read-fonts/src/collections/int_set/bitset.rs, read-fonts/src/collections/int_set/mod.rs
iter_from() iterates over set members >= to the given value. range() iterates over set members in the given range (inclusive).
=> Add public IntSet methods iter_from() and range().

font-types/src/version.rs
=> Fix wrong assertion message

skrifa/src/instance.rs
=> Partial revert of "bypass variation processing for default location"

read-fonts/src/array.rs, read-fonts/src/tables/layout.rs
particularly those that show up in harfrust profiles
JMM
=> inline some commonly used methods

klippa/src/gpos.rs, klippa/src/gpos/mark_lig_pos.rs, klippa/src/gpos/mark_mark_pos.rs
For MarkToLigPos and MarkToMarkPos subtables
=> [klippa] GPOS collect variation indices

read-fonts/src/tables/layout.rs
=> [Coverage/ClassDef] Add a cost() method

read-fonts/src/tables/gpos.rs, read-fonts/src/tables/value_record.rs
Adds a new `Value` type that is a fully resolved version of `ValueRecord`. This can be generated from `ValueRecord` or be read directly to avoid the conversion cost.
In addition, the `PairPosFormat2` gets a new `values()` method that is essentially a fast path for reading the position adjustments for a pair of classes.
This shows a measurable improvement in shaping performance. I'll send a harfrust PR containing the other half of this and let @behdad confirm on the HB side.
Still needs more tests before merging but the code itself should be ready for review.
=> [read-fonts] new Value type and PairPos2 fast path

.github/workflows/rust.yml, Cargo.toml, skrifa/src/outline/glyf/hint/engine/definition.rs
=> Bump MSRV to 1.80

klippa/src/gsubgpos.rs
=> [klippa] subset Context/ChainContext Format2 tables

read-fonts/src/tables/aat.rs
such that HarfRust can iterate over all values.
=> [read_fonts/aat] Expose more of the lookup internals

read-fonts/src/read.rs
When malicious or corrupted font data contains a variable sized array with a large count and a 0 length element, we will spin on parsing that element until we exhaust the count. This checks for 0 length elements and bails early returning the size up to that point.
Fixes https://github.com/harfbuzz/harfrust/issues/203
=> [read-fonts] Avoid timeout when computing array len

read-fonts/src/tables/aat.rs, read-fonts/src/tables/kern.rs
=> [read-fonts/aat] Make StateMachine header public

read-fonts/src/tables/aat.rs
This was already done for extended state tables. This may improve state transition performance in HarfRust, particularly for GeezaPro kerning.
=> [read-fonts] aat: preparse some state table fields

skrifa/src/color/instance.rs
Ref https://oss-fuzz.com/testcase-detail/5180237819478016 and https://g-issues.oss-fuzz.com/issues/439498857
First commit contains failing test.
=> Add with overflow in ColrInstance::var_deltas
